@startuml
hide circle
hide empty members
skinparam linetype ortho
class "PrF1 Start"
class "AP Hub"
"PrF1 Start" <--> "AP Hub"
class "PrF1 NW"
"PrF1 Start" <--> "PrF1 NW"
class "PrF1 South"
"PrF1 NW" <--> "PrF1 South"
"PrF1 South" --> "PrF1 SW Bronze Gate"
class "PrF1 SW Bronze Gate"
class "PrF1 East"
"PrF1 South" <--> "PrF1 East"
"PrF1 East" --> "PrF1 Middle Bronze Gate"
class "PrF1 Middle Bronze Gate"
class "Knight Start"
"PrF1 East" <--> "Knight Start"
"Knight Start" --> "Knight Arena"
class "Knight Arena"
"Knight Arena" --> "Knight Defeated"
class "Knight Defeated"
"Knight Defeated" --> "Knight Exit"
class "Knight Exit"
class "AvF9 Main Area"
"Knight Exit" <--> "AvF9 Main Area"
"AvF9 Main Area" --> "AvF9 NE Room"
"AvF9 Main Area" --> "AvF9 South Room"
"AvF9 Main Area" --> "AvF9 SE Cache"
"AvF9 Main Area" --> "AvF9 Boss Switch Room"
"AvF9 Main Area" --> "AvF9 Open SW Bronze Gate"
"AvF9 Main Area" <--> "AvF9 Main Area"
"AvF9 Main Area" <--> "AvF9 Main Area"
"AvF9 Main Area" <--> "AvF9 Main Area"
"AvF9 Main Area" --> "AvF9 East Gold Gate"
class "AvF9 NE Room"
class "AvF9 South Room"
"AvF9 South Room" --> "AvF9 South Shops Left Silver Gate"
"AvF9 South Room" --> "AvF9 South Shops Right Silver Gate"
class "AvF9 SE Cache"
class "AvF9 Boss Switch Room"
"AvF9 Boss Switch Room" --> "AvF9 Simon Says Room"
class "AvF9 Open SW Bronze Gate"
"AvF9 Open SW Bronze Gate" --> "AvF9 Open SW Left Wall"
"AvF9 Open SW Bronze Gate" --> "AvF9 Open SW Right Wall"
class "AvF9 East Gold Gate"
class "AvF9 West Gold Gate"
"AvF9 Main Area" <--> "AvF9 West Gold Gate"
"AvF9 West Gold Gate" --> "AvF9 Exit"
class "AvF9 South Shops Left Silver Gate"
class "AvF9 South Shops Right Silver Gate"
class "AvF9 Simon Says Room"
"AvF9 Simon Says Room" --> "AvF9 Bonus Entrance"
class "AvF9 Open SW Left Wall"
"AvF9 Open SW Left Wall" --> "AvF9 NW Teleport"
class "AvF9 Open SW Right Wall"
class "AvF9 Exit"
class "AvF9 Bonus Entrance"
"AvF9 Bonus Entrance" --> "ChF12 Fire Floor"
class "AvF9 NW Teleport"
class "AvF8 From Floor 9"
"AvF8 From Floor 9" --> "AvF8 NE Cache"
"AvF9 Exit" <--> "AvF8 From Floor 9"
class "ChF12 Fire Floor"
"ChF12 Fire Floor" --> "ChF12 Fire Floor Teleport"
"ChF12 Fire Floor" --> "AvB Main"
class "AvF8 NE Cache"
class "ChF12 Fire Floor Teleport"
class "AvB Main"
"AvB Main" --> "ChF10 Silver Gate"
"AvB Main" <--> "AvB Main"
"AvB Main" --> "AvB Main"
class "ChF10 Prison Stairs"
"AvB Main" <--> "ChF10 Prison Stairs"
class "ChF10 Silver Gate"
"ChF10 Silver Gate" --> "ChF10 Prison Stairs"
"ChF10 Silver Gate" --> "ChF10 Teleport Island"
class "ChF10 West"
"ChF10 Silver Gate" <--> "ChF10 West"
"ChF10 West" --> "ChF10 South Bronze Gate Room"
"ChF10 West" <--> "ChF10 West"
"ChF10 West" <--> "ChF10 West"
class "ChF10 Teleport Island"
"ChF10 Teleport Island" --> "ChF12 Teleport From Floor 11"
class "ChF10 East"
"ChF10 East" --> "ChF10 North Spikes"
"ChF10 East" --> "ChF10 SE Spikes"
"ChF10 East" --> "ChF10 Shop"
"ChF10 East" <--> "ChF10 East"
"ChF10 East" <--> "ChF10 East"
"ChF10 East" --> "ChF10 East"
"ChF10 West" <--> "ChF10 East"
class "ChF10 South Bronze Gate Room"
"ChF10 South Bronze Gate Room" --> "ChF10 East"
"ChF10 South Bronze Gate Room" --> "ChF10 Ledge"
class "AvF7 Start"
"ChF10 West" <--> "AvF7 Start"
"AvF7 Start" --> "AvF7 SE Gold Gate"
class "ChF12 Teleport From Floor 11"
"ChF12 Teleport From Floor 11" --> "ChF12 NW"
class "ChF12 Right Entrance"
"ChF10 East" <--> "ChF12 Right Entrance"
"ChF12 Right Entrance" --> "ChF12 Red Spikes Switch"
class "ChF10 North Spikes"
class "ChF10 SE Spikes"
class "ChF10 Shop"
class "ChF10 Ledge"
class "AvF7 SE Gold Gate"
"AvF7 SE Gold Gate" --> "AvF7 East"
class "ChF12 NW"
"ChF12 NW" <--> "ChF12 NW"
"ChF12 NW" --> "ChF12 NW"
class "ChF12 Red Spikes Switch"
"ChF12 Red Spikes Switch" --> "ChF12 Red Spikes"
class "AvF7 East"
"AvF7 East" --> "AvF7 East Southernmost Bronze Gate"
"AvF7 East" --> "AvF7 East Silver Gate"
"AvF7 East" --> "AvF7 East"
class "ChF11 South"
"ChF12 NW" <--> "ChF11 South"
"ChF11 South" --> "ChF11 SW In Wall"
"ChF11 South" --> "ChF11 West In Wall"
"ChF11 South" --> "ChF11 West Spikes"
"ChF11 South" --> "ChF11 Left West Shop"
"ChF11 South" --> "ChF11 Right West Shop"
"ChF11 South" --> "ChF11 Bottom East Shop"
"ChF11 South" --> "ChF11 Top East Shop"
"ChF11 South" --> "ChF11 Exits Bronze Gate"
"ChF11 South" <--> "ChF11 South"
"ChF11 South" <--> "ChF11 South"
"ChF11 South" <--> "ChF11 South"
"ChF11 South" <--> "ChF11 South"
"ChF11 South" <--> "ChF11 South"
"ChF11 South" <--> "ChF11 South"
"ChF11 South" --> "ChF11 North Secret Shops"
class "ChF12 Red Spikes"
"ChF12 Red Spikes" --> "ChF12 Southernmost Bronze Gate"
"ChF12 Red Spikes" --> "ChF12 Middle Shop"
"ChF12 Red Spikes" --> "ChF12 Middle in Wall"
"ChF12 Red Spikes" --> "ChF12 Middle Teleport"
"ChF12 Red Spikes" <--> "ChF12 Red Spikes"
"ChF12 Red Spikes" <--> "ChF12 Red Spikes"
"ChF12 Red Spikes" <--> "ChF12 Red Spikes"
"ChF12 Red Spikes" <--> "ChF12 Red Spikes"
"ChF12 NW" <--> "ChF12 Red Spikes"
"ChF12 Red Spikes" --> "ChF12 SW Hidden Hall"
class "AvF7 East Southernmost Bronze Gate"
class "AvF7 East Silver Gate"
"AvF7 East Silver Gate" --> "AvF7 SE In Wall"
class "AvF7 East North Bronze Gates"
"AvF7 East" <--> "AvF7 East North Bronze Gates"
"AvF7 East North Bronze Gates" --> "AvF7 East North Bronze Gates"
"AvF7 East North Bronze Gates" --> "AvF7 East Gold Gate"
class "ChF11 SW In Wall"
class "ChF11 West In Wall"
class "ChF11 West Spikes"
class "ChF11 Left West Shop"
class "ChF11 Right West Shop"
"ChF11 Right West Shop" --> "ChF11 Middle West Shop"
class "ChF11 Bottom East Shop"
"ChF11 Bottom East Shop" --> "ChF11 Puzzle"
class "ChF11 Top East Shop"
class "ChF11 Exits Bronze Gate"
class "ChF11 North"
"ChF11 South" <--> "ChF11 North"
"ChF11 North" --> "ChF11 North In Wall"
"ChF11 North" --> "ChF11 North Secret Shops"
class "ChF11 North Secret Shops"
class "ChB Main"
"ChF11 South" <--> "ChB Main"
"ChB Main" --> "ChB NW Room"
"ChB Main" --> "ChB West Room"
"ChB Main" --> "ChB East Room"
"ChB Main" --> "ChF11 Teleport Island"
class "Lich Exit"
"ChF11 South" <--> "Lich Exit"
class "ChF12 Southernmost Bronze Gate"
class "ChF12 Middle Shop"
class "ChF12 Middle in Wall"
class "ChF12 Middle Teleport"
class "ChF12 SW Hidden Hall"
"ChF12 SW Hidden Hall" --> "ChF12 SE Hidden Room"
"ChF12 SW Hidden Hall" --> "ChF11 Teleport from Floor 12"
class "AvF7 SE In Wall"
class "AvF7 East Gold Gate"
"AvF7 East Gold Gate" --> "AvF7 NW"
class "ChF11 Middle West Shop"
"ChF11 Middle West Shop" --> "ChF11 East In Wall"
class "ChF11 Puzzle"
class "ChF11 Bonus Entrance"
"ChF11 North" <--> "ChF11 Bonus Entrance"
class "ChF11 North In Wall"
class "AvF8 Start"
"ChF11 North" <--> "AvF8 Start"
"AvF8 Start" --> "AvF8 Main"
class "ChB NW Room"
class "ChB West Room"
class "ChB East Room"
class "ChF11 Teleport Island"
"ChF11 Teleport Island" --> "ChF11 Bonus Return"
class "ChF12 SE Hidden Room"
"ChF12 SE Hidden Room" --> "ChF12 Light Bridge"
class "ChF11 Teleport from Floor 12"
"ChF11 Teleport from Floor 12" --> "AvF9 Bonus Return"
class "AvF7 NW"
"AvF7 NW" --> "AvF7 NW Hidden Room"
class "ChF11 East In Wall"
class "AvB Teleport Room"
"ChF11 Bonus Entrance" <--> "AvB Teleport Room"
class "AvF8 Main"
"AvF8 Main" --> "AvF8 West Bronze Gate"
"AvF8 Main" <--> "AvF8 Main"
"AvF8 Main" <--> "AvF8 Main"
"AvF8 Main" --> "AvF8 Main"
"AvF8 Main" --> "AvF8 East"
"AvF8 Main" --> "AvF8 NW"
"AvF8 Main" --> "AvF8 Silver Gate"
"AvF8 Main" --> "AvF8 Gold Gate"
class "ChF11 Bonus Return"
class "ChF12 Light Bridge"
class "AvF9 Bonus Return"
"AvF9 Bonus Return" --> "AvF9 Bonus Return Light Bridge"
class "AvF7 NW Hidden Room"
"AvF7 NW Hidden Room" --> "AvF7 NW Gold Gate"
class "AvF8 West Bronze Gate"
class "AvF8 East"
class "AvF8 NW"
"AvF8 NW" --> "AvF8 North"
class "AvF8 Silver Gate"
"AvF8 Silver Gate" --> "AvF8 South"
class "AvF8 Gold Gate"
class "AvF9 Bonus Return Light Bridge"
class "AmF4 Start"
"AmF4 Start" --> "AmF4 SE"
"AmF4 Start" --> "AmF4 Start North Locked Shop"
"AmF4 Start" --> "AmF4 Start NE Locked Shop"
"AmF4 Start" --> "AmF4 Start SE Locked Shop"
"AvF9 Bonus Return" <--> "AmF4 Start"
class "AvF7 NW Gold Gate"
"AvF7 NW Gold Gate" --> "AvF7 SW"
class "AvF8 North"
class "AvF8 South"
"AvF8 South" --> "AvF8 Spike Trap Treasure Island"
"AvF8 South" --> "AvF8 West Island"
class "AvF8 Boss Switch"
"AvF8 Gold Gate" <--> "AvF8 Boss Switch"
class "PrB Start"
"AmF4 Start" <--> "PrB Start"
"PrB Start" --> "PrB Room 1"
class "AmF4 SE"
class "AmF4 Start North Locked Shop"
class "AmF4 Start NE Locked Shop"
class "AmF4 Start SE Locked Shop"
class "PrF3 Entrance"
"AmF4 Start" <--> "PrF3 Entrance"
"PrF3 Entrance" --> "PrF3 Start"
class "Lich Start"
"AmF4 Start" <--> "Lich Start"
"Lich Start" --> "Lich Arena"
class "AvF7 SW"
"AvF7 SW" --> "AvF7 SW Silver Gate"
"AvF7 SW" --> "AvF7 SW Gold Gate"
"AvF7 SW" <--> "AvF7 SW"
class "AvF8 Spike Trap Treasure Island"
"AvF8 Spike Trap Treasure Island" --> "AvF8 SW Light Bridge"
class "AvF8 West Island"
class "PrB Room 1"
"PrB Room 1" --> "PrB Room 2"
class "AmF4 East"
"AmF4 SE" <--> "AmF4 East"
"AmF4 East" --> "AmF4 East SW Vault"
"AmF4 East" --> "AmF4 East Bronze Gate Enemy Room"
"AmF4 East" --> "AmF4 East SE Vault"
"AmF4 East" --> "AmF4 East East Vault"
"AmF4 East" --> "AmF4 East NE Vault"
"AmF4 East" --> "AmF4 North Vault"
"AmF4 East" --> "AmF4 Red Spikes"
"AmF4 East" --> "AmF4 North Teleport"
class "PrF3 Start"
"PrF3 Start" --> "PrF3 NW In Wall"
"PrF3 Start" --> "PrF3 NW Area North Bronze Gate"
"PrF3 Start" --> "PrF3 NW Area South Bronze Gate"
class "Lich Arena"
"Lich Arena" --> "Lich Defeated"
class "AvF7 SW Silver Gate"
"AvF7 SW Silver Gate" --> "AvF7 Start In Wall"
class "AvF7 SW Gold Gate"
"AvF7 SW Gold Gate" --> "AvF7 Exit Left"
class "AvF8 SW Light Bridge"
"AvF8 SW Light Bridge" --> "AvF8 Puzzle"
class "PrB Room 2"
"PrB Room 2" --> "PrB Room 2 Unlock"
"PrB Room 2" --> "PrB Room 3"
class "AmF4 East SW Vault"
class "AmF4 East Bronze Gate Enemy Room"
class "AmF4 East SE Vault"
"AmF4 East SE Vault" --> "AmF4 Rune Switches Room"
class "AmF4 East East Vault"
class "AmF4 East NE Vault"
class "AmF4 North Vault"
class "AmF4 Red Spikes"
class "AmF4 North Teleport"
class "AmF4 West"
"AmF4 East" <--> "AmF4 West"
"AmF4 West" --> "AmF4 West NE Vault"
"AmF4 West" --> "AmF4 West SE Vault"
"AmF4 West" --> "AmF4 West SW Vault"
"AmF4 West" --> "AmF4 West SW Lower Vault"
"AmF4 West" --> "AmF4 Puzzle"
"AmF4 West" --> "AmF4 SW Spikes"
class "PrF3 NW In Wall"
class "PrF3 NW Area North Bronze Gate"
class "PrF3 NW Area South Bronze Gate"
class "PrF3 Silver Gate"
"PrF3 Start" <--> "PrF3 Silver Gate"
class "PrF3 North Gold Gate"
"PrF3 Start" <--> "PrF3 North Gold Gate"
"PrF3 North Gold Gate" --> "PrF3 Red Spikes Room"
"PrF3 North Gold Gate" --> "PrF3 Bonus Room"
"PrF3 North Gold Gate" --> "PrF3 South Bronze Gate"
"PrF3 North Gold Gate" --> "PrF3 South Spikes"
"PrF3 North Gold Gate" --> "PrF3 SW"
"PrF3 North Gold Gate" --> "PrF3 Arrow Hall Secret"
class "Lich Defeated"
"Lich Defeated" --> "Lich Exit"
class "AvF7 Start In Wall"
class "AvF7 Exit Left"
"AvF7 Exit Left" --> "AvF7 Exit Right"
class "AvF8 Puzzle"
class "PrB Room 2 Unlock"
class "PrB Room 3"
"PrB Room 3" --> "PrB Room 3 Unlock"
"PrB Room 3" --> "PrB Room 2 Open Hall"
class "AmF4 Rune Switches Room"
"AmF4 Rune Switches Room" --> "AmF4 SE Cache"
class "AmF4 NW Vault"
"AmF4 West" <--> "AmF4 NW Vault"
class "AmF4 West NE Vault"
class "AmF4 West SE Vault"
class "AmF4 West SW Vault"
class "AmF4 West SW Lower Vault"
class "AmF4 Puzzle"
class "AmF4 SW Spikes"
class "PrF2 Return from Floor 1"
"PrF3 Silver Gate" <--> "PrF2 Return from Floor 1"
class "PrF3 Red Spikes Room"
"PrF3 Red Spikes Room" --> "PrF3 Red Spikes Tower Room"
class "PrF3 Bonus Room"
class "PrF3 South Bronze Gate"
class "PrF3 South Spikes"
class "PrF3 SW"
"PrF3 SW" --> "PrF3 South Exit"
"PrF3 SW" --> "PrF3 Hidden Arrow Hall"
"PrF3 SW" --> "PrF3 South Gold Gate"
class "PrF3 Arrow Hall Secret"
class "Dragon Start"
"AvF7 Exit Left" <--> "Dragon Start"
"Dragon Start" --> "Dragon Defeated"
class "AvF7 Exit Right"
class "PrB Room 3 Unlock"
class "PrB Room 2 Open Hall"
"PrB Room 2 Open Hall" --> "PrB Room 4"
class "AmF4 SE Cache"
class "PrF3 Red Spikes Tower Room"
class "PrF1 From Floor 2"
"PrF3 Bonus Room" <--> "PrF1 From Floor 2"
class "PrF3 South Exit"
"PrF3 South Exit" --> "PrF3 North Gold Gate"
class "PrF3 Hidden Arrow Hall"
class "PrF3 South Gold Gate"
class "PrF1 From Floor 3 South"
"PrF3 SW" <--> "PrF1 From Floor 3 South"
class "Dragon Defeated"
"Dragon Defeated" --> "Chambers Escape"
class "AmF6 Main"
"AvF7 Exit Right" <--> "AmF6 Main"
"AmF6 Main" --> "AmF6 Knife Puzzle Reward"
"AmF6 Main" --> "AmF6 Knife Puzzle Reward 2"
"AmF6 Main" --> "AmF6 Teleport"
"AmF6 Main" --> "AmF6 Pyramids North Bronze Gate"
"AmF6 Main" --> "AmF6 Pyramids East Bronze Gate"
"AmF6 Main" --> "AmF6 North Left Bronze Gate"
"AmF6 Main" --> "AmF6 North Right Bronze Gate"
"AmF6 Main" --> "AmF6 SE Left Bronze Gate"
"AmF6 Main" --> "AmF6 SE Right Bronze Gate"
class "PrB Room 4"
"PrB Room 4" --> "AmF5 Bonus Return"
class "PrF1 Chambers Return Start"
"PrF1 From Floor 2" <--> "PrF1 Chambers Return Start"
"PrF1 Chambers Return Start" --> "PrF1 Chambers Return Puzzle"
class "AmF5 NW"
"AmF5 NW" --> "AmF5 Blue Spikes"
"AmF5 NW" --> "AmF5 Stairs to Floor 6"
"PrF3 South Exit" <--> "AmF5 NW"
class "Chambers Escape"
"Chambers Escape" --> "Archives Escape"
class "AmF6 Start"
"AmF6 Main" <--> "AmF6 Start"
class "AmF6 Knife Puzzle Reward"
class "AmF6 Knife Puzzle Reward 2"
class "PrF2 Middle"
"AmF6 Main" <--> "PrF2 Middle"
class "AmF6 Teleport"
class "AmF6 Pyramids North Bronze Gate"
class "AmF6 Pyramids East Bronze Gate"
class "AmF6 North Left Bronze Gate"
class "AmF6 North Right Bronze Gate"
class "AmF6 SE Left Bronze Gate"
class "AmF6 SE Right Bronze Gate"
class "AmF5 Bonus Return"
class "PrF1 Chambers Return Puzzle"
class "AmF4 From Floor 5"
"AmF5 NW" <--> "AmF4 From Floor 5"
class "AmB Start"
"AmF5 NW" <--> "AmB Start"
"AmB Start" --> "AmB Center Area"
class "AmF5 Blue Spikes"
"AmF5 Blue Spikes" --> "AmF5 Blue Spikes Teleport"
class "AmF5 Stairs to Floor 6"
class "Archives Escape"
"Archives Escape" --> "Armory Escape"
class "PrF2 Start"
"PrF2 Middle" <--> "PrF2 Start"
class "PrF2 North"
"PrF2 Middle" <--> "PrF2 North"
"PrF2 North" --> "PrF2 Spike Puzzle Bottom"
"PrF2 North" --> "PrF2 Spike Puzzle Top"
"PrF2 North" --> "PrF2 Spike Puzzle Left"
"PrF2 North" --> "PrF2 Red Spike Switch"
class "PrF2 South"
"PrF2 Middle" <--> "PrF2 South"
"PrF2 South" --> "PrF2 East Bronze Gate Past Gold Gate"
"PrF2 South" --> "PrF2 Middle Bronze Gate"
"PrF2 South" --> "PrF2 SE Bronze Gate"
"PrF2 South" --> "PrF2 Gold Gate Room Reward"
"PrF2 South" --> "PrF2 West Treasure Room"
"PrF2 South" --> "PrF2 Item Puzzle"
class "AmB Center Area"
"AmB Center Area" --> "AmB NW Room"
"AmB Center Area" --> "AmB North Room"
"AmB Center Area" --> "AmB East Room"
"AmB Center Area" --> "AmB South Room"
"AmB Center Area" --> "AmB West Room"
"AmB Center Area" --> "AmB SE Room"
"AmB Center Area" --> "AmB NE Room"
class "AmF5 Blue Spikes Teleport"
class "PrF1 From Floor 3 North"
"AmF5 Stairs to Floor 6" <--> "PrF1 From Floor 3 North"
class "Armory Escape"
"Armory Escape" --> "Prison Escape"
class "Queen Start"
"PrF2 Start" <--> "Queen Start"
"Queen Start" --> "Queen Arena"
class "PrF2 Spike Puzzle Bottom"
class "PrF2 Spike Puzzle Top"
class "PrF2 Spike Puzzle Left"
class "PrF2 Red Spike Switch"
"PrF2 Red Spike Switch" --> "PrF2 Puzzle"
"PrF2 Red Spike Switch" --> "PrF2 East Bronze Gate"
"PrF2 Red Spike Switch" --> "PrF2 East Save Room"
class "PrF2 East Bronze Gate Past Gold Gate"
class "PrF2 Middle Bronze Gate"
class "PrF2 SE Bronze Gate"
class "PrF2 Gold Gate Room Reward"
class "PrF2 West Treasure Room"
"PrF2 West Treasure Room" --> "PrF2 West Treasure Room Teleport Item"
class "PrF2 Item Puzzle"
class "PrF2 End"
"PrF2 South" <--> "PrF2 End"
class "AmB NW Room"
class "AmB North Room"
class "AmB East Room"
class "AmB South Room"
class "AmB West Room"
class "AmB SE Room"
class "AmB NE Room"
"AmB NE Room" --> "AmB Exit"
class "Prison Escape"
"Prison Escape" --> "Escaped Castle Hammerwatch"
class "Queen Arena"
"Queen Arena" --> "Queen Defeated"
class "PrF2 Puzzle"
class "PrF2 East Bronze Gate"
class "PrF2 East Save Room"
class "PrF2 West Treasure Room Teleport Item"
class "AmF5 Start"
"PrF2 End" <--> "AmF5 Start"
"AmF5 Start" --> "AmF5 South Teleport"
"AmF5 Start" --> "AmF5 SE Teleport"
"AmF5 Start" --> "AmF5 Puzzle"
"AmF5 Start" --> "AmF5 SW Bronze Gate"
"AmF5 Start" --> "AmF5 South Left Bronze Gate"
"AmF5 Start" --> "AmF5 South Right Bronze Gate"
"AmF5 Start" --> "AmF5 South Save Bronze Gate"
class "AmB Exit"
"AmB Exit" --> "PrF3 Complete Bonus"
class "Escaped Castle Hammerwatch"
class "Queen Defeated"
"Queen Defeated" --> "Queen Exit"
class "AmF5 South Teleport"
class "AmF5 SE Teleport"
class "AmF5 Puzzle"
class "AmF5 SW Bronze Gate"
class "AmF5 South Left Bronze Gate"
class "AmF5 South Right Bronze Gate"
class "AmF5 South Save Bronze Gate"
class "AmF5 NE"
"AmF5 Start" <--> "AmF5 NE"
"AmF5 NE" --> "AmF5 NE Miniboss Bronze Gate"
"AmF5 NE" --> "AmF5 NE Rune Puzzle Left Bronze Gate"
"AmF5 NE" --> "AmF5 NE Rune Puzzle Right Bronze Gate"
"AmF5 NE" --> "AmF5 NE Across from Save Bronze Gate"
"AmF5 NE" --> "AmF5 NE Save Bronze Gate"
"AmF5 NE" --> "AmF5 NE Teleport"
"AmF5 NE" --> "AmF5 East"
class "PrF3 Complete Bonus"
"PrF3 Complete Bonus" --> "PrF3 Bonus Room"
class "Queen Exit"
class "AmF5 NE Miniboss Bronze Gate"
class "AmF5 NE Rune Puzzle Left Bronze Gate"
class "AmF5 NE Rune Puzzle Right Bronze Gate"
class "AmF5 NE Across from Save Bronze Gate"
class "AmF5 NE Save Bronze Gate"
class "AmF5 NE Teleport"
class "AmF5 East"
"AmF5 East" --> "AmF5 East Bronze Gate"
class "AmF6 from Floor 5"
"Queen Exit" <--> "AmF6 from Floor 5"
"AmF6 from Floor 5" --> "AmF6 Pyramids South Bronze Gate"
class "AmF5 East Bronze Gate"
class "AmF6 Pyramids South Bronze Gate"
package "other regions" <<Cloud>> {
class "Menu"
class "Collect All Planks"
}
@enduml