# Mainly dictionaries converting in-game things to/from AP
from .names import item_name, location_name, region_name, entrance_name
from .items import item_table
from .locations import all_locations
from typing import Optional

BLOODSTONE_VALUE_MULTIPLIER = 5
PODIUM_ANIM_TIME = 12.76

PICKUP_UPGRADE_COG = "pickup_upgrade_cog"
PLACEHOLDER_ORE = "placeholder_ore"
PLACEHOLDER_GEM = "placeholder_gem"
ORB_SUPER_CONTAINER = "orb_super_container"

RANDOMIZED_ITEM_ENTITIES = {
    PICKUP_UPGRADE_COG,
    PLACEHOLDER_ORE,
    PLACEHOLDER_GEM,
    ORB_SUPER_CONTAINER,
}

AP_OFFWORLD_ITEM = "ap_item_offworld"
COGBOX_EMPTY = "cogbox_empty"
COGBOX_SUPER_ORBS = "cogbox_super_orbs"

AP_CONTAINER_EFFECT = "ap_container"
UPGRADE_EFFECT = "upgrade"


class GameData:
    ap_item_id: Optional[int]
    ap_loc_id: int
    
    def __init__(self, ap_item: Optional[str], ap_loc: Optional[str]):
        self.ap_item_id = item_table[ap_item].code if ap_item is not None else None
        self.ap_loc_id = all_locations[ap_loc].code if ap_loc is not None else None


in_game_item_data: dict[str, GameData] = {
    "pickaxe": GameData(item_name.pickaxe, None),
    "backpack": GameData(item_name.backpack, None),
    "lamp": GameData(item_name.lamp, None),
    "armor": GameData(item_name.armor, None),
    "watertank": GameData(item_name.tank, None),
    "pressurebomb": GameData(item_name.bomb, location_name.c_bs_podium),
    "jackhammer": GameData(item_name.jackhammer, location_name.c_ms_podium),
    "steampack": GameData(item_name.jetengine, location_name.c_mc_podium),
    "hook": GameData(item_name.hookshot, location_name.c_rs_podium),
    "hook.long_hook": GameData(item_name.up_hookshot_range, location_name.c_rtc_podium),
    "run_boots": GameData(item_name.sprint, location_name.gt_tut_podium),
    "pickaxe.fire": GameData(item_name.up_pickaxe_ignition, location_name.c_cs_podium),
    "pressurebomb.launcher": GameData(item_name.up_bomb_grenades, location_name.c_cos_podium),
    "pressurebomb.launcher_triple": GameData(item_name.up_bomb_more_grenades, location_name.em_heisenberg),
    "steampack.slayer": GameData(item_name.up_ramjet, location_name.c_as_podium),
    "armor.damage_reduction": GameData(item_name.up_armor_defense, location_name.c_sa_podium),
    "fate.bloodquest": GameData(item_name.up_fate_blood_quest, location_name.a_josh_yonker),
    "fate.xpx2": GameData(item_name.up_fate_thrillseekers_tale, location_name.y_up_luke_yonker),
    "fate.explosions": GameData(item_name.up_fate_deathplosions, location_name.wd_zebulon_yonker),
    "pickaxe.bonus_xp": GameData(item_name.up_pickaxe_xp, None),
    "pickaxe.resource_damage_01": GameData(item_name.up_pickaxe_resource_dmg, None),
    "pickaxe.bounty": GameData(item_name.up_pickaxe_gold_kills, None),
    "pickaxe.knockback_01": GameData(item_name.up_pickaxe_recoil, None),
    "pickaxe.health_pickup": GameData(item_name.up_pickaxe_heal_orb, None),
    "pickaxe.deflect_projectiles": GameData(item_name.up_pickaxe_projectile_reflect, None),
    "pickaxe.speed_01": GameData(item_name.up_pickaxe_swing_speed, None),
    "pickaxe.enemy_damage_01": GameData(item_name.up_pickaxe_damage, location_name.em_artifact_21),
    "backpack.lower_death_penalty_01": GameData(item_name.up_bag_resource_loss, None),
    "backpack.discard_give_money": GameData(item_name.up_bag_discard_gold, None),
    "backpack.extra_gem": GameData(item_name.up_bag_storage_gem, None),
    "backpack.town_portal": GameData(item_name.up_bag_portal, None),
    "backpack.double_resources": GameData(item_name.up_bag_resource_dupe, None),
    "backpack.magnetic_pull": GameData(item_name.up_bag_magnet, None),
    "backpack.pickup_money": GameData(item_name.up_bag_cheap_res_gold, None),
    "backpack.discard_give_health": GameData(item_name.up_bag_discard_heal, None),
    "backpack.extra_value": GameData(item_name.up_bag_sell_gold, None),
    "backpack.extra_ore": GameData(item_name.up_bag_storage_ore, location_name.em_artifact_10),
    "lamp.increased_area": GameData(item_name.up_lamp_radius, None),
    "lamp.lit_pickups": GameData(item_name.up_lamp_pickup_light, None),
    "lamp.lightning_reflexes": GameData(item_name.up_lamp_hazard_dodge, None),
    "lamp.light_pickup": GameData(item_name.up_lamp_enemy_light, None),
    "lamp.infinite_light": GameData(item_name.up_lamp_light_min, None),
    "lamp.eye_for_weakness": GameData(item_name.up_lamp_secret_sight, None),
    "armor.reduce_falldamage_01": GameData(item_name.up_armor_fall_damage, None),
    "armor.thorns": GameData(item_name.up_armor_thorns, None),
    "armor.resistliquids": GameData(item_name.up_armor_liquid_res, None),
    "armor.deflect": GameData(item_name.up_armor_reflect, None),
    "armor.guts": GameData(item_name.up_armor_second_life, None),
    "armor.rainbow_orbs": GameData(item_name.up_armor_orbs, location_name.em_artifact_6),
    "watertank.improved_water_pump": GameData(item_name.up_tank_fill_speed, None),
    "watertank.light_orbs_to_water": GameData(item_name.up_tank_water_orb_convert, None),
    "watertank.water_condenser": GameData(item_name.up_tank_water_regen, None),
    "watertank.health_regen": GameData(item_name.up_tank_water_healing, location_name.em_artifact_28),
    "pressurebomb.self_immunity": GameData(item_name.up_bomb_no_friendly_fire, None),
    "pressurebomb.water_pickup": GameData(item_name.up_bomb_extra_bomb, None),
    "pressurebomb.brickbreaker": GameData(item_name.up_bomb_strength, None),
    "pressurebomb.air_bomb": GameData(item_name.up_bomb_air_firing, None),
    "jackhammer.faster_windup": GameData(item_name.up_hammer_windup, None),
    "jackhammer.slower_winddown": GameData(item_name.up_hammer_winddown, None),
    "jackhammer.push": GameData(item_name.up_hammer_forward_pull, None),
    "jackhammer.faster_maxspeed": GameData(item_name.up_hammer_speed, None),
    "steampack.feather_fall": GameData(item_name.up_jetpack_coast, None),
    "steampack.boost": GameData(item_name.up_jetpack_speed, None),
    "steampack.in_air_cooling": GameData(item_name.up_jetpack_air_cooling, None),
    "minimap.quest_pointer": GameData(item_name.up_map_markers, None),
    "minimap.mineral_detector": GameData(item_name.up_map_resources, location_name.em_artifact_15),
    "minimap.hp_bar": GameData(item_name.up_map_health, location_name.em_artifact_1),
    "fate.resource_exploder": GameData(item_name.up_fate_dmg_aoe, location_name.em_artifact_3),
    "lamp.damaging_light": GameData(item_name.up_lamp_damage, None),
    "watertank.water_pickup": GameData(item_name.up_tank_water_pickup, None),
    "pressurebomb.increased_radius": GameData(item_name.up_bomb_radius, None),
    "pressurebomb.improved_water": GameData(item_name.up_bomb_water_usage, None),
    "jackhammer.shockwave": GameData(item_name.up_hammer_shockwave, None),
    "jackhammer.improved_water": GameData(item_name.up_hammer_water_usage, None),
    "collectible_42": GameData(item_name.a_building_plans, location_name.gt_tut_podium_secret),
    "collectible_13": GameData(item_name.a_straw_doll, location_name.gt_tut_boss_totem),
    "collectible_11": GameData(item_name.a_book_groda, location_name.wd_bottom),
    "collectible_24": GameData(item_name.a_banana_peels, location_name.c_tt_breakable_wall),
    "collectible_07": GameData(item_name.a_action_figure, location_name.wp_cliff),
    "collectible_10": GameData(item_name.a_inflatable_friend, location_name.wp_hill_right),
    "collectible_31": GameData(item_name.a_black_box, location_name.c_rf_top_right),
    "collectible_02": GameData(item_name.a_amulet, location_name.c_pwg_secret),
    "collectible_01": GameData(item_name.a_dead_rat, location_name.c_bs_secret_r),
    "collectible_35": GameData(item_name.a_diary, location_name.c_cic_top_secret),
    "collectible_03": GameData(item_name.a_wrapped_gift, location_name.a_cp_from_wp),
    "collectible_29": GameData(item_name.a_fifty, location_name.y_up_lake_t),
    "collectible_15": GameData(item_name.a_lost_penguin, location_name.c_ms_top),
    "collectible_14": GameData(item_name.a_glowing_goo, location_name.c_rrh_top),
    "collectible_41": GameData(item_name.a_six_pack, location_name.o_top),
    "collectible_39": GameData(item_name.a_dumbells, location_name.c_rs_secret_r),
    "collectible_20": GameData(item_name.a_monster_plushy, location_name.a_b_r),
    "collectible_28": GameData(item_name.a_stone_tablet, location_name.c_dc_bottom),
    "collectible_21": GameData(item_name.a_shark_tooth, location_name.c_tbc_top_l),
    "collectible_25": GameData(item_name.a_theremin, location_name.totd_cm_end_b),
    "collectible_32": GameData(item_name.a_red_cloth, location_name.c_fil_perfect),
    "collectible_26": GameData(item_name.a_weird_stone, location_name.totd_ga),
    "collectible_27": GameData(item_name.a_fossil, location_name.c_ls_end_secret),
    "collectible_33": GameData(item_name.a_cult_list, location_name.c_gh_secret_left),
    "collectible_18": GameData(item_name.a_chainsaw, location_name.c_sac_secret_t),
    "collectible_08": GameData(item_name.a_holy_toast, location_name.c_ic_secret_r),
    "collectible_23": GameData(item_name.a_cake, location_name.totd_river_b_b),
    "collectible_37": GameData(item_name.a_manual, location_name.totd_river_b_t),
    "collectible_22": GameData(item_name.a_rubber_chickens, location_name.c_mm_reward_3),
    "collectible_38": GameData(item_name.a_pills, location_name.tog_cistern_r),
    "collectible_16": GameData(item_name.a_old_invitations, location_name.c_cos_wall_l),
    "collectible_19": GameData(item_name.a_toy_rocket, location_name.c_coa_secret),
    "collectible_30": GameData(item_name.a_wagon_wheel, location_name.c_cow_secret),
    "collectible_17": GameData(item_name.a_sacred_documentation, location_name.y_lower_below_acid_l),
    "collectible_12": GameData(item_name.a_birdie_seeds, location_name.y_lower_mm_l),
    "collectible_34": GameData(item_name.a_amiigo, location_name.c_sss_secret_r),
    "collectible_36": GameData(item_name.a_orchid, location_name.c_ll_secret_b),
    "collectible_05": GameData(item_name.a_scented_candle, location_name.c_hph_secret),
    "collectible_06": GameData(item_name.a_cereal, location_name.c_mms_secret),
    "collectible_40": GameData(item_name.a_painting, location_name.c_bb_secret),
    "collectible_09": GameData(item_name.a_lime_snowman, location_name.c_lime_loop_secret),
    "collectible_04": GameData(item_name.a_fertilizer, location_name.a_top_l_t),
    "collectible_43": GameData(item_name.a_completion_proof, location_name.c_hell_end),
    "fate.hell_cave_sigil": GameData(item_name.up_fate_sigil, location_name.em_artifact_42),
    PICKUP_UPGRADE_COG: GameData(item_name.cog, None),
    PLACEHOLDER_ORE: GameData(item_name.ore, None),
    PLACEHOLDER_GEM: GameData(item_name.gem, None),
    ORB_SUPER_CONTAINER: GameData(item_name.omni_orbs, None),
    "pickup_resource_vectron": GameData(item_name.vectron_ore_1, None),
    "pickup_resource_vectron_02": GameData(item_name.vectron_ore_2, None),
    "pickup_resource_vectron_03": GameData(item_name.vectron_ore_3, None),
    "pickup_resource_vectron_04": GameData(item_name.vectron_ore_4, None),
    "pickup_resource_vectron_05": GameData(item_name.vectron_ore_5, None),
}
shop_item_data: dict[str, list[Optional[GameData]]] = {
    "pickaxe": [
        None,
        GameData(None, location_name.em_pickaxe_2),
        GameData(None, location_name.em_pickaxe_3),
        GameData(None, location_name.em_pickaxe_4),
        GameData(None, location_name.em_pickaxe_5),
        GameData(None, location_name.em_pickaxe_6),
        GameData(None, location_name.em_pickaxe_7),
        GameData(None, location_name.em_pickaxe_8),
    ],
    "backpack": [
        None,
        GameData(None, location_name.em_backpack_2),
        GameData(None, location_name.em_backpack_3),
        GameData(None, location_name.em_backpack_4),
        GameData(None, location_name.em_backpack_5),
        GameData(None, location_name.em_backpack_6),
        GameData(None, location_name.em_backpack_7),
        GameData(None, location_name.em_backpack_8),
        GameData(None, location_name.em_backpack_9),
        GameData(None, location_name.em_backpack_10),
    ],
    "lamp": [
        None,
        None,
        GameData(None, location_name.em_lamp_2),
        GameData(None, location_name.em_lamp_3),
        GameData(None, location_name.em_lamp_4),
        GameData(None, location_name.em_lamp_5),
        GameData(None, location_name.em_lamp_6),
        GameData(None, location_name.em_lamp_7),
    ],
    "armor": [
        None,
        GameData(None, location_name.em_armor_2),
        GameData(None, location_name.em_armor_3),
        GameData(None, location_name.em_armor_4),
        GameData(None, location_name.em_armor_5),
        GameData(None, location_name.em_armor_6),
        GameData(None, location_name.em_armor_7),
        GameData(None, location_name.em_armor_8),
    ],
    "watertank": [
        GameData(None, location_name.em_tank_1),
        GameData(None, location_name.em_tank_2),
        GameData(None, location_name.em_tank_3),
        GameData(None, location_name.em_tank_4),
        GameData(None, location_name.em_tank_5),
    ],
    "pressurebomb": [
        GameData(None, location_name.em_bomb_1),
        GameData(None, location_name.em_bomb_2),
        GameData(None, location_name.em_bomb_3),
        GameData(None, location_name.em_bomb_4),
    ],
    "jackhammer": [
        GameData(None, location_name.em_hammer_1),
        GameData(None, location_name.em_hammer_2),
        GameData(None, location_name.em_hammer_3),
        GameData(None, location_name.em_hammer_4),
    ],
    "steampack": [
        GameData(None, location_name.em_jetpack_1),
        GameData(None, location_name.em_jetpack_2),
        GameData(None, location_name.em_jetpack_3),
    ],
}

ap_item_to_in_game_name: dict[int, str] = {data.ap_item_id: itm for itm, data in in_game_item_data.items()}

# Unused rn
level_to_region: dict[str, str] = {
    "west_desert": region_name.west_desert_start,  #
    "west_desert_cave_cart_puzzle": region_name.tenacious_trollies,
    "east_desert": region_name.windy_plains,
    "east_desert_cave_runfallblock": region_name.rock_falls,
    # "east_desert_cave_hell_temple_of_skillness": region_name.something,
    # "east_desert_cave_hell_skillness": region_name.something,
    # "east_desert_cave_hell_lava_flight": region_name.something,
    # "east_desert_cave_hell_buttons": region_name.something,
    # "east_desert_cave_hell_end": region_name.something,
    # "east_desert_cave_hell_crushers": region_name.something,
    # "east_desert_cave_hell_acoknights": region_name.something,
    # "east_desert_cave_hell_vectron": region_name.something,
    # "east_desert_cave_hell_rockets": region_name.something,
    # "east_desert_cave_hell_acoknights_entrance": region_name.something,
    # "east_desert_cave_hell_crushers_entrance": region_name.something,
    # "east_desert_cave_hell_lava_flight_entrance": region_name.something,
    # "east_desert_cave_hell_skillness_entrance": region_name.something,
    # "east_desert_cave_hell_buttons_entrance": region_name.something,
    # "east_desert_cave_hell_rockets_entrance": region_name.something,
    # "east_desert_cave_hell_vectron_entrance": region_name.something,
    "el_machino": region_name.machino,
    "archaea_1": region_name.archaea,  #
    "archaea_cave_unclimbable": region_name.patch_wall_grotto,
    "archaea_cave_jackhammer": region_name.masons_station,
    "archaea_cave_pressurebomb": region_name.bursters_station,
    "archaea_cave_fallblock_puzzle": region_name.tick_boom_room,
    "archaea_cave_snakestone": region_name.rupture_rock_hollow,
    "archaea_cave_snakestone_blocks": region_name.cave_in_catacomb,
    "archaea_cave_trilobite_puzzle": region_name.trilobyte_bluff,
    "archaea_cave_vectron_entrance": region_name.mysterious_cave,
    "archaea_cave_cactus": region_name.prickly_panorama,
    "fire_temple": region_name.temple_destroyer,  #
    "firetemple_cave_lavachase": region_name.demons_crib,
    "firetemple_cave_golem": region_name.grim_hollow,
    "firetemple_cave_crusher": region_name.roasted_romp,
    "firetemple_cave_floor_is_lava": region_name.floor_is_lava,
    "firetemple_cave_boxes": region_name.infernal_crates,
    "firetemple_cave_lava_shooters": region_name.lava_shooters,
    "firetemple_cave_flamer": region_name.combusters_station,
    "firetemple_cave_armor": region_name.the_sun_armory,
    "firetemple_cave_firebat": region_name.the_batcave,
    "firetemple_cave_spikeconveyor": region_name.spikes_conveyors,
    "firetemple_cave_generator": region_name.device_of_doom,
    "firetemple_cave_generator2": region_name.device_of_destruction,
    "firetemple_cave_treasure_chamber": region_name.ronalds_treasure_chamber,
    "firetemple_cave_hell_carts": region_name.mine_cart_madness,
    "temple_of_guidance": region_name.temple_guidance,  #
    "temple_of_guidance_2_cave_arrowtraps": region_name.chamber_of_arrows,
    "temple_of_guidance_2_cave_maze": region_name.chamber_of_secrets,
    "temple_of_guidance_2_cave_generator": region_name.device_of_devastation,
    "temple_of_guidance_2_cave_pushthecarts": region_name.chamber_of_wheels,
    "yarrow": region_name.yarrow,  #
    "yarrow_cave_generator": region_name.device_of_disaster,
    "yarrow_cave_gauntlet": region_name.leaky_lodge,
    "yarrow_cave_bats": region_name.bushwack_beehive,
    "yarrow_cave_run": region_name.lime_loop,
    "yarrow_cave_steampack_slayer": region_name.aeronauts_station,
    "yarrow_cave_water": region_name.swim_swam_sway,
    "yarrow_cave_cliffhanger": region_name.hodge_podge_hang,
    "yarrow_cave_mushimushiroom": region_name.mushi_mushi_snuggery,
    "the_hub": region_name.oasis,
    "the_hub_cave_grapplinghook": region_name.rosies_storage,
    "the_hub_cave_hubtube": region_name.sludge_river_bend,
    "the_hub_cave_boss": region_name.the_reactor,
    # "the_hub_cave_boss_saving_rusty": region_name.something,
    "vectron_1": region_name.vectron,

    # "archaea_cave_sinkstone_stickybomb": region_name.something,
    # "archaea_cave_runfallblock": region_name.something,
    # "firetemple_cave_conveyor": region_name.the_batcave,
    # "firetemple_cave_platform": region_name.something,
    # "archaea_cave_run": region_name.something,
    # "small_challenge_stickaround": region_name.something,
    # "temple_of_skillness": region_name.something,
}

# (cave door, return door)
cave_doors = {
    region_name.tenacious_trollies: (entrance_name.door_cavecartpuzzle_wdes, entrance_name.door_wdes_cavecartpuzzle),
    region_name.rock_falls: (entrance_name.door_caverunfallblock_edes, entrance_name.door_edes_caverunfallblock),
    region_name.patch_wall_grotto: (entrance_name.door_caveunclimbable_arch, entrance_name.door_arch_caveunclimbable),
    region_name.bursters_station: (entrance_name.door_cavepressurebomb_arch2, entrance_name.door_arch2_cavepressurebomb),
    region_name.cave_in_catacomb: (entrance_name.door_cavesnakestoneblocks_arch1, entrance_name.door_arch1_cavesnakestoneblocks),
    region_name.tick_boom_room: (entrance_name.door_cavefallblockpuzzle_arch1, entrance_name.door_arch1_cavefallblockpuzzle),
    region_name.prickly_panorama: (entrance_name.door_cavecactus_arch1, entrance_name.door_arch1_cavecactus),
    region_name.trilobyte_bluff: (entrance_name.door_cavetrilobitepuzzle_arch1, entrance_name.door_arch1_cavetrilobitepuzzle),
    region_name.masons_station: (entrance_name.door_cavejackhammer_arch2, entrance_name.door_arch2_cavejackhammer),
    region_name.rupture_rock_hollow: (entrance_name.door_cavesnakestone_arch1, entrance_name.door_arch1_cavesnakestone),
    region_name.rosies_storage: (entrance_name.door_cavegrapplinghook_thehub, entrance_name.door_thehub_cavegrapplinghook),
    region_name.mysterious_cave: (entrance_name.door_arch_vectron1, entrance_name.door_archaea_vectron1),
    # region_name.demons_crib: (entrance_name.door_cavelavachase_fire, entrance_name.door_fire_cavelavachase),
    # region_name.temple_destroyer_upper: (entrance_name.door_fire_cavelavachase_2, None),
    region_name.the_batcave: (entrance_name.door_cavefirebat_fire1, entrance_name.door_fire1_cavefirebat),
    region_name.floor_is_lava: (entrance_name.door_floor_is_lava_ftemp, entrance_name.door_ftemp_floor_is_lava),
    region_name.lava_shooters: (entrance_name.door_cavelavashooters_ftemp, entrance_name.door_ftemp_cavelavashooters),
    region_name.roasted_romp: (entrance_name.door_cavecrusher_ftemp, entrance_name.door_ftemp_cavecrusher),
    region_name.grim_hollow: (entrance_name.door_cavegolem_ftemp, entrance_name.door_ftemp_cavegolem),
    region_name.spikes_conveyors: (entrance_name.door_cavespikeconveyor_fire, entrance_name.door_fire_cavespikeconveyor),
    region_name.combusters_station: (entrance_name.door_caveflamer_fire1, entrance_name.door_fire1_caveflamer),
    region_name.device_of_doom: (entrance_name.door_cavegenerator1_fire1, entrance_name.door_fire1_cavegenerator1),
    region_name.ronalds_treasure_chamber: (entrance_name.door_cavetreasurechamber_fire1, entrance_name.door_fire1_cavetreasurechamber),
    region_name.infernal_crates: (entrance_name.door_caveboxes_ftemp, entrance_name.door_ftemp_caveboxes),
    region_name.mine_cart_madness: (entrance_name.door_cavehellcarts_fire2, entrance_name.door_fire2_cavehellcarts),
    region_name.the_sun_armory: (entrance_name.door_cavearmor_fire2, entrance_name.door_fire2_cavearmor),
    region_name.device_of_destruction: (entrance_name.door_cavegenerator2_fire2, entrance_name.door_fire2_cavegenerator2),
    region_name.chamber_of_secrets: (entrance_name.door_cavemaze_guidance, entrance_name.door_guidance_cavemaze),
    # region_name.chamber_of_arrows: (entrance_name.door_cavearrowtraps_guidance, entrance_name.door_guidance_cavearrowtraps),
    # region_name.temple_guidance_cistern_l: (entrance_name.door_guidance2button_cavearrowtraps, entrance_name.door_cavearrowtraps_guidance2button),
    # region_name.chamber_of_wheels: (entrance_name.door_cavepushthecarts_guidance, entrance_name.door_guidance_cavepushthecarts),
    # region_name.temple_guidance_cistern_r: (entrance_name.door_guidance2button_cavepushthecarts, entrance_name.door_cavepushthecarts_guidance2button),
    region_name.device_of_devastation: (entrance_name.door_cavegenerator_guidance, entrance_name.door_guidance_cavegenerator),
    region_name.swim_swam_sway: (entrance_name.door_cavewater_yarr, entrance_name.door_yarr_cavewater),
    # region_name.sludge_river_bend: (entrance_name.entrance, entrance_name.entrance),
    # region_name.oasis: (entrance_name.entrance, entrance_name.entrance),
    # region_name.leaky_lodge: (entrance_name.door_cavegauntlet_yarr_a, entrance_name.door_yarr_cavegauntlet_a),
    # region_name.yarrow_below_acid_swamp: (entrance_name.door_yarr_cavegauntlet_b, entrance_name.door_cavegauntlet_yarr_b),
    region_name.hodge_podge_hang: (entrance_name.door_cavecliffhanger_yarr, entrance_name.door_yarr_cavecliffhanger),
    region_name.mushi_mushi_snuggery: (entrance_name.door_cavemushimushiroom_yarr, entrance_name.door_yarr_cavemushimushiroom),
    region_name.bushwack_beehive: (entrance_name.door_cavebats_yarr, entrance_name.door_yarr_cavebats),
    region_name.lime_loop: (entrance_name.door_caverun_yarr, entrance_name.door_yarr_caverun),
    # region_name.aeronauts_station: (entrance_name.door_cavesteampackslayer_yarr_a, entrance_name.door_yarr_cavesteampackslayer_a),
    # region_name.yarrow_bottom: (entrance_name.door_yarr_cavesteampackslayer_b, entrance_name.door_cavesteampackslayer_yarr_b),
    region_name.device_of_disaster: (entrance_name.door_cavegenerator_yarr2, entrance_name.door_yarr2_cavegenerator),
}

door_source_regions = {door_data[0]: region for region, door_data in cave_doors.items()}

COG_COSTS = {
    "pickaxe.speed_01": 3,
    "pickaxe.bounty": 3,
    # "pickaxe.fire": 0,
    "pickaxe.resource_damage_01": 2,
    "pickaxe.knockback_01": 1,
    "pickaxe.deflect_projectiles": 2,
    "pickaxe.enemy_damage_01": 4,
    "pickaxe.bonus_xp": 1,
    "pickaxe.health_pickup": 3,
    "backpack.magnetic_pull": 2,
    "backpack.extra_ore": 5,
    "backpack.extra_gem": 2,
    "backpack.discard_give_money": 1,
    "backpack.discard_give_health": 1,
    "backpack.pickup_money": 3,
    "backpack.lower_death_penalty_01": 2,
    "backpack.town_portal": 3,
    "backpack.double_resources": 4,
    "backpack.extra_value": 0,
    "lamp.increased_area": 1,
    "lamp.light_pickup": 2,
    "lamp.infinite_light": 3,
    "lamp.lit_pickups": 1,
    "lamp.lightning_reflexes": 2,
    "lamp.eye_for_weakness": 3,
    "armor.reduce_falldamage_01": 2,
    "armor.thorns": 1,
    "armor.guts": 5,
    "armor.resistliquids": 3,
    "armor.rainbow_orbs": 1,
    "armor.deflect": 3,
    "watertank.improved_water_pump": 1,
    "watertank.water_condenser": 5,
    "watertank.light_orbs_to_water": 1,
    "watertank.health_regen": 5,
    "pressurebomb.brickbreaker": 1,
    # "pressurebomb.launcher": 0,
    "pressurebomb.water_pickup": 3,
    "pressurebomb.self_immunity": 1,
    "pressurebomb.launcher_triple": 3,
    "pressurebomb.air_bomb": 3,
    "jackhammer.faster_windup": 2,
    "jackhammer.faster_maxspeed": 3,
    "jackhammer.slower_winddown": 1,
    "jackhammer.push": 2,
    # "steampack.slayer": 0,
    "steampack.feather_fall": 1,
    "steampack.boost": 2,
    "steampack.in_air_cooling": 4,
    # "hook.long_hook": 0,
    "minimap.mineral_detector": 4,
    "minimap.hp_bar": 1,
    "fate.bloodquest": 1,
    "fate.xpx2": 1,
    "fate.explosions": 1,
    "fate.resource_exploder": 1,
    # "fate.hell_cave_sigil": 0,
}

EXTRA_COG_COSTS = {
    "lamp.damaging_light": 4,
    "watertank.water_pickup": 3,
    "pressurebomb.increased_radius": 1,
    "pressurebomb.improved_water": 4,
    "jackhammer.shockwave": 2,
    "jackhammer.improved_water": 4,
}

# For the mod
ORE_AP_LOCS = {
    "archaea_cave_cactus": {
        (48, 8): 132568934,
    },
    "archaea_cave_jackhammer": {
        (-7, 12): 132587911,
        (-8, 13): 132587910,
        (-32, 8): 132579529,
        (-33, 8): 132579528,
        (-33, 7): 132579527,
        (-34, 10): 132579526,
        (-12, 12): 132579384,
    },
    "archaea_cave_pressurebomb": {
        (7, 14): 132566214,
    },
    "archaea_cave_snakestone": {
        (5, 12): 132575410,
        (5, 13): 132575409,
    },
    "archaea_patch_after_hub_area": {
        (13, 80): 132592324,
        (14, 79): 132592323,
        (13, 79): 132592322,
        (-9, 1): 132568460,
        (32, 22): 132568459,
        (31, 22): 132568458,
        (31, 21): 132568457,
        (28, 24): 132568309,
        (10, 4): 132568304,
        (-9, 2): 132568205,
        (-9, 4): 132568204,
        (3, 45): 132568181,
    },
    "archaea_patch_blocks": {
        (21, 11): 132568233,
        (28, 27): 132568232,
        (32, 38): 132568231,
        (24, 38): 132568230,
        (9, 20): 132568199,
    },
    "archaea_patch_cacti": {
        (33, 6): 132568206,
        (10, 16): 132568215,
        (4, 1): 132568224,
    },
    "archaea_patch_dirt": {
        (24, 13): 132576501,
        (24, 12): 132576500,
        (23, 12): 132576499,
        (23, 13): 132576498,
        (14, 6): 132576463,
        (2, -3): 132575881,
        (3, -4): 132575882,
        (1, -2): 132575883,
    },
    "archaea_patch_entrance": {
        (26, 11): 132568069,
        (13, 4): 132566747,
        (20, 4): 132566746,
    },
    "archaea_patch_entrance_west": {
        (14, 17): 132592337,
    },
    "archaea_patch_hub_entrance": {
        (19, -1): 132577354,
        (17, 13): 132577326,
    },
    "archaea_patch_pressurebomb_lock": {
        (-3, 2): 132566522,
    },
    "archaea_patch_stripes": {
        (21, -1): 132576018,
        (1, -4): 132576017,
    },
    "archaea_patch_vectron_entrance": {
        (35, 36): 132589849,
        (36, 38): 132589848,
        (36, 37): 132589847,
        (37, 36): 132589846,
    },
    "east_desert_cave_runfallblock": {
        (19, 9): 132569041,
    },
    "east_desert_patch_climb": {
        (14, -6): 132586747,
        (-7, -4): 132565457,
        (-6, -4): 132565456,
        (-6, -5): 132565455,
        (-7, -5): 132565454,
    },
    "firetemple2_patch_entrance": {
        (27, 15): 132584496,
        (127, 4): 132583163,
    },
    "firetemple2_patch_first_tunneldown": {
        (-4, 20): 132589134,
    },
    "firetemple2_patch_horizontaldig": {
        (-77, 4): 132586758,
        (-76, 4): 132586757,
        (-15, 5): 132586212,
        (2, 23): 132586213,
        (7, 22): 132586214,
        (5, 20): 132586215,
        (2, 13): 132586216,
        (-1, 12): 132586217,
        (-9, 12): 132586218,
        (-2, 3): 132586247,
        (-29, 20): 132586311,
    },
    "firetemple_cave_armor": {
        (18, 13): 132592388,
    },
    "firetemple_cave_boxes": {
        (41, 21): 132597480,
    },
    "firetemple_cave_crusher": {
        (-17, 16): 132608111,
        (-18, 16): 132608109,
        (-17, 15): 132608108,
    },
    "firetemple_cave_flamer": {
        (17, 17): 132579956,
    },
    "firetemple_cave_hell_carts": {
        (-20, 22): 132587483,
    },
    "firetemple_cave_lavachase": {
        (16, 43): 132568971,
    },
    "firetemple_cave_treasure_chamber": {
        (11, -2): 132592310,
    },
    "firetemple_patch_bottom_conveyors": {
        (15, 40): 132589245,
        (-2, 15): 132589231,
        (-1, 15): 132589230,
        (0, 35): 132589227,
        (1, 35): 132589218,
        (10, 16): 132583334,
    },
    "firetemple_patch_brazier_top": {
        (21, 28): 132588513,
        (20, 28): 132588512,
        (19, 27): 132588511,
        (20, 27): 132588510,
        (3, 20): 132588505,
    },
    "firetemple_patch_priest_intro": {
        (-12, 6): 132584635,
    },
    "temple_of_guidance": {
        (3, 8): 132572147,
        (8, 42): 132572061,
        (9, 39): 132572060,
        (12, 38): 132572059,
        (10, 34): 132572058,
        (5, 33): 132572057,
        (8, 36): 132572056,
    },
    "temple_of_guidance_2": {
        (-29, 45): 132582440,
        (-32, 43): 132582439,
        (-30, 39): 132582438,
        (27, 47): 132581983,
        (28, 47): 132581986,
        (29, 48): 132581997,
    },
    "temple_of_guidance_2_cave_arrowtraps": {
        (8, -8): 132582511,
    },
    "temple_of_guidance_2_cave_maze": {
        (47, 19): 132580606,
        (48, 8): 132580315,
    },
    "the_hub_cave_grapplinghook": {
        (-15, -29): 132591127,
        (-14, -29): 132591126,
        (-14, -28): 132591124,
        (-15, -28): 132591123,
    },
    "the_hub_cave_hubtube": {
        (-24, 0): 132587961,
        (-13, -6): 132587621,
        (-2, 1): 132587587,
        (9, -4): 132587559,
        (-4, 0): 132587557,
        (-4, -3): 132587556,
    },
    "west_desert_cave_cart_puzzle": {
        (13, 2): 132583914,
    },
    "west_desert_cliffs": {
        (59, 11): 132586797,
        (43, 20): 132586796,
        (42, 13): 132586795,
        (31, 7): 132586793,
        (22, 13): 132586792,
    },
    "west_desert_intro": {
        (-1, 7): 132592453,
    },
    "yarrow_2_patch_spitters": {
        (29, 28): 132592504,
        (25, 1): 132592499,
        (3, -4): 132592488,
        (18, 0): 132592480,
        (9, -1): 132592479,
        (27, 15): 132588049,
    },
    "yarrow_cave_bats": {
        (-34, 26): 132597308,
        (-35, 26): 132597309,
    },
    "yarrow_cave_cliffhanger": {
        (-31, 19): 132598544,
    },
    "yarrow_cave_gauntlet": {
        (74, -27): 132603657,
        (75, -27): 132603656,
        (36, -29): 132603507,
        (43, -25): 132603505,
        (74, -28): 132598771,
        (56, -38): 132598770,
        (36, -15): 132598724,
    },
    "yarrow_cave_mushimushiroom": {
        (-29, 36): 132598554,
    },
    "yarrow_cave_steampack_slayer": {
        (-16, 14): 132597414,
    },
    "yarrow_cave_water": {
        (-16, 69): 132596194,
        (-15, 68): 132596191,
        (9, 55): 132596186,
    },
    "yarrow_patch_sneakpeek": {
        (17, 2): 132589042,
        (-3, 24): 132588781,
        (-3, 6): 132588795,
        (17, 38): 132588880,
        (41, 0): 132588894,
    },
}