
wd_zebulon_yonker = "WD: Zebulon Yonker"
wd_start_cliff_ore = "WD: Start Cliff Ore"

gt_tut_dig_gearbox = "ToG: Tutorial Dig Left Wall"
gt_tut_podium = "ToG: Tutorial Upgrade Podium"
gt_tut_podium_secret = "ToG: Tutorial Upgrade Podium Secret"
gt_tut_above_hallway = "ToG: Tutorial Above Hallway To Boss Room"
gt_tut_boss_totem = "ToG: Tutorial Below Boss Totem"
gt_tut_orb_b = "ToG: Tutorial Lower Orb"
gt_tut_orb_m = "ToG: Tutorial Middle Orb"
gt_tut_orb_t = "ToG: Tutorial Fall Entrance Orb"
gt_tut_orb_boss_entr = "ToG: Tutorial Boss Entrance Orb"
gt_tut_orb_boss_1 = "ToG: Tutorial Boss Arena Orb #1"
gt_tut_orb_boss_2 = "ToG: Tutorial Boss Arena Orb #2"
gt_tut_orb_boss_3 = "ToG: Tutorial Boss Arena Orb #3"
gt_tut_orb_boss_4 = "ToG: Tutorial Boss Arena Orb #4"
gt_tut_orb_boss_5 = "ToG: Tutorial Boss Arena Orb #5"
gt_tut_orb_boss_6 = "ToG: Tutorial Boss Arena Orb #6"

wd_right = "WD: Right Above Bombable Block"
wd_top = "WD: Top of Middle Hill"
wd_bottom = "WD: Bottom of Middle Hill"
wd_cliffs_ore_t = "WD: Middle Hill Top Ore"
wd_cliffs_ore_l = "WD: Middle Hill Left Ore"
wd_cliffs_ore_m = "WD: Middle Hill Middle Ore"
wd_cliffs_ore_r = "WD: Middle Hill Right Ore"
wd_cliffs_ore_b = "WD: Middle Hill Bottom Ore"

c_tt_breakable_wall = "Tenacious Trollies: Breakable Wall"
c_tt_end = "Tenacious Trollies: Reward"
c_tt_ore = "Tenacious Trollies: Ore"
c_tt_orb = "Tenacious Trollies: Orb"

# El Machino
em_heisenberg = "Clifford Heisenberg Upgrade"
em_carson_1 = "Trader Carson Trade #1"
em_carson_2 = "Trader Carson Trade #2"
em_carson_3 = "Trader Carson Trade #3"
em_carson_4 = "Trader Carson Trade #4"
em_carson_5 = "Trader Carson Trade #5"
em_carson_6 = "Trader Carson Trade #6"
em_carson_7 = "Trader Carson Trade #7"
em_artifact_1 = "1 Artifact"
em_artifact_3 = "3 Artifacts"
em_artifact_6 = "6 Artifacts"
em_artifact_10 = "10 Artifacts"
em_artifact_15 = "15 Artifacts"
em_artifact_21 = "21 Artifacts"
em_artifact_28 = "28 Artifacts"
em_artifact_42 = "42 Artifacts"

wp_cliff = "WP: Left Cliffside"
wp_cliffside_ore = "WP: Left Cliffside Ore"
wp_cliff_ore_1 = "WP: Cliff Interior Ore #1"
wp_cliff_ore_2 = "WP: Cliff Interior Ore #2"
wp_cliff_ore_3 = "WP: Cliff Interior Ore #3"
wp_cliff_ore_4 = "WP: Cliff Interior Ore #4"
wp_bottom_l = "WP: Plains Left"
wp_bottom_r = "WP: Plains Right"
wp_hill_right = "WP: Right Cliff"

c_pp_ore = "Prickly Panorama: Ore"

c_rf_top_right = "Rock Falls: Top Right"
c_rf_end = "Rock Falls: End"
c_rf_ore = "Rock Falls: Ore"

a_top_l_t = "Archaea Top: Upper Left in Wall"
a_top_ore_l_t = "Archaea Top: Ore Upper Left in Wall"
a_top_ore_gates_l = "Archaea Top: Left Ore Under Gates"
a_top_ore_gates_r = "Archaea Top: Right Ore Under Gates"
a_top_ore_r = "Archaea Top: Bottom Right Ore"
a_top_ore_l_1 = "Archaea Top: Entrance Ore #1"
a_top_ore_l_2 = "Archaea Top: Entrance Ore #2"
a_top_ore_l_3 = "Archaea Top: Entrance Ore #3"
a_top_ore_l_4 = "Archaea Top: Entrance Ore #4"
a_top_ore_l_5 = "Archaea Top: Entrance Ore #5"
a_top_ore_l_6 = "Archaea Top: Entrance Ore #6"
a_top_ore_l_7 = "Archaea Top: Entrance Ore #7"
a_top_ore_l_8 = "Archaea Top: Entrance Ore #8"
a_top_l_b = "Archaea Top: Lower Left in Wall"
a_top_r = "Archaea Top: Right Below Cave"

c_pwg_ledge = "Patch Wall Grotto: Ledge"
c_pwg_secret = "Patch Wall Grotto: Secret Passage"
c_pwg_orb = "Patch Wall Grotto: Orb"

c_bs_podium = "Burster's Station: Upgrade Podium"
c_bs_secret_r = "Burster's Station: Right Secret"
c_bs_secret_t = "Burster's Station: Top Secret"
c_bs_podium_ore = "Burster's Station: Ore Above Podium"
c_bs_orb_start = "Burster's Station: Start Orb"
c_bs_orb_end = "Burster's Station: End Orb"

a_rrp_l = "Archaea RRP: Left"
a_rrp_ore = "Archaea RRP: Ore"
a_rrp_r = "Archaea Below RRP: Right"
a_rrp_ore_n = "Archaea Below RRP: North Ore Under Block"
a_rrp_ore_m = "Archaea Below RRP: Middle Ore Under Block"
a_rrp_ore_se = "Archaea Below RRP: SE Ore Under Block"
a_rrp_ore_sw = "Archaea Below RRP: SW Ore Under Block"
a_rrp_ore_w = "Archaea Below RRP: Left Ore"

c_cic_end = "Cave-In Catacomb: End"
c_cic_top_secret = "Cave-In Catacomb: Top Secret"
c_cic_orb = "Cave-In Catacomb: Orb"

a_cp_from_wp = "Archaea Cactus Plantation: Door Ledge"
a_cp_ore_from_wp = "Archaea Cactus Plantation: Door Ore"
a_cp_ore_nw = "Archaea Cactus Plantation: NW Ore"
a_cp_ore_m = "Archaea Cactus Plantation: Middle Ore"

a_atw_ore_nw_1 = "Archaea Above the Wall: NW Ore #1"

a_wall = "Archaea Wall: Left in Wall"

c_tbr_reward = "Tick Boom Room Reward"
c_tbr_orb = "Tick Boom Room Orb"

c_tb_orb = "Trilobyte Bluff: Orb"
c_tb_end = "Trilobyte Bluff: End"

y_up_lake_t = "Yarrow Upper: Above Lower Lake"
y_up_lake_r = "Yarrow Upper: Secret Right of Lower Lake"
y_up_luke_yonker = "Yarrow Upper: Luke Yonker"
y_up_lake_ore_l = "Yarrow Upper: Below Luke Yonker"
y_up_lake_ore_m = "Yarrow Upper: Left of Upper Lake"
y_up_lake_ore_r = "Yarrow Upper: Above Upper Lake"
y_lo_lake_ore_l = "Yarrow Upper: Above Entrance to Lower Yarrow"
y_lo_lake_ore_r = "Yarrow Upper: Left of Lower Lake"

a_bwall_entr = "Archaea: Brick Area Entrance Ledge"
a_bwall_ore_t = "Archaea: Ore Above Oasis Entrance"
a_bwall_ore_b = "Archaea: Ore Under Oasis Entrance"
a_bwall_l = "Archaea Below the Wall: Left"
a_bwall_ore_l = "Archaea Below the Wall: Left Ore"
a_bwall_ore_r = "Archaea Below the Wall: Right Ore"
a_josh_yonker = "Archaea: Josh Yonker"

c_ms_podium = "Mason's Station: Upgrade Podium"
c_ms_top = "Mason's Station: Top Secret"
c_ms_end = "Mason's Station: End"
c_ms_before_podium_ore_1 = "Mason's Station: Ore Before Podium #1"
c_ms_before_podium_ore_2 = "Mason's Station: Ore Before Podium #2"
c_ms_before_podium_ore_3 = "Mason's Station: Ore Before Podium #3"
c_ms_bricks_ore_1 = "Mason's Station: Ore In Bricks #1"
c_ms_bricks_ore_2 = "Mason's Station: Ore In Bricks #2"
c_ms_bricks_ore_3 = "Mason's Station: Ore In Bricks #3"
c_ms_podium_ore = "Mason's Station: Ore Above Podium"
c_ms_orb = "Mason's Station: Orb"

a_bo_ore_nw_1 = "Archaea Before the Oasis: NW Ore #1"
a_bo_ore_nw_2 = "Archaea Before the Oasis: NW Ore #2"
a_bo_ore_nw_3 = "Archaea Before the Oasis: NW Ore #3"
a_bo_ore_r_secret_1 = "Archaea Before the Oasis: Right Secret Ore #1"
a_bo_ore_r_secret_2 = "Archaea Before the Oasis: Right Secret Ore #2"
a_bo_ore_r_secret_3 = "Archaea Before the Oasis: Right Secret Ore #3"
a_bo_ore_r_secret_4 = "Archaea Before the Oasis: Right Secret Ore #4"
a_bo_ore_m = "Archaea Before the Oasis: Middle Ore"

c_rrh_end = "Rupture Rock Hollow: End"
c_rrh_top = "Rupture Rock Hollow: Top Secret"
c_rrh_right = "Rupture Rock Hollow: Right Ledge"
c_rrh_ore_1 = "Rupture Rock Hollow: Ore #1"
c_rrh_ore_2 = "Rupture Rock Hollow: Ore #2"
c_rrh_orb_start = "Rupture Rock Hollow: Start Orb"
c_rrh_orb_mid = "Rupture Rock Hollow: Midpoint Orb"
c_rrh_orb_end = "Rupture Rock Hollow: End Orb"

o_top = "Oasis: Top Secret"

c_rs_podium = "Rosie's Storage: Upgrade Podium"
c_rs_secret_r = "Rosie's Storage: Right Secret"
c_rs_end = "Rosie's Storage: End"
c_rs_orb = "Rosie's Storage: Orb"
c_rs_ore_1 = "Rosie's Storage: Ore #1"
c_rs_ore_2 = "Rosie's Storage: Ore #2"
c_rs_ore_3 = "Rosie's Storage: Ore #3"
c_rs_ore_4 = "Rosie's Storage: Ore #4"

o_r_orb_entr_1 = "The Reactor: Entrance Orb #1"
o_r_orb_entr_2 = "The Reactor: Entrance Orb #2"
o_r_orb_entr_3 = "The Reactor: Entrance Orb #3"
o_r_orb_entr_4 = "The Reactor: Entrance Orb #4"
o_r_orb_p1_1 = "The Reactor: 1st Phase Orb #1"
o_r_orb_p1_2 = "The Reactor: 1st Phase Orb #2"
o_r_orb_p1_3 = "The Reactor: 1st Phase Orb #3"
o_r_orb_p1_4 = "The Reactor: 1st Phase Orb #4"
o_r_orb_p2_1 = "The Reactor: 2nd Phase Orb #1"
o_r_orb_p2_2 = "The Reactor: 2nd Phase Orb #2"
o_r_orb_p2_3 = "The Reactor: 2nd Phase Orb #3"
o_r_orb_p2_4 = "The Reactor: 2nd Phase Orb #4"
o_r_orb_p3_1 = "The Reactor: 3rd Phase Orb #1"
o_r_orb_p3_2 = "The Reactor: 3rd Phase Orb #2"
o_r_orb_p3_3 = "The Reactor: 3rd Phase Orb #3"
o_r_orb_p3_4 = "The Reactor: 3rd Phase Orb #4"
o_r_orb_p4_1 = "The Reactor: 4th Phase Orb #1"
o_r_orb_p4_2 = "The Reactor: 4th Phase Orb #2"
o_r_orb_p4_3 = "The Reactor: 4th Phase Orb #3"
o_r_orb_p4_4 = "The Reactor: 4th Phase Orb #4"
o_r_orb_p5_1 = "The Reactor: 5th Phase Orb #1"
o_r_orb_p5_2 = "The Reactor: 5th Phase Orb #2"
o_r_orb_p5_3 = "The Reactor: 5th Phase Orb #3"
o_r_orb_p5_4 = "The Reactor: 5th Phase Orb #4"
o_r_orb_p6_1 = "The Reactor: 6th Phase Orb #1"
o_r_orb_p6_2 = "The Reactor: 6th Phase Orb #2"
o_r_orb_p6_3 = "The Reactor: 6th Phase Orb #3"
o_r_orb_p6_4 = "The Reactor: 6th Phase Orb #4"
o_r_orb_p7_1 = "The Reactor: 7th Phase Orb #1"
o_r_orb_p7_2 = "The Reactor: 7th Phase Orb #2"
o_r_orb_p7_3 = "The Reactor: 7th Phase Orb #3"
o_r_orb_p7_4 = "The Reactor: 7th Phase Orb #4"
o_r_orb_p8_1 = "The Reactor: 8th Phase Orb #1"
o_r_orb_p8_2 = "The Reactor: 8th Phase Orb #2"
o_r_orb_p8_3 = "The Reactor: 8th Phase Orb #3"
o_r_orb_p8_4 = "The Reactor: 8th Phase Orb #4"
o_r_orb_p9_1 = "The Reactor: 9th Phase Orb #1"
o_r_orb_p9_2 = "The Reactor: 9th Phase Orb #2"
o_r_orb_p9_3 = "The Reactor: 9th Phase Orb #3"
o_r_orb_p9_4 = "The Reactor: 9th Phase Orb #4"
o_r_orb_p10_1 = "The Reactor: 10th Phase Orb #1"
o_r_orb_p10_2 = "The Reactor: 10th Phase Orb #2"
o_r_orb_p10_3 = "The Reactor: 10th Phase Orb #3"
o_r_orb_p10_4 = "The Reactor: 10th Phase Orb #4"
o_r_orb_p10_5 = "The Reactor: 10th Phase Orb #5"

a_lmo_ceiling = "Archaea Lower Mining Outpost: In Ceiling Under Tube"
a_lmo_ore_end_1 = "Archaea Lower Mining Outpost: End Ore #1"
a_lmo_ore_end_2 = "Archaea Lower Mining Outpost: End Ore #2"
a_lmo_ore_end_3 = "Archaea Lower Mining Outpost: End Ore #3"
a_lmo_ore_nw_1 = "Archaea Lower Mining Outpost: NW Ore #1"
a_lmo_ore_nw_2 = "Archaea Lower Mining Outpost: NW Ore #2"
a_lmo_ore_nw_3 = "Archaea Lower Mining Outpost: NW Ore #3"
a_lmo_ore_e_1 = "Archaea Lower Mining Outpost: East Ore #1"
a_lmo_ore_e_2 = "Archaea Lower Mining Outpost: East Ore #2"
a_lmo_ore_e_3 = "Archaea Lower Mining Outpost: East Ore #3"
a_lmo_ore_e_loner = "Archaea Lower Mining Outpost: East Loner Ore"
a_lmo_ore_n = "Archaea Lower Mining Outpost: North Ore"
a_lmo_ore_bricks = "Archaea Lower Mining Outpost: Brick Area Ore"

a_b_l = "Archaea Bottom: Top Left"
a_b_r = "Archaea Bottom: Right"
a_b_m = "Archaea Bottom: Middle"
a_b_jet_b = "Archaea Bottom: Jet Engine Course Bottom"
a_b_jet_end = "Archaea Bottom: Jet Engine Course End"
a_b_jet_orb = "Archaea Bottom: Jet Engine Course End Orb"
a_b_jet_ore_1 = "Archaea Bottom: Jet Engine Course End Ore #1"
a_b_jet_ore_2 = "Archaea Bottom: Jet Engine Course End Ore #2"
a_b_jet_ore_3 = "Archaea Bottom: Jet Engine Course End Ore #3"
a_b_jet_ore_4 = "Archaea Bottom: Jet Engine Course End Ore #4"

c_mc_podium = "Mysterious Cave: Upgrade Podium"
c_mc_top = "Mysterious Cave: Top Secret"
c_mc_orb = "Mysterious Cave: Orb"

v_ore_1 = "Vectron: Ore #1"
v_ore_2 = "Vectron: Ore #2"
v_ore_3 = "Vectron: Ore #3"
v_ore_4 = "Vectron: Ore #4"
v_ore_5 = "Vectron: Ore #5"

totd_upper_m = "TotD: Top Entrance Middle"
totd_upper_r = "TotD: Top Entrance Right Secret"
totd_upper_ore_m = "TotD: Top Entrance Middle Ore"
totd_upper_ore_r_1 = "TotD: Top Entrance Right Ore #1"
totd_upper_ore_r_2 = "TotD: Top Entrance Right Ore #2"
totd_upper_ore_r_3 = "TotD: Top Entrance Right Ore #3"
totd_upper_ore_r_4 = "TotD: Top Entrance Right Ore #4"

totd_entrance_top = "TotD: Main Entrance Right"

c_dc_bottom = "Demon's Crib: Beneath Lava"
c_dc_ore = "Demon's Crib: Ore"
c_dc_orb_entr = "Demon's Crib: Entrance Orb"
c_dc_orb_end = "Demon's Crib: End Orb"

totd_es_maze = "TotD: Entrance Shaft Maze"

c_tbc_top_r = "The Batcave: Top Right"
c_tbc_top_l = "The Batcave: Top Left Secret"
c_tbc_orb = "The Batcave: Orb"

totd_cm_m = "TotD: Conveyor Maze Middle"
totd_cm_end_t = "TotD: Conveyor Maze End Top"
totd_cm_end_b = "TotD: Conveyor Maze End Bottom"
totd_cm_orb_t = "TotD: Orb Above Conveyor Maze"
totd_cm_orb_b = "TotD: Conveyor Maze Orb"
totd_cm_ore_tl_1 = "TotD: Conveyor Maze Top Left Ore #1"
totd_cm_ore_tl_2 = "TotD: Conveyor Maze Top Left Ore #2"
totd_cm_ore_t = "TotD: Conveyor Maze Top Ore"
totd_cm_ore_bl_1 = "TotD: Conveyor Maze Bottom Left Ore #1"
totd_cm_ore_bl_2 = "TotD: Conveyor Maze Bottom Left Ore #2"
totd_cm_ore_b = "TotD: Conveyor Maze Bottom Ore"

c_fil_orb_entr = "Floor is Lava: Entrance Orb"
c_fil_orb_m = "Floor is Lava: Middle Orb"
c_fil_orb_t = "Floor is Lava: Top Orb"
c_fil_end = "Floor is Lava: End"
c_fil_perfect = "Floor is Lava: Perfect End"

c_ls_orb_entr = "Lava Shooters: Entrance Orb"
c_ls_orb_t = "Lava Shooters: Top Orb"
c_ls_orb_b = "Lava Shooters: Bottom Orb"
c_ls_orb_end = "Lava Shooters: End Orb"
c_ls_ledge_r = "Lava Shooters: Right Ledge"
c_ls_end_secret = "Lava Shooters: End Secret"
c_ls_end = "Lava Shooters: End"

c_rr_secret_l = "Roasted Romp: Left Secret"
c_rr_ore_1 = "Roasted Romp: Ore #1"
c_rr_ore_2 = "Roasted Romp: Ore #2"
c_rr_ore_3 = "Roasted Romp: Ore #3"
c_rr_orb_entr = "Roasted Romp: Entrance Orb"
c_rr_orb_end = "Roasted Romp: End Orb"
c_rr_end = "Roasted Romp: End"

totd_ga = "TotD: Golem Altar Upper"
totd_ga_ore = "TotD: Golem Altar Upper Ore"

c_gh_orb_entr = "Grim Hollow: Entrance Orb"
c_gh_secret_left = "Grim Hollow: Left Secret"
c_gh_orb_m = "Grim Hollow: Midpoint Orb"
c_gh_end = "Grim Hollow: End"

c_sac_secret_r = "Spikes & Conveyors: Right Secret"
c_sac_secret_t = "Spikes & Conveyors: Top Secret"
c_sac_end = "Spikes & Conveyors: End"
c_sac_orb_entr = "Spikes & Conveyors: Entrance Orb"
c_sac_orb_m = "Spikes & Conveyors: Midpoint Orb"
c_sac_orb_end = "Spikes & Conveyors: End Orb"

totd_bowels_l = "TotD: Bowels Lava Left"
totd_bowels_m = "TotD: Bowels Middle Lava Pool Top"

c_cs_podium = "Combuster's Station: Upgrade Podium"
c_cs_secret_l = "Combuster's Station: End Secret"
c_cs_ore = "Combuster's Station: Ore"
c_cs_orb_entr_1 = "Combuster's Station: Entrance Orb #1"
c_cs_orb_entr_2 = "Combuster's Station: Entrance Orb #2"
c_cs_orb_arena_1 = "Combuster's Station: Lower Left Arena Orb"
c_cs_orb_arena_2 = "Combuster's Station: Top Left Arena Orb"
c_cs_orb_arena_3 = "Combuster's Station: Top Center Arena Orb"
c_cs_orb_arena_4 = "Combuster's Station: Top Right Arena Orb"
c_cs_orb_arena_5 = "Combuster's Station: Bottom Right Arena Orb"
c_cs_orb_arena_m = "Combuster's Station: Bottom Center Arena Orb"
c_cs_orb_end = "Combuster's Station: End Orb"

c_rtc_podium = "Ronald's Treasure Chamber: Upgrade Podium"
c_rtc_secret_1 = "Ronald's Treasure Chamber: Secret Left"
c_rtc_secret_2 = "Ronald's Treasure Chamber: Secret Middle"
c_rtc_secret_3 = "Ronald's Treasure Chamber: Secret Right"
c_rtc_ore_b = "Ronald's Treasure Chamber: Bottom Ore"
c_rtc_ore_secret = "Ronald's Treasure Chamber: Secret Ore"

totd_river_t = "TotD: Top Lava River Right"
totd_river_t_orb_entr = "TotD: Top Lava River Left Orb"
totd_river_t_ore_entr = "TotD: Top Lava River Left Ore"
totd_river_t_orb_m = "TotD: Top Lava River Middle Orb"
totd_river_t_ore_end = "TotD: Top Lava River Right Ore"
totd_river_m_r_ore = "TotD: Middle Lava River Right Ore"
totd_river_b_l = "TotD: Bottom Lava River Left"
totd_river_b_b = "TotD: Bottom Lava River Bottom"
totd_river_b_r = "TotD: Bottom Lava River Right"
totd_river_b_t = "TotD: Bottom Lava River Top"
totd_river_b_ore_l_1 = "TotD: Bottom Lava River Left Ore #1"
totd_river_b_ore_l_2 = "TotD: Bottom Lava River Left Ore #2"
totd_river_b_ore_armory = "TotD: Ore Under Sun Armory"
totd_river_b_ore_1 = "TotD: Ore Right of Sun Armory"
totd_river_b_ore_2 = "TotD: Bottom Lava River Upper Hallway Ore"
totd_river_b_ore_3 = "TotD: Bottom Lava River Left Ore Cluster"
totd_river_b_ore_4 = "TotD: Bottom Lava River Middle Ore Cluster #1"
totd_river_b_ore_5 = "TotD: Bottom Lava River Middle Ore Cluster #2"
totd_river_b_ore_6 = "TotD: Bottom Lava River Bottom Ore Cluster #1"
totd_river_b_ore_7 = "TotD: Bottom Lava River Bottom Ore Cluster #2"
totd_river_b_ore_8 = "TotD: Bottom Lava River Bottom Ore Cluster #3"

c_ic_orb_entr = "Infernal Crates: Entrance Orb"
c_ic_orb_m = "Infernal Crates: Middle Orb"
c_ic_secret_r = "Infernal Crates: Right Secret"
c_ic_end = "Infernal Crates: End"
c_ic_ore = "Infernal Crates: Ore"

c_mm_reward_1 = "Mine Cart Madness: Midpoint Reward"
c_mm_reward_2 = "Mine Cart Madness: End #1"
c_mm_reward_3 = "Mine Cart Madness: End #2"
c_mm_ore = "Mine Cart Madness: Ore"
c_mm_orb_1 = "Mine Cart Madness: Entrance Orb"
c_mm_orb_2 = "Mine Cart Madness: 2nd Room Orb"
c_mm_orb_3 = "Mine Cart Madness: 3rd Room Orb"

c_sa_podium = "The Sun Armory: Upgrade Podium"
c_sa_ore = "The Sun Armory: Ore"

tog_cistern_l = "ToG: Cistern Left"
tog_cistern_r = "ToG: Cistern Right"
tog_cistern_m = "ToG: Cistern Middle Cave Exit"
tog_cistern_ore_l_1 = "ToG: Cistern Left Ore #1"
tog_cistern_ore_l_2 = "ToG: Cistern Left Ore #2"
tog_cistern_ore_l_3 = "ToG: Cistern Left Ore #3"
tog_cistern_ore_r_1 = "ToG: Cistern Right Ore #1"
tog_cistern_ore_r_2 = "ToG: Cistern Right Ore #2"
tog_cistern_ore_r_3 = "ToG: Cistern Right Ore #3"

c_cos_podium = "Chamber of Secrets: Upgrade Podium"
c_cos_wall_l = "Chamber of Secrets: Illusory Wall"
c_cos_end = "Chamber of Secrets: End"
c_cos_ore_t = "Chamber of Secrets: Top Ore"
c_cos_ore_b = "Chamber of Secrets: Bottom Ore"
c_cos_orb_entr = "Chamber of Secrets: Entrance Orb"
c_cos_orb_r = "Chamber of Secrets: Right Orb"
c_cos_orb_end = "Chamber of Secrets: End Orb"

c_coa_secret = "Chamber of Arrows: Secret"
c_coa_end = "Chamber of Arrows: End"
c_coa_ore = "Chamber of Arrows: Ore"
c_coa_orb_entr = "Chamber of Arrows: Entrance Orb"
c_coa_orb_before_arrows_1 = "Chamber of Arrows: Orb Before Arena #1"
c_coa_orb_before_arrows_2 = "Chamber of Arrows: Orb Before Arena #2"
c_coa_orb_arrows = "Chamber of Arrows: Arena Orb"

c_cow_orb_entr = "Chamber of Wheels: Entrance Orb"
c_cow_orb_m = "Chamber of Wheels: Midpoint Orb"
c_cow_secret = "Chamber of Wheels: Secret"
c_cow_end = "Chamber of Wheels: End"

y_lower_below_acid_l = "Yarrow: Below the Acid Swamp Left"
y_lower_bouncy_ceil = "Yarrow: Bounce House Ceiling"
y_lower_ore_bouncy_1 = "Yarrow: Bounce House Left Ore"
y_lower_ore_bouncy_2 = "Yarrow: Bounce House Middle Left Ore"
y_lower_ore_bouncy_3 = "Yarrow: Bounce House Middle Right Ore"
y_lower_ore_bouncy_4 = "Yarrow: Bounce House Right Ore"
y_lower_ore_m = "Yarrow: Mushroom Pond Top Ore"
y_lower_ore_b = "Yarrow: Mushroom Pond Bottom Ore"
y_lower_above_mm = "Yarrow: Above Mosquito Minefield Acid Pool"
y_lower_mm_l = "Yarrow: Mosquito Minefield Left"

c_sss_secret_r = "Swim Swam Sway: Right Secret"
c_sss_secret_l = "Swim Swam Sway: Left Secret"
c_sss_end = "Swim Swam Sway: End"
c_sss_orb_entr = "Swim Swam Sway: Entrance Orb"
c_sss_orb_end = "Swim Swam Sway: End Orb"
c_sss_ore_r = "Swim Swam Sway: Right Ore"
c_sss_ore_l_1 = "Swim Swam Sway: Left Ore #1"
c_sss_ore_l_2 = "Swim Swam Sway: Left Ore #2"

c_srb_r = "Sludge River Bend: Right Behind Rock"
c_srb_m = "Sludge River Bend: Middle Behind Rock"
c_srb_orb_entr = "Sludge River Bend: Entrance Orb"
c_srb_orb_l = "Sludge River Bend: Middle Left Orb"
c_srb_orb_m = "Sludge River Bend: Middle Right Orb"
c_srb_orb_r = "Sludge River Bend: Right Orb"
c_srb_ore_entr = "Sludge River Bend: Entrance Ore"
c_srb_ore_l = "Sludge River Bend: Top Left Ore"
c_srb_ore_m_1 = "Sludge River Bend: Middle Ore #1"
c_srb_ore_m_2 = "Sludge River Bend: Middle Ore #2"
c_srb_ore_m_3 = "Sludge River Bend: Middle Ore #3"
c_srb_ore_r = "Sludge River Bend: Top Right Ore"
c_srb_ore_1 = "Sludge River Bend: Ore 1"
c_srb_ore_2 = "Sludge River Bend: Ore 2"
c_srb_ore_3 = "Sludge River Bend: Ore 3"

c_ll_secret_b = "Leaky Lodge: Under Rock Below Start"
c_ll_secret_t = "Leaky Lodge: Top Secret"
c_ll_end = "Leaky Lodge: End"
c_ll_orb_entr = "Leaky Lodge: Entrance Orb"
c_ll_orb_tr = "Leaky Lodge: Orb Before End Drop"
c_ll_orb_bl = "Leaky Lodge: Bottom Orb"
c_ll_orb_tl = "Leaky Lodge: Left Orb"
c_ll_ore_tr_1 = "Leaky Lodge: Top Right Ore #1"
c_ll_ore_tr_2 = "Leaky Lodge: Top Right Ore #2"
c_ll_ore_tr_3 = "Leaky Lodge: Top Right Ore #3"
c_ll_ore_tl_1 = "Leaky Lodge: Top Left Top Ore"
c_ll_ore_tl_2 = "Leaky Lodge: Top Left Bottom Ore"
c_ll_ore_t = "Leaky Lodge: Topmost Ore"
c_ll_ore_bl = "Leaky Lodge: Leftmost Ore"

c_hph_secret = "Hodge-Podge Hang: Secret"
c_hph_end = "Hodge-Podge Hang: End"
c_hph_ore = "Hodge-Podge Hang: Ore"
c_hph_orb_entr = "Hodge-Podge Hang: Entrance Orb"
c_hph_orb_end = "Hodge-Podge Hang: End Orb"

c_mms_secret = "Mushi Mushi Snuggery: Secret"
c_mms_end = "Mushi Mushi Snuggery: End"
c_mms_ore = "Mushi Mushi Snuggery: Ore"
c_mms_orb_entr = "Mushi Mushi Snuggery: Entrance Orb"
c_mms_orb_end = "Mushi Mushi Snuggery: End Orb"

c_bb_secret = "Bushwack Beehive: Secret"
c_bb_end = "Bushwack Beehive: End"
c_bb_ore_1 = "Bushwack Beehive: Ore #1"
c_bb_ore_2 = "Bushwack Beehive: Ore #2"
c_bb_orb = "Bushwack Beehive: Orb"

c_lime_loop_end = "Lime Loop: End"
c_lime_loop_secret = "Lime Loop: Secret"
c_lime_loop_orb = "Lime Loop: Orb"

c_as_podium = "Aeronaut's Station: Upgrade Podium"
c_as_end = "Aeronaut's Station: End"
c_as_secret = "Aeronaut's Station: Secret"
c_as_ore = "Aeronaut's Station: Ore"
c_as_orb = "Aeronaut's Station: Orb"

c_hell_end = "Trials Reward"

# Shop Upgrade Locations
em_pickaxe_2 = "Pickaxe Tier 2 Upgrade"
em_pickaxe_3 = "Pickaxe Tier 3 Upgrade"
em_pickaxe_4 = "Pickaxe Tier 4 Upgrade"
em_pickaxe_5 = "Pickaxe Tier 5 Upgrade"
em_pickaxe_6 = "Pickaxe Tier 6 Upgrade"
em_pickaxe_7 = "Pickaxe Tier 7 Upgrade"
em_pickaxe_8 = "Pickaxe Tier 8 Upgrade"
em_backpack_2 = "Bag Tier 2 Upgrade"
em_backpack_3 = "Bag Tier 3 Upgrade"
em_backpack_4 = "Bag Tier 4 Upgrade"
em_backpack_5 = "Bag Tier 5 Upgrade"
em_backpack_6 = "Bag Tier 6 Upgrade"
em_backpack_7 = "Bag Tier 7 Upgrade"
em_backpack_8 = "Bag Tier 8 Upgrade"
em_backpack_9 = "Bag Tier 9 Upgrade"
em_backpack_10 = "Bag Tier 10 Upgrade"
em_lamp_1 = "Lamp Tier 1 Upgrade"
em_lamp_2 = "Lamp Tier 2 Upgrade"
em_lamp_3 = "Lamp Tier 3 Upgrade"
em_lamp_4 = "Lamp Tier 4 Upgrade"
em_lamp_5 = "Lamp Tier 5 Upgrade"
em_lamp_6 = "Lamp Tier 6 Upgrade"
em_lamp_7 = "Lamp Tier 7 Upgrade"
em_armor_2 = "Armor Tier 2 Upgrade"
em_armor_3 = "Armor Tier 3 Upgrade"
em_armor_4 = "Armor Tier 4 Upgrade"
em_armor_5 = "Armor Tier 5 Upgrade"
em_armor_6 = "Armor Tier 6 Upgrade"
em_armor_7 = "Armor Tier 7 Upgrade"
em_armor_8 = "Armor Tier 8 Upgrade"
em_tank_1 = "Water Tank Tier 1 Upgrade"
em_tank_2 = "Water Tank Tier 2 Upgrade"
em_tank_3 = "Water Tank Tier 3 Upgrade"
em_tank_4 = "Water Tank Tier 4 Upgrade"
em_tank_5 = "Water Tank Tier 5 Upgrade"
em_bomb_1 = "Pressure Bomb Tier 1 Upgrade"
em_bomb_2 = "Pressure Bomb Tier 2 Upgrade"
em_bomb_3 = "Pressure Bomb Tier 3 Upgrade"
em_bomb_4 = "Pressure Bomb Tier 4 Upgrade"
em_hammer_1 = "Jackhammer Tier 1 Upgrade"
em_hammer_2 = "Jackhammer Tier 2 Upgrade"
em_hammer_3 = "Jackhammer Tier 3 Upgrade"
em_hammer_4 = "Jackhammer Tier 4 Upgrade"
em_jetpack_1 = "Jetpack Tier 1 Upgrade"
em_jetpack_2 = "Jetpack Tier 2 Upgrade"
em_jetpack_3 = "Jetpack Tier 3 Upgrade"

# Event locations
ev_tog_cistern_button_l = "ToG: Cistern Left Button"
ev_tog_cistern_button_r = "ToG: Cistern Right Button"

ev_totd_treasure_brazier_top = "TotD: Top Treasure Brazier"
ev_totd_treasure_brazier_right = "TotD: Right Treasure Brazier"
ev_totd_treasure_brazier_left = "TotD: Left Treasure Brazier"

ev_device_of_doom = "Device of Doom"
ev_device_of_destruction = "Device of Destruction"
ev_device_of_devastation = "Device of Devastation"
ev_device_of_disaster = "Device of Disaster"

ev_defeat_rosie = "Defeat Rosie"

YONKER_LOCS = {
    wd_zebulon_yonker,
    y_up_luke_yonker,
    a_josh_yonker,
}