# Castle Region Names
menu = "Menu"

p1_start = "Prison Floor 1 Start"
p1_s = "Prison Floor 1 South"
p1_sw_bronze_gate = "Prison Floor 1 SW Bronze Gate"
p1_e = "Prison Floor 1 East"
p1_m_bronze_gate = "Prison Floor 1 Middle Bronze Gate"
p1_from_p2 = "Prison Floor 1 From Floor 2"
p1_from_p3_n = "Prison Floor 1 From Floor 3 North"
p1_from_p3_s = "Prison Floor 1 From Floor 3 South"

p2_start = "Prison Floor 2 Start"
p2_m = "Prison Floor 2 Middle"
p2_n = "Prison Floor 2 North"
p2_red_switch = "Prison Floor 2 Red Spike Switch"
p2_e_bronze_gate = "Prison Floor 2 East Bronze Gate"
p2_s = "Prison Floor 2 South"
p2_gg_room_reward = "Prison Floor 2 Gold Gate Room Reward"
p2_e_bronze_gate_2 = "Prison Floor 2 East Bronze Gate Past Gold Gate"
p2_m_bronze_gate = "Prison Floor 2 Middle Bronze Gate"
p2_se_bronze_gate = "Prison Floor 2 SE Bronze Gate"
p2_end = "Prison Floor 2 End"

p3_start = "Prison Floor 3 Start"
p3_nw_n_bronze_gate = "Prison Floor 3 NW Area North Bronze Gate"
p3_nw_s_bronze_gate = "Prison Floor 3 NW Area South Bronze Gate"
p3_silver_gate = "Prison Floor 3 Silver Gate"
p3_n_gold_gate = "Prison Floor 3 North Gold Gate"
p3_bonus_return = "Prison Floor 3 Complete Bonus"
p3_s_bronze_gate = "Prison Floor 3 South Bronze Gate"
p3_s_gold_gate = "Prison Floor 3 South Gold Gate"
p3_portal_from_p1 = "Prison Floor 3 Skip Boss Switch"

n1_start = "Bonus 1 Start"
n1_room1 = "Bonus 1 Room 1"
n1_room2 = "Bonus 1 Room 2"
n1_room3 = "Bonus 1 Room 3"
n1_room4 = "Bonus 1 Room 4"

b1_start = "Boss 1 Start"
b1_arena = "Boss 1 Arena"
b1_defeated = "Boss 1 Defeated"

a1_start = "Armory Floor 1 Start"

b4_defeated = "Dragon Defeated"
escaped = "Escaped Castle Hammerwatch"

get_planks = "Collect All Planks"
