# Castle Hammerwatch Pickup Location Names
# Prison 1
p1_by_nw_bronze_gate = "Prison Floor 1 By NW Bronze Gate"
p1_entrance_1 = "Prison Floor 1 Entrance Hidden Hall Below Secret Dupe 1"
p1_entrance_2 = "Prison Floor 1 Entrance Hidden Hall Below Secret Dupe 2"
p1_entrance_3 = "Prison Floor 1 Entrance Hidden Hall Below Secret Dupe 3"
p1_entrance_4 = "Prison Floor 1 Entrance Hidden Hall Below Secret Dupe 4"
p1_entrance_secret = "Prison Floor 1 Entrance Hidden Hall Secret"
p1_entrance_hall_1 = "Prison Floor 1 Entrance Hidden Hall Left"
p1_entrance_hall_2 = "Prison Floor 1 Entrance Hidden Hall Right"
p1_entrance_s = "Prison Floor 1 Entrance Hidden Hall South Room"
p1_entrance_w = "Prison Floor 1 Entrance Hidden Hall West Room"

p1_by_sw_bronze_gate_1 = "Prison Floor 1 By SW Bronze Gate Top"
p1_by_sw_bronze_gate_2 = "Prison Floor 1 By SW Bronze Gate Left Dupe 1"
p1_by_sw_bronze_gate_3 = "Prison Floor 1 By SW Bronze Gate Left Dupe 2"
p1_by_sw_bronze_gate_4 = "Prison Floor 1 By SW Bronze Gate Cell"
p1_s_lower_hall_1 = "Prison Floor 1 South Lower Hall Dupe 1"
p1_s_lower_hall_2 = "Prison Floor 1 South Lower Hall Dupe 2"
p1_s_lower_hall_3 = "Prison Floor 1 South Lower Hall Dupe 3"
p1_s_lower_hall_4 = "Prison Floor 1 South Lower Hall Dupe 4"
p1_s_lower_hall_5 = "Prison Floor 1 South Lower Hall Dupe 5"
p1_s_lower_hall_6 = "Prison Floor 1 South Lower Hall Dupe 6"
p1_s_lower_hall_7 = "Prison Floor 1 South Lower Hall Dupe 7"
p1_s_lower_hall_8 = "Prison Floor 1 South Lower Hall Dupe 8"
p1_s_lower_hall_9 = "Prison Floor 1 South Lower Hall Dupe 9"
p1_s_lower_hall_10 = "Prison Floor 1 South Lower Hall Dupe 10"
p1_e_save_room_1 = "Prison Floor 1 East Save Room Left"
p1_e_save_room_2 = "Prison Floor 1 East Save Room Right"
p1_s_of_e_save_room = "Prison Floor 1 South of East Save Room"
p1_w_save = "Prison Floor 1 West Save"
p1_w_of_se_bronze_gate_1 = "Prison Floor 1 West of SE Bronze Gate Top"
p1_w_of_se_bronze_gate_2 = "Prison Floor 1 West of SE Bronze Gate Column Dupe 1"
p1_w_of_se_bronze_gate_3 = "Prison Floor 1 West of SE Bronze Gate Column Dupe 2"
p1_w_of_se_bronze_gate_4 = "Prison Floor 1 West of SE Bronze Gate Column Dupe 3"
p1_w_of_se_bronze_gate_5 = "Prison Floor 1 West of SE Bronze Gate Room By Column"
p1_s_w_bridges_w = "Prison Floor 1 South of West Bridges Alcove"
p1_n_of_se_bridge = "Prison Floor 1 North of SE Bridge"
p1_center_bridges_n_1 = "Prison Floor 1 North of Center Bridges Dupe 1"
p1_center_bridges_n_2 = "Prison Floor 1 North of Center Bridges Dupe 2"
p1_center_bridges_n_3 = "Prison Floor 1 North of Center Bridges Dupe 3"
p1_center_bridges_s_1 = "Prison Floor 1 South of Center Bridges Dupe 1"
p1_center_bridges_s_2 = "Prison Floor 1 South of Center Bridges Dupe 2"
p1_center_bridges_s_3 = "Prison Floor 1 South of Center Bridges Dupe 3"
p1_center_bridges_s_4 = "Prison Floor 1 South of Center Bridges Dupe 4"
p1_e_secret = "Prison Floor 1 East Secret"
p1_s_secret_1 = "Prison Floor 1 South Secret Dupe 1"
p1_s_secret_2 = "Prison Floor 1 South Secret Dupe 2"
p1_se_bridge = "Prison Floor 1 SE Bridge"

p1_sw_bronze_gate = "Prison Floor 1 SW Bronze Gate"

p1_by_exit_1 = "Prison Floor 1 By Exit Dupe 1"
p1_by_exit_2 = "Prison Floor 1 By Exit Dupe 2"
p1_by_exit_3 = "Prison Floor 1 By Exit Dupe 3"
p1_room_by_exit = "Prison Floor 1 Room By Exit"
p1_by_m_bronze_gate_1 = "Prison Floor 1 By Middle Bronze Gate Top Dupe 1"
p1_by_m_bronze_gate_2 = "Prison Floor 1 By Middle Bronze Gate Top Dupe 2"
p1_by_m_bronze_gate_3 = "Prison Floor 1 By Middle Bronze Gate Top Dupe 3"
p1_by_m_bronze_gate_4 = "Prison Floor 1 By Middle Bronze Gate Bottom Dupe 1"
p1_by_m_bronze_gate_5 = "Prison Floor 1 By Middle Bronze Gate Bottom Dupe 2"
p1_by_m_bronze_gate_6 = "Prison Floor 1 By Middle Bronze Gate Bottom Dupe 3"
p1_e_bridges_1 = "Prison Floor 1 North of East Bridges Dupe 1"
p1_e_bridges_2 = "Prison Floor 1 North of East Bridges Dupe 2"
p1_e_bridges_3 = "Prison Floor 1 North of East Bridges Dupe 3"
p1_e_bridges_4 = "Prison Floor 1 East Bridges"
p1_e_bridges_5 = "Prison Floor 1 South of East Bridges"
p1_ne_arrow_traps = "Prison Floor 1 NE Arrow Traps"
p1_hint_room = "Prison Floor 1 Hint Room"

p1_m_bronze_gate = "Prison Floor 1 Middle Bronze Gate"

p1_bars_1 = "Prison Floor 1 Behind Bars Dupe 1"
p1_bars_2 = "Prison Floor 1 Behind Bars Dupe 2"
p1_p2_by_shop = "Prison Floor 1 From Floor 2 By Shop"

p1_p3_n_bridge = "Prison Floor 1 North Bridge"
p1_p3_n_across_bridge = "Prison Floor 1 Across North Bridge"

p1_p3_s = "Prison Floor 1 From Floor 3"

# Prison Floor 2
p2_entrance_1 = "Prison Floor 2 NW of Entrance"
p2_entrance_2 = "Prison Floor 2 NE of Entrance"
p2_entrance_3 = "Prison Floor 2 East of Entrance Dupe"
p2_entrance_4 = "Prison Floor 2 SE of Entrance"
p2_entrance_5 = "Prison Floor 2 East of Entrance"
p2_w_of_gold_gate = "Prison Floor 2 West of East Gold Gate"
p2_nw_island_s_1 = "Prison Floor 2 NW Island South of Bridge Dupe 1"
p2_nw_island_s_2 = "Prison Floor 2 NW Island South of Bridge Dupe 2"
p2_nw_island_1 = "Prison Floor 2 NW Island North Dupe 1"
p2_nw_island_2 = "Prison Floor 2 NW Island North Dupe 2"
p2_nw_island_3 = "Prison Floor 2 NW Island North Dupe 3"
p2_nw_island_4 = "Prison Floor 2 NW Island West"
p2_nw_island_5 = "Prison Floor 2 NW Island South"
p2_w_of_silver_gate_1 = "Prison Floor 2 West of Silver Gate Dupe 1"
p2_w_of_silver_gate_2 = "Prison Floor 2 West of Silver Gate Dupe 2"

p2_spike_puzzle_e = "Prison Floor 2 East of Spike Puzzle"
p2_spike_puzzle_ne_1 = "Prison Floor 2 NE of Spike Puzzle Dupe 1"
p2_spike_puzzle_ne_2 = "Prison Floor 2 NE of Spike Puzzle Dupe 2"
p2_spike_puzzle_ne_3 = "Prison Floor 2 NE of Spike Puzzle Dupe 3"
p2_spike_puzzle_e_1 = "Prison Floor 2 East of Spike Puzzle Dupe 1"
p2_spike_puzzle_e_2 = "Prison Floor 2 East of Spike Puzzle Dupe 2"
p2_spike_puzzle_n_1 = "Prison Floor 2 Spike Puzzle North Reward 1"
p2_spike_puzzle_n_2 = "Prison Floor 2 Spike Puzzle North Reward 2"
p2_spike_puzzle_w_1 = "Prison Floor 2 Spike Puzzle West Reward 1"
p2_spike_puzzle_w_2 = "Prison Floor 2 Spike Puzzle West Reward 2"

p2_puzzle_1 = "Prison Floor 2 Puzzle Reward 1"
p2_puzzle_2 = "Prison Floor 2 Puzzle Reward 2"
p2_puzzle_3 = "Prison Floor 2 Puzzle Reward 3"
p2_puzzle_4 = "Prison Floor 2 Puzzle Reward 4"
p2_by_red_spikes_1 = "Prison Floor 2 By Red Spikes Dupe 1"
p2_by_red_spikes_2 = "Prison Floor 2 By Red Spikes Dupe 2"
p2_by_red_spikes_3 = "Prison Floor 2 By Red Spikes Dupe 3"
p2_e_of_red_spikes_1 = "Prison Floor 2 NE of Red Spikes"
p2_e_of_red_spikes_2 = "Prison Floor 2 East of Red Spikes"
p2_e_of_red_spikes_3 = "Prison Floor 2 NE Save"
p2_e_of_red_spikes_4 = "Prison Floor 2 SE of Red Spikes"
p2_e_of_ne_save_1 = "Prison Floor 2 East of NE Save Dupe 1"
p2_e_of_ne_save_2 = "Prison Floor 2 East of NE Save Dupe 2"
p2_e_poker_plant_room_1 = "Prison Floor 2 East Poker Plant Room Left Dupe 1"
p2_e_poker_plant_room_2 = "Prison Floor 2 East Poker Plant Room Left Dupe 2"
p2_e_poker_plant_room_3 = "Prison Floor 2 East Poker Plant Room Left Dupe 3"
p2_e_poker_plant_room_4 = "Prison Floor 2 East Poker Plant Room East Cell"
p2_e_poker_plant_room_5 = "Prison Floor 2 East Poker Plant Room Right Dupe 1"
p2_e_poker_plant_room_6 = "Prison Floor 2 East Poker Plant Room Right Dupe 2"
p2_e_save = "Prison Floor 2 East Save"

p2_e_gold_gate_room_1 = "Prison Floor 2 East Gold Gate Room NW"
p2_e_gold_gate_room_2 = "Prison Floor 2 East Gold Gate Room North"
p2_e_gold_gate_room_3 = "Prison Floor 2 East Gold Gate Room East"
p2_e_gold_gate_room_4 = "Prison Floor 2 East Gold Gate Room West"
p2_e_gold_gate_room_5 = "Prison Floor 2 East Gold Gate Room Center Left Cell"
p2_e_gold_gate_room_6 = "Prison Floor 2 East Gold Gate Room Center Right Cell"
p2_e_gold_gate_room_7 = "Prison Floor 2 East of Toggle Spike Trap Dupe 1"
p2_e_gold_gate_room_8 = "Prison Floor 2 East of Toggle Spike Trap Dupe 2"
p2_e_gold_gate_room_9 = "Prison Floor 2 East of Toggle Spike Trap Dupe 3"
p2_e_gold_gate_room_10 = "Prison Floor 2 East Gold Gate Room South Center Cell"
p2_e_gold_gate_room_11 = "Prison Floor 2 East Gold Gate Room South Left Cell"
p2_e_gold_gate_room_12 = "Prison Floor 2 East Gold Gate Room South Hall"
p2_e_gold_gate_room_13 = "Prison Floor 2 East Gold Gate Room South Right Cell"
p2_e_gold_gate_room_reward_1 = "Prison Floor 2 East Gold Gate Room Reward Left"
p2_e_gold_gate_room_reward_2 = "Prison Floor 2 East Gold Gate Room Reward Right"
p2_toggle_spike_trap_reward_1 = "Prison Floor 2 Toggle Spike Trap Reward 1"
p2_toggle_spike_trap_reward_2 = "Prison Floor 2 Toggle Spike Trap Reward 2"
p2_toggle_spike_trap_reward_3 = "Prison Floor 2 Toggle Spike Trap Reward 3"
p2_s_arrow_traps_1 = "Prison Floor 2 South Arrow Traps Dupe 1"
p2_s_arrow_traps_2 = "Prison Floor 2 South Arrow Traps Dupe 2"
p2_s_arrow_traps_3 = "Prison Floor 2 South Arrow Traps Dupe 3"
p2_big_bridge_1 = "Prison Floor 2 West of Big Bridge Top Dupe 1"
p2_big_bridge_2 = "Prison Floor 2 West of Big Bridge Top Dupe 2"
p2_big_bridge_3 = "Prison Floor 2 West of Big Bridge Bottom"
p2_w_poker_plant_room_1 = "Prison Floor 2 West Poker Plant Room Dupe 1"
p2_w_poker_plant_room_2 = "Prison Floor 2 West Poker Plant Room Dupe 2"
p2_w_poker_plant_room_3 = "Prison Floor 2 West Poker Plant Room Dupe 3"
p2_s_of_w_gold_gate_1 = "Prison Floor 2 South of West Gold Gate Dupe 1"
p2_s_of_w_gold_gate_2 = "Prison Floor 2 South of West Gold Gate Dupe 2"
p2_s_of_w_gold_gate_3 = "Prison Floor 2 South of West Gold Gate Dupe 3"
p2_boss_switch = "Prison Floor 2 Left of Boss Switch"
p2_sequence_puzzle_reward = "Prison Floor 2 Sequence Puzzle Reward"
p2_beetle_boss_room_1 = "Prison Floor 2 Beetle Boss Room Top"
p2_beetle_boss_room_2 = "Prison Floor 2 Beetle Boss Room Middle"
p2_beetle_boss_room_3 = "Prison Floor 2 Beetle Boss Room SW"
p2_beetle_boss_room_4 = "Prison Floor 2 Beetle Boss Room Left"
p2_beetle_boss_hidden_room_1 = "Prison Floor 2 Beetle Boss Hidden Room Top"
p2_beetle_boss_hidden_room_2 = "Prison Floor 2 Beetle Boss Hidden Room Bottom"

p2_end_1 = "Prison Floor 2 Exit Dupe 1"
p2_end_2 = "Prison Floor 2 Exit Dupe 2"

# Random Locations
crloc_p1_bronze_key_entrance = "P1 Bronze Key 1"
crloc_p1_bronze_key_sw = "P1 Bronze Key 2"
crloc_p1_bronze_key_se = "P1 Bronze Key 3"
crloc_p1_bronze_key_e = "P1 Bronze Key 4"
crloc_p1_bronze_key_n = "P1 Bronze Key 5"

crloc_p2_bkey_1 = "P2 Bronze Key 1"
crloc_p2_bkey_2 = "P2 Bronze Key 2"
crloc_p2_bkey_3 = "P2 Bronze Key 3"
crloc_p2_bkey_4 = "P2 Bronze Key 4"
crloc_p2_skey = "P2 Silver Key 1"
crloc_p2_gkey_1 = "P2 Gold Key 1"
crloc_p2_gkey_2 = "P2 Gold Key 2"
crloc_p2_puzzle = "P2 Puzzle 1"

# Event Locations
ev_p2_gold_gate_room_nw_switch = "P2 Gold Gate Room NW Switch"
ev_p2_gold_gate_room_ne_switch = "P2 Gold Gate Room NE Switch"
ev_p2_gold_gate_room_sw_switch = "P2 Gold Gate Room SW Switch"
ev_p2_gold_gate_room_se_switch = "P2 Gold Gate Room SE Switch"

# Shared Event Locations
ev_victory = "Victory"
