# Castle Region Names
menu = "Menu"

p1_start = "Prison Floor 1 Start"
p1_s = "Prison Floor 1 South"
p1_sw_bronze_gate = "Prison Floor 1 SW Bronze Gate"
p1_e = "Prison Floor 1 East"
p1_m_bronze_gate = "Prison Floor 1 Middle Bronze Gate"
p1_from_p2 = "Prison Floor 1 From Floor 2"
p1_from_p3_n = "Prison Floor 1 From Floor 3 North"
p1_from_p3_s = "Prison Floor 1 From Floor 3 South"

p2_start = "Prison Floor 2 Start"
p2_m = "Prison Floor 2 Middle"
p2_n = "Prison Floor 2 North"
p2_red_switch = "Prison Floor 2 Red Spike Switch"
p2_e_bronze_gate = "Prison Floor 2 East Bronze Gate"
p2_s = "Prison Floor 2 South"
p2_gg_room_reward = "Prison Floor 2 Gold Gate Room Reward"
p2_e_bronze_gate_2 = "Prison Floor 2 East Bronze Gate Past Gold Gate"
p2_m_bronze_gate = "Prison Floor 2 Middle Bronze Gate"
p2_se_bronze_gate = "Prison Floor 2 SE Bronze Gate"
p2_end = "Prison Floor 2 End"

p3_start = "Prison Floor 3 Start"
p3_nw_n_bronze_gate = "Prison Floor 3 NW Area North Bronze Gate"
p3_nw_s_bronze_gate = "Prison Floor 3 NW Area South Bronze Gate"
p3_silver_gate = "Prison Floor 3 Silver Gate"
p3_n_gold_gate = "Prison Floor 3 North Gold Gate"
p3_bonus_return = "Prison Floor 3 Complete Bonus"
p3_s_bronze_gate = "Prison Floor 3 South Bronze Gate"
p3_s_gold_gate = "Prison Floor 3 South Gold Gate"
p3_portal_from_p1 = "Prison Floor 3 Skip Boss Switch"

n1_start = "Bonus 1 Start"
n1_room1 = "Bonus 1 Room 1"
n1_room2 = "Bonus 1 Room 2"
n1_room3 = "Bonus 1 Room 3"
n1_room4 = "Bonus 1 Room 4"

b1_start = "Boss 1 Start"
b1_arena = "Boss 1 Arena"
b1_defeated = "Boss 1 Defeated"

a1_start = "Armory Floor 4 Start"
a1_start_shop_w = "Armory Floor 4 Start North Locked Shop"
a1_start_shop_m = "Armory Floor 4 Start NE Locked Shop"
a1_start_shop_e = "Armory Floor 4 Start SE Locked Shop"
a1_start_shop_s = "Armory Floor 4 Start South Shop"
a1_start_shop_nw = "Armory Floor 4 Start NW Shop"
a1_e = "Armory Floor 4 East"
a1_e_sw_bgate = "Armory Floor 4 East SW Vault"
a1_e_s_bgate = "Armory Floor 4 East Bronze Gate Skeleton Room"
a1_e_se_bgate = "Armory Floor 4 East SE Vault"
a1_e_e_bgate = "Armory Floor 4 East East Vault"
a1_e_ne_bgate = "Armory Floor 4 East NE Vault"
a1_se_cache = "Armory Floor 4 SE Cache"
a1_n_bgate = "Armory Floor 4 North Vault"
a1_w = "Armory Floor 4 West"
a1_w_ne_bgate = "Armory Floor 4 West NE Vault"
a1_nw_bgate = "Armory Floor 4 NW Vault"
a1_w_se_bgate = "Armory Floor 4 West SE Vault"
a1_w_sw_bgate = "Armory Floor 4 West SW Vault"
a1_red_spikes = "Armory Floor 4 Red Spikes"
a1_sw_spikes = "Armory Floor 4 SW Spikes"
a1_from_a2 = "Armory Floor 4 From Floor 5"

a2_start = "Armory Floor 5 Start"
a2_s_bgate = "Armory Floor 5 South Bronze Gate"
a2_ne = "Armory Floor 5 NE"
a2_ne_l_bgate = "Armory Floor 5 NE Left Bronze Gate"
a2_ne_r_bgate = "Armory Floor 5 NE Right Bronze Gate"
a2_e = "Armory Floor 5 East"
a2_e_bgate = "Armory Floor 5 East Bronze Gate"
a2_nw = "Armory Floor 5 NW"
a2_blue_spikes = "Armory Floor 5 Blue Spikes"
a2_bonus_return = "Armory Floor 5 Bonus Return"

n2_start = "Bonus 2 Start"
n2_m = "Bonus 2 Center Area"
n2_n = "Bonus 2 North Room"
n2_e = "Bonus 2 East Room"
n2_s = "Bonus 2 South Room"
n2_w = "Bonus 2 West Room"
n2_nw = "Bonus 2 NW Room"
n2_ne = "Bonus 2 NE Room"

a3_main = "Armory Floor 6"
a3_knife_puzzle_reward = "Armory Floor 6 Knife Puzzle Reward"
a3_pyramids_s_bgate = "Armory Floor 6 South Pyramids South Bronze Gate"

b2_start = "Boss 2 Start"
b2_arena = "Boss 2 Arena"
b2_defeated = "Boss 2 Defeated"

r1_start = "Archives Floor 7 Start"
r1_start_wall = "Archives Floor 7 Start In Wall"
r1_se_wall = "Archives Floor 7 SE In Wall"
r1_e = "Archives Floor 7 East"
r1_e_s_bgate = "Archives Floor 7 East Southernmost Bronze Gate"
r1_e_n_bgate = "Archives Floor 7 East North Bronze Gates"
r1_e_sgate = "Archives Floor 7 East Silver Gate"
r1_ne_ggate = "Archives Floor 7 East Gold Gate"
r1_nw = "Archives Floor 7 NW"
r1_nw_hidden = "Archives Floor 7 NW Hidden Room"
r1_sw = "Archives Floor 7 SW"
r1_w_sgate = "Archives Floor 7 West Silver Gate"

r2_start = "Archives Floor 8 Start"
r2_bswitch = "Archives Floor 8 Boss Switch"
r2_m = "Archives Floor 8 Main"
r2_nw = "Archives Floor 8 NW"
r2_s = "Archives Floor 8 South"
r2_e = "Archives Floor 8 East"
r2_from_r3 = "Archives Floor 8 From Floor 9"

r3_main = "Archives Floor 9 Main Area"
r3_e_ggate = "Archives Floor 9 East Gold Gate"
r3_w_ggate = "Archives Floor 9 West Gold Gate"
r3_boss_switch = "Archives Floor 9 Boss Switch Room"
r3_sw_bgate = "Archives Floor 9 Open SW Bronze Gate"
r3_l_shop_sgate = "Archives Floor 9 South Shops Left Silver Gate"
r3_r_shop_sgate = "Archives Floor 9 South Shops Right Silver Gate"

n3_main = "Bonus 3 Main"
n3_tp_room = "Bonus 3 Teleport Room"

b3_start = "Boss 3 Start"
b3_arena = "Boss 3 Arena"
b3_defeated = "Boss 3 Defeated"

c1_start = "Chambers Floor 10 East"
c1_n_spikes = "Chambers Floor 10 North Spikes"
c1_se_spikes = "Chambers Floor 10 SE Spikes"
c1_shop = "Chambers Floor 10 Shop"
c1_w = "Chambers Floor 10 West"
c1_sgate = "Chambers Floor 10 Silver Gate"
c1_prison_stairs = "Chambers Floor 10 Prison Stairs"
c1_s_bgate = "Chambers Floor 10 South Bronze Gate Room"
c1_ledge = "Chambers Floor 10 Ledge"
c1_tp_island = "Chambers Floor 10 Teleport Island"

pstart_start = "Prison Return Start"
pstart_puzzle = "Prison Return Puzzle"

c2_main = "Chambers Floor 11 South"
c2_sw_wall = "Chambers Floor 11 SW In Wall"
c2_w_spikes = "Chambers Floor 11 West Spikes"
c2_e_shops_1 = "Chambers Floor 11 Bottom East Shop"
c2_e_shops_2 = "Chambers Floor 11 Top East Shop"
c2_w_shops_1 = "Chambers Floor 11 Left West Shop"
c2_w_shops_2 = "Chambers Floor 11 Middle West Shop"
c2_w_shops_3 = "Chambers Floor 11 Right West Shop"
c2_n = "Chambers Floor 11 North"
c2_n_wall = "Chambers Floor 11 North In Wall"
c2_bonus_return = "Chambers Floor 11 Bonus Return"
c2_c3_tp = "Chambers Floor 11 Teleport from Floor 12"
c2_n_shops = "Chambers Floor 11 North Secret Shops"
c2_tp_island = "Chambers Floor 11 Teleport Island"

n4_main = "Bonus 4 Main"
n4_nw = "Bonus 4 NW Room"
n4_w = "Bonus 4 West Room"
n4_e = "Bonus 4 East Room"

c3_start = "Chambers Floor 12 Right Entrance"
c3_rspike_switch = "Chambers Floor 12 Red Spikes Switch"
c3_rspikes = "Chambers Floor 12 Red Spikes"
c3_s_bgate = "Chambers Floor 12 Southernmost Bronze Gate"
c3_m_wall = "Chambers Floor 12 Middle in Wall"
c3_m_shop = "Chambers Floor 12 Middle Shop"
c3_m_tp = "Chambers Floor 12 Middle Teleport"
c3_nw = "Chambers Floor 12 NW"
c3_sw_hidden = "Chambers Floor 12 SW Hidden Hall"
c3_fire_floor = "Chambers Floor 12 Fire Floor"
c3_fire_floor_tp = "Chambers Floor 12 Fire Floor Teleport"
c3_c2_tp = "Chambers Floor 12 Teleport From Floor 11"
c3_se_hidden = "Chambers Floor 12 SE Hidden Room"
c3_light_bridge = "Chambers Floor 12 Light Bridge"

b4_start = "Dragon Start"
b4_defeated = "Dragon Defeated"

e1_main = "Chamber Floors Escape"
e2_main = "Archive Floors Escape"
e3_main = "Armory Floors Escape"
e4_main = "Prison Floors Escape"

escaped = "Escaped Castle Hammerwatch"

get_planks = "Collect All Planks"
