# Item Names
empty = "Empty"
bonus_chest = "Bonus Chest"
bonus_key = "Bonus Key"
chest_blue = "Blue Chest"
chest_green = "Green Chest"
chest_purple = "Purple Chest"
chest_red = "Red Chest"
chest_wood = "Wood Chest"
vendor_coin = "Vendor Coin"
plank = "Strange Plank"
apple = "Apple"
orange = "Orange"
steak = "Steak"
fish = "Fish"
mana_1 = "Mana Shard"
mana_2 = "Mana Orb"
key_bronze = "Bronze Key"
key_silver = "Silver Key"
key_gold = "Gold Key"
mirror = "Mirror"
ore = "Ore"
key_teleport = "Rune Key"
ankh = "1-Up Ankh"
ankh_5up = "5-Up Ankh"
ankh_7up = "7-Up Ankh"
powerup_7up = "7-Up Ankh"
potion_damage = "Damage Potion"
potion_rejuvenation = "Rejuvenation Potion"
potion_invulnerability = "Invulnerability Potion"
stat_upgrade_damage = "Damage Upgrade"
stat_upgrade_defense = "Defense Upgrade"
stat_upgrade_health = "Health Upgrade"
stat_upgrade_mana = "Mana Upgrade"
stat_upgrade = "Random Stat Upgrade"
diamond = "Diamond"
diamond_red = "Red Diamond"
diamond_small = "Small Diamond"
diamond_small_red = "Small Red Diamond"
valuable_1 = "Copper Coin"
valuable_2 = "Copper Coins"
valuable_3 = "Copper Coin Pile"
valuable_4 = "Silver Coin"
valuable_5 = "Silver Coins"
valuable_6 = "Silver Coin Pile"
valuable_7 = "Gold Coin"
valuable_8 = "Gold Coins"
valuable_9 = "Gold Coin Pile"

# Quest Item Names
pan = "Frying Pan"
lever = "Pumps Lever"
pickaxe = "Pickaxe"

pan_fragment = "Frying Pan Fragment"
lever_fragment = "Pumps Lever Fragment"
pickaxe_fragment = "Pickaxe Fragment"

# Special Item Names
sonic_ring = "Gold Ring"
serious_health = "Serious Health Upgrade"

# Custom Item Names
key_bronze_big = "Big Bronze Key"

key_bronze_prison = "Prison Bronze Key"
key_silver_prison = "Prison Silver Key"
key_gold_prison = "Prison Gold Key"
key_bonus_prison = "Prison Bonus Key"
key_bronze_armory = "Armory Bronze Key"
key_silver_armory = "Armory Silver Key"
key_gold_armory = "Armory Gold Key"
key_bonus_armory = "Armory Bonus Key"
key_bronze_archives = "Archives Bronze Key"
key_silver_archives = "Archives Silver Key"
key_gold_archives = "Archives Gold Key"
key_bonus_archives = "Archives Bonus Key"
key_bronze_chambers = "Chambers Bronze Key"
key_silver_chambers = "Chambers Silver Key"
key_gold_chambers = "Chambers Gold Key"
key_bonus_chambers = "Chambers Bonus Key"
key_bronze_big_prison = "Prison Big Bronze Key"
key_bronze_big_armory = "Armory Big Bronze Key"
key_bronze_big_archives = "Archives Big Bronze Key"
key_bronze_big_chambers = "Chambers Big Bronze Key"

# Special Generation stuff
secret = "Secret"
puzzle = "Puzzle"
miniboss_stat_upgrade = "Miniboss Stat Upgrade"
loot_tower = "Tower Loot"
loot_flower = "Flower Loot"
loot_mini_flower = "Mini Flower Loot"

# Trap Items
trap_bomb = "Bomb Trap"
trap_confuse = "Confuse Trap"
trap_mana = "Mana Drain Trap"
trap_poison = "Poison Trap"
trap_frost = "Frost Trap"
trap_fire = "Fire Trap"

# Event Names
ev_victory = "Victory"

ev_castle_p2_switch = "Prison Floor 2 Switch"
ev_castle_c2_n_shops_switch = "Chambers Floor 11 North Shops Switch"
ev_castle_c2_n_tp_button = "Chambers Floor 11 North Teleport Button"
ev_castle_c3_rspikes_switch = "Chambers Floor 12 Red Spikes Switch"
ev_castle_c3_sw_hidden_switch = "Chambers Floor 12 SW Hidden Hall Switch"
ev_castle_b1_boss_switch = "Prison Boss Switch"
ev_castle_b2_boss_switch = "Armory Boss Switch"
ev_castle_b3_boss_switch = "Archives Boss Switch"
ev_castle_b4_boss_switch = "Chambers Boss Switch"

ev_open_temple_entrance_shortcut = "Open Temple Entrance Shortcut"
ev_krilith_defeated = "Krilith Defeated"
ev_pof_switch = "Activate PoF Switch"
ev_solar_node = "Activate Solar Node"
ev_t2_bridge_switch = "Temple Floor 2 Bridge Switch"
ev_pof_1_unlock_exit = "PoF Level 1 Unlock Exit"
ev_pof_2_unlock_exit = "PoF Level 2 Unlock Exit"
ev_pof_complete = "PoF Complete"
