# Item Names
empty = "Empty"
bonus_chest = "Bonus Chest"
bonus_key = "Bonus Key"
chest_blue = "Blue Chest"
chest_green = "Green Chest"
chest_purple = "Purple Chest"
chest_red = "Red Chest"
chest_wood = "Wood Chest"
vendor_coin = "Vendor Coin"
plank = "Strange Plank"
apple = "Apple"
orange = "Orange"
steak = "Steak"
fish = "Fish"
mana_1 = "Mana Shard"
mana_2 = "Mana Orb"
key_bronze = "Bronze Key"
key_silver = "Silver Key"
key_gold = "Gold Key"
mirror = "Mirror"
ore = "Ore"
key_teleport = "Rune Key"
ankh = "1-Up Ankh"
ankh_5up = "5-Up Ankh"
ankh_7up = "7-Up Ankh"
powerup_7up = "7-Up Ankh"
potion_damage = "Damage Potion"
potion_rejuvenation = "Rejuvenation Potion"
potion_invulnerability = "Invulnerability Potion"
stat_upgrade_damage = "Damage Upgrade"
stat_upgrade_defense = "Defense Upgrade"
stat_upgrade_health = "Health Upgrade"
stat_upgrade_mana = "Mana Upgrade"
stat_upgrade = "Random Stat Upgrade"
diamond = "Diamond"
diamond_red = "Red Diamond"
diamond_small = "Small Diamond"
diamond_small_red = "Small Red Diamond"

# Quest Item Names
pan = "Frying Pan"
lever = "Pumps Lever"
pickaxe = "Pickaxe"

pan_fragment = "Frying Pan Fragment"
lever_fragment = "Pumps Lever Fragment"
pickaxe_fragment = "Pickaxe Fragment"

# Special Item Names
sonic_ring = "Gold Ring"
serious_health = "Serious Health Upgrade"

# Special Generation stuff
secret = "Secret"
puzzle = "Puzzle"

# Trap Items
trap_bomb = "Bomb Trap"
trap_confuse = "Confuse Trap"
trap_mana = "Mana Drain Trap"
trap_poison = "Poison Trap"
trap_frost = "Frost Trap"
trap_fire = "Fire Trap"

# Event Names
ev_victory = "Victory"

ev_castle_b1_boss_switch = "Prison Boss Switch"
ev_castle_p2_switch = "Prison Floor 2 Switch"
ev_castle_b2_boss_switch = "Armory Boss Switch"
ev_castle_b3_boss_switch = "Archives Boss Switch"
ev_castle_b4_boss_switch = "Castle Boss Switch"

ev_open_temple_entrance_shortcut = "Open Temple Entrance Shortcut"
ev_krilith_defeated = "Krilith Defeated"
ev_pof_switch = "Activate PoF Switch"
ev_solar_node = "Activate Solar Node"
ev_t2_bridge_switch = "Temple Floor 2 Bridge Switch"
ev_pof_complete = "PoF Complete"
