from typing import Dict, List
from . import castle_region_names 
from . import temple_region_names
from .shop_location_names import shop_class_location_names
from ..regions import castle_regions, temple_regions, p3_portal_boss_rune_room_regions
from ..locations import all_locations

location_groups = {

}
castle_region_groups: Dict[str, List[str]] = {
    # Castle
    "Prison Floor 1 Locations": [
        castle_region_names.p1_start,
        castle_region_names.p1_nw,
        castle_region_names.p1_secret,
        castle_region_names.p1_nw_left,
        castle_region_names.p1_s,
        castle_region_names.p1_sw_secret,
        castle_region_names.p1_sw_bronze_gate,
        castle_region_names.p1_e,
        castle_region_names.p1_m_bronze_gate,
        castle_region_names.p1_from_p2,
        castle_region_names.p1_from_p3_n,
        castle_region_names.p1_from_p3_s,
        castle_region_names.pstart_start,
        castle_region_names.pstart_puzzle_island,
        castle_region_names.pstart_puzzle,
    ],
    "Prison Floor 2 Locations": [
        castle_region_names.p2_start,
        castle_region_names.p2_m,
        castle_region_names.p2_p1_return,
        castle_region_names.p2_n,
        castle_region_names.p2_ne_secret,
        castle_region_names.p2_puzzle,
        castle_region_names.p2_spike_puzzle_left,
        castle_region_names.p2_spike_puzzle_top,
        castle_region_names.p2_spike_puzzle_bottom,
        castle_region_names.p2_red_switch,
        castle_region_names.p2_e_bronze_gate,
        castle_region_names.p2_e_save,
        castle_region_names.p2_s,
        castle_region_names.p2_gg_room_reward,
        castle_region_names.p2_e_bronze_gate_2,
        castle_region_names.p2_m_bronze_gate,
        castle_region_names.p2_se_bronze_gate,
        castle_region_names.p2_w_secrets,
        castle_region_names.p2_w_treasure,
        castle_region_names.p2_w_treasure_tp,
        castle_region_names.p2_tp_puzzle,
        castle_region_names.p2_end,
    ],
    "Prison Floor 3 Locations": [
        castle_region_names.p3_start_door,
        castle_region_names.p3_start,
        castle_region_names.p3_start_shop,
        castle_region_names.p3_start_secret,
        castle_region_names.p3_nw_closed_room,
        castle_region_names.p3_nw_n_bronze_gate,
        castle_region_names.p3_nw_s_bronze_gate,
        castle_region_names.p3_silver_gate,
        castle_region_names.p3_n_gold_gate,
        castle_region_names.p3_rspikes,
        castle_region_names.p3_rspikes_room,
        castle_region_names.p3_bspikes,
        castle_region_names.p3_bonus,
        castle_region_names.p3_bonus_return,
        castle_region_names.p3_se_secret,
        castle_region_names.p3_s_bronze_gate,
        castle_region_names.p3_spikes_s,
        castle_region_names.p3_m_secret,
        castle_region_names.p3_sw,
        castle_region_names.p3_boss,
        castle_region_names.p3_s_gold_gate,
        castle_region_names.p3_exit_s,
        castle_region_names.p3_arrow_hall_secret,
        castle_region_names.p3_hidden_arrow_hall,
        castle_region_names.p3_hidden_s_hall_secret,
    ],
    "Armory Floor 4 Locations": [
        castle_region_names.a1_start,
        castle_region_names.a1_start_shop_w,
        castle_region_names.a1_start_shop_m,
        castle_region_names.a1_start_shop_e,
        castle_region_names.a1_start_shop_s,
        castle_region_names.a1_start_shop_nw,
        castle_region_names.a1_se,
        castle_region_names.a1_e,
        castle_region_names.a1_ne_cache,
        castle_region_names.a1_e_sw_bgate,
        castle_region_names.a1_e_s_bgate,
        castle_region_names.a1_e_se_bgate,
        castle_region_names.a1_e_e_bgate,
        castle_region_names.a1_e_ne_bgate,
        castle_region_names.a1_rune_room,
        castle_region_names.a1_se_cache,
        castle_region_names.a1_n_bgate,
        castle_region_names.a1_tp_n,
        castle_region_names.a1_w,
        castle_region_names.a1_n_secret,
        castle_region_names.a1_w_ne_bgate,
        castle_region_names.a1_nw_bgate,
        castle_region_names.a1_w_se_bgate,
        castle_region_names.a1_w_sw_bgate,
        castle_region_names.a1_w_sw_bgate_1,
        castle_region_names.a1_red_spikes,
        castle_region_names.a1_sw_spikes,
        castle_region_names.a1_puzzle,
        castle_region_names.a1_from_a2,
        castle_region_names.a1_boss,
    ],
    "Armory Floor 5 Locations": [
        castle_region_names.a2_start,
        castle_region_names.a2_tp_sw,
        castle_region_names.a2_tp_se,
        castle_region_names.a2_sw_bgate,
        castle_region_names.a2_s_bgate,
        castle_region_names.a2_se_bgate,
        castle_region_names.a2_s_save_bgate,
        castle_region_names.a2_s_secret,
        castle_region_names.a2_ne,
        castle_region_names.a2_ne_m_bgate,
        castle_region_names.a2_ne_l_bgate,
        castle_region_names.a2_ne_r_bgate,
        castle_region_names.a2_ne_b_bgate,
        castle_region_names.a2_ne_save_bgate,
        castle_region_names.a2_tp_ne,
        castle_region_names.a2_ne_secret,
        castle_region_names.a2_e,
        castle_region_names.a2_e_bgate,
        castle_region_names.a2_nw,
        castle_region_names.a2_blue_spikes,
        castle_region_names.a2_blue_spikes_tp,
        castle_region_names.a2_bonus_return,
        castle_region_names.a2_puzzle,
        castle_region_names.a2_to_a3,
    ],
    "Armory Floor 6 Locations": [
        castle_region_names.a3_start,
        castle_region_names.a3_main,
        castle_region_names.a3_tp,
        castle_region_names.a3_knife_puzzle_reward,
        castle_region_names.a3_knife_reward_2,
        castle_region_names.a3_secret,
        castle_region_names.a3_from_a2,
        castle_region_names.a3_from_a2_wall,
        castle_region_names.a3_nw_stairs,
        castle_region_names.a3_w_b_bgate,
        castle_region_names.a3_w_b_bgate_tp,
        castle_region_names.a3_w_t_bgate,
        castle_region_names.a3_w_r_bgate,
        castle_region_names.a3_n_l_bgate,
        castle_region_names.a3_n_r_bgate,
        castle_region_names.a3_e_l_bgate,
        castle_region_names.a3_e_r_bgate,
    ],
    "Archives Floor 7 Locations": [
        castle_region_names.r1_start,
        castle_region_names.r1_se_ggate,
        castle_region_names.r1_start_wall,
        castle_region_names.r1_se_wall,
        castle_region_names.r1_e,
        castle_region_names.r1_e_s_bgate,
        castle_region_names.r1_e_n_bgate,
        castle_region_names.r1_e_sgate,
        castle_region_names.r1_ne_ggate,
        castle_region_names.r1_nw,
        castle_region_names.r1_puzzle,
        castle_region_names.r1_nw_hidden,
        castle_region_names.r1_nw_ggate,
        castle_region_names.r1_sw,
        castle_region_names.r1_w_wall,
        castle_region_names.r1_w_sgate,
        castle_region_names.r1_sw_ggate,
        castle_region_names.r1_exit_l,
        castle_region_names.r1_exit_r,
    ],
    "Archives Floor 8 Locations": [
        castle_region_names.r2_start,
        castle_region_names.r2_bswitch,
        castle_region_names.r2_m,
        castle_region_names.r2_nw,
        castle_region_names.r2_n,
        castle_region_names.r2_sgate,
        castle_region_names.r2_s,
        castle_region_names.r2_spike_island,
        castle_region_names.r2_sw_bridge,
        castle_region_names.r2_sw_secret,
        castle_region_names.r2_puzzle_room,
        castle_region_names.r2_puzzle,
        castle_region_names.r2_w,
        castle_region_names.r2_e,
        castle_region_names.r2_from_r3,
        castle_region_names.r2_ne_cache,
        castle_region_names.r2_w_bgate,
        castle_region_names.r2_ggate,
        castle_region_names.r2_exit,
    ],
    "Archives Floor 9 Locations": [
        castle_region_names.r3_main,
        castle_region_names.r3_ne_room,
        castle_region_names.r3_s_room,
        castle_region_names.r3_e_ggate,
        castle_region_names.r3_w_ggate,
        castle_region_names.r3_se_secret,
        castle_region_names.r3_boss_switch,
        castle_region_names.r3_rune_room,
        castle_region_names.r3_simon_says,
        castle_region_names.r3_bonus,
        castle_region_names.r3_sw_bgate,
        castle_region_names.r3_sw_bgate_secret,
        castle_region_names.r3_sw_wall_r,
        castle_region_names.r3_sw_wall_l,
        castle_region_names.r3_passage_start,
        castle_region_names.r3_passage,
        castle_region_names.r3_passage_room_1,
        castle_region_names.r3_passage_mid,
        castle_region_names.r3_passage_room_2,
        castle_region_names.r3_passage_spikes,
        castle_region_names.r3_passage_end,
        castle_region_names.r3_nw_tp,
        castle_region_names.r3_l_shop_sgate,
        castle_region_names.r3_r_shop_sgate,
        castle_region_names.r3_bonus_return,
        castle_region_names.r3_bonus_return_bridge,
        castle_region_names.r3_exit,
        castle_region_names.r3_boss,
    ],
    "Chambers Floor 10 Locations": [
        castle_region_names.c1_start,
        castle_region_names.c1_n_spikes,
        castle_region_names.c1_se_spikes,
        castle_region_names.c1_shop,
        castle_region_names.c1_w,
        castle_region_names.c1_sgate,
        castle_region_names.c1_prison_stairs,
        castle_region_names.c1_s_bgate,
        castle_region_names.c1_ledge,
        castle_region_names.c1_tp_island,
    ],
    "Chambers Floor 11 Locations": [
        castle_region_names.c2_main,
        castle_region_names.c2_sw_wall,
        castle_region_names.c2_w_wall,
        castle_region_names.c2_e_wall,
        castle_region_names.c2_w_spikes,
        castle_region_names.c2_e_shops_1,
        castle_region_names.c2_e_shops_2,
        castle_region_names.c2_w_shops_1,
        castle_region_names.c2_w_shops_2,
        castle_region_names.c2_w_shops_3,
        castle_region_names.c2_puzzle_room,
        castle_region_names.c2_puzzle,
        castle_region_names.c2_n,
        castle_region_names.c2_exit_bgate,
        castle_region_names.c2_n_wall,
        castle_region_names.c2_bonus,
        castle_region_names.c2_bonus_return,
        castle_region_names.c2_c3_tp,
        castle_region_names.c2_n_shops,
        castle_region_names.c2_tp_island,
        castle_region_names.c2_boss,
    ],
    "Chambers Floor 12 Locations": [
        castle_region_names.c3_start,
        castle_region_names.c3_rspike_switch,
        castle_region_names.c3_rspikes,
        castle_region_names.c3_s_bgate,
        castle_region_names.c3_m_wall,
        castle_region_names.c3_m_shop,
        castle_region_names.c3_m_tp,
        castle_region_names.c3_nw,
        castle_region_names.c3_sw_hidden,
        castle_region_names.c3_fire_floor,
        castle_region_names.c3_fire_floor_tp,
        castle_region_names.c3_c2_tp,
        castle_region_names.c3_se_hidden,
        castle_region_names.c3_light_bridge,
        castle_region_names.c3_easter_egg,
    ],
    "Prison Bonus Locations": [
        castle_region_names.n1_start,
        castle_region_names.n1_room1,
        castle_region_names.n1_room2,
        castle_region_names.n1_room2_secret,
        castle_region_names.n1_room2_unlock,
        castle_region_names.n1_room3,
        castle_region_names.n1_room3_unlock,
        castle_region_names.n1_room3_hall,
        castle_region_names.n1_room4,
        castle_region_names.n1_exit,
    ],
    "Armory Bonus Locations": [
        castle_region_names.n2_start,
        castle_region_names.n2_m,
        castle_region_names.n2_n,
        castle_region_names.n2_e,
        castle_region_names.n2_s,
        castle_region_names.n2_w,
        castle_region_names.n2_nw,
        castle_region_names.n2_ne,
        castle_region_names.n2_se,
        castle_region_names.n2_exit,
    ],
    "Archives Bonus Locations": [
        castle_region_names.n3_main,
        castle_region_names.n3_tp_room,
    ],
    "Chambers Bonus Locations": [
        castle_region_names.n4_main,
        castle_region_names.n4_nw,
        castle_region_names.n4_w,
        castle_region_names.n4_e,
        castle_region_names.n4_exit,
    ],
    "Queen Locations": [
        castle_region_names.b1_start,
        castle_region_names.b1_arena,
        castle_region_names.b1_defeated,
        castle_region_names.b1_exit,
    ],
    "Knight Locations": [
        castle_region_names.b2_start,
        castle_region_names.b2_arena,
        castle_region_names.b2_defeated,
        castle_region_names.b2_exit,
    ],
    "Lich Locations": [
        castle_region_names.b3_start,
        castle_region_names.b3_arena,
        castle_region_names.b3_defeated,
        castle_region_names.b3_exit,
    ],
    "Worldfire Locations": [
        castle_region_names.b4_start,
        castle_region_names.b4_defeated,
    ],
    "Escape Locations": [
        castle_region_names.e1_main,
        castle_region_names.e2_main,
        castle_region_names.e3_main,
        castle_region_names.e4_main,
    ],
}
temple_region_groups: Dict[str, List[str]] = {
    "Temple Outside Locations": [
        temple_region_names.hub_main,
        temple_region_names.hub_rocks,
        temple_region_names.hub_pyramid_of_fear,
    ],
    "Cave Level 3 Locations": [
        temple_region_names.cave_3_main,
        temple_region_names.c3_main_secrets,
        temple_region_names.c3_e,
        temple_region_names.c3_e_guard_secret,
        temple_region_names.cave_3_fall,
        temple_region_names.cave_3_portal,
        temple_region_names.cave_3_fields,
        temple_region_names.c3_e_water,
        temple_region_names.cave_3_secret,
        temple_region_names.c3_puzzle,
    ],
    "Cave Level 2 Locations": [
        temple_region_names.cave_2_main,
        temple_region_names.c2_main_secrets,
        temple_region_names.c2_red_bridge,
        temple_region_names.c2_green_bridge,
        temple_region_names.c2_sw,
        temple_region_names.c2_double_bridge,
        temple_region_names.c2_sw_secrets,
        temple_region_names.cave_2_pumps,
        temple_region_names.c2_puzzle,
    ],
    "Cave Level 1 Locations": [
        temple_region_names.cave_1_main,
        temple_region_names.c1_main_secrets,
        temple_region_names.cave_1_blue_bridge,
        temple_region_names.c1_blue_bridge_secrets,
        temple_region_names.cave_1_red_bridge,
        temple_region_names.c1_red_bridge_secrets,
        temple_region_names.cave_1_green_bridge,
        temple_region_names.c1_storage_island,
        temple_region_names.c1_secret_hall,
        temple_region_names.cave_1_pumps,
        temple_region_names.cave_1_temple,
        temple_region_names.c1_n_puzzle,
        temple_region_names.c1_e_puzzle,
    ],
    "Subterranean Passage Locations": [
        temple_region_names.passage_entrance,
        temple_region_names.passage_entrance_secret,
        temple_region_names.passage_mid,
        temple_region_names.passage_mid_secrets,
        temple_region_names.passage_end,
        temple_region_names.passage_end_secret,
        temple_region_names.passage_puzzle,
    ],
    "Temple Entrance Locations": [
        temple_region_names.temple_entrance,
        temple_region_names.temple_entrance_back,
    ],
    "Temple Floor 1 Locations": [
        temple_region_names.t1_main,
        temple_region_names.t1_main_secret,
        temple_region_names.t1_sw_sdoor,
        temple_region_names.t1_w,
        temple_region_names.t1_runway_halls,
        temple_region_names.t1_node_1,
        temple_region_names.t1_node_2,
        temple_region_names.t1_sun_turret,
        temple_region_names.t1_ice_turret,
        temple_region_names.t1_n_of_ice_turret,
        temple_region_names.t1_s_of_ice_turret,
        temple_region_names.t1_east,
        temple_region_names.t1_e_secret,
        temple_region_names.t1_sun_block_hall,
        temple_region_names.t1_telarian,
        temple_region_names.t1_jail_e,
        temple_region_names.t1_ne_hall,
        temple_region_names.t1_telarian_melt_ice,
        temple_region_names.t1_ice_chamber_melt_ice,
        temple_region_names.t1_w_puzzle,
        temple_region_names.t1_e_puzzle,
    ],
    "Temple Floor 2 Locations": [
        temple_region_names.t2_main,
        temple_region_names.t2_main_secrets,
        temple_region_names.t2_melt_ice,
        temple_region_names.t2_w_ice_gate,
        temple_region_names.t2_e_ice_gate,
        temple_region_names.t2_n_gate,
        temple_region_names.t2_n_gate_secret,
        temple_region_names.t2_s_gate,
        temple_region_names.t2_s_gate_secret,
        temple_region_names.t2_n_node,
        temple_region_names.t2_s_node,
        temple_region_names.t2_jail_sw,
        temple_region_names.t2_sdoor_gate,
        temple_region_names.t2_pof,
        temple_region_names.t2_pof_spikes,
        temple_region_names.t2_jail_s,
        temple_region_names.t2_nw_button_gate,
        temple_region_names.t2_boulder_room,
        temple_region_names.t2_n_hidden_hall,
        temple_region_names.t2_jones_hall,
        temple_region_names.t2_ornate,
        temple_region_names.t2_ornate_t3,
        temple_region_names.t2_ornate_gate,
        temple_region_names.t2_light_bridge_w,
        temple_region_names.t2_light_bridges_s,
        temple_region_names.t2_light_bridges_se,
        temple_region_names.t2_portal_gate,
        temple_region_names.t2_n_puzzle,
        temple_region_names.t2_nw_puzzle,
        temple_region_names.t2_e_puzzle,
        temple_region_names.t2_sw_puzzle,
    ],
    "Temple Floor 3 Locations": [
        temple_region_names.t3_main,
        temple_region_names.t3_blockade_s,
        temple_region_names.t3_s_gate,
        temple_region_names.t3_n_node_blocks,
        temple_region_names.t3_s_node_blocks_1,
        temple_region_names.t3_s_node_blocks_2,
        temple_region_names.t3_s_node,
        temple_region_names.t3_n_node,
        temple_region_names.t3_gates,
        temple_region_names.t3_puzzle_room,
        temple_region_names.t3_boss_fall_1,
        temple_region_names.t3_boss_fall_2,
        temple_region_names.t3_boss_fall_3,
        temple_region_names.t3_puzzle,
    ],
    "Pyramid of Fear Locations": [
        temple_region_names.pof_1_main,
        temple_region_names.pof_1_s_halls,
        temple_region_names.pof_1_sw_room,
        temple_region_names.pof_1_se_room,
        temple_region_names.pof_1_se_room_top,
        temple_region_names.pof_1_sw_gate,
        temple_region_names.pof_1_center,
        temple_region_names.pof_1_nw,
        temple_region_names.pof_1_n_room,
        temple_region_names.pof_1_exit_hall,
        temple_region_names.pof_1_gate_2,
        temple_region_names.pof_2_entrance,
        temple_region_names.pof_2_entrance_blocks,
        temple_region_names.pof_2_main,
        temple_region_names.pof_2_n,
        temple_region_names.pof_2_puzzle,
        temple_region_names.pof_2_exit,
        temple_region_names.pof_3_start,
        temple_region_names.pof_3_main,
        temple_region_names.pof_puzzle,
    ],
    "Dune Sharks Arena Locations": [
        temple_region_names.boss_1_entrance,
        temple_region_names.b1_back,
        temple_region_names.b1_back_secret,
        temple_region_names.boss_1_arena,
        temple_region_names.boss_1_defeated,
    ],
    "Krilith Arena Locations": [
        temple_region_names.boss2_main,
        temple_region_names.boss2_defeated,
    ],
    "Sha'Rand Arena Locations": [
        temple_region_names.b3_main,
        temple_region_names.b3_platform_1,
        temple_region_names.b3_platform_2,
        temple_region_names.b3_platform_3,
        temple_region_names.b3_defeated,
    ],
}
# location_type_groups = {
#
# }
# loc_type_groups = {
#     LocType.Recovery: "Recovery Locations",
#     LocType.Puzzle: "Puzzle Locations",
#     LocType.Secret: "Secret Locations",
#     LocType.Bonus: "Bonus Locations",
#     LocType.EnemyLoot: "Enemy Loot Locations",
#     LocType.Button: "Button Locations",
# }
# for loc_type, name in loc_type_groups.items():
#     location_type_groups[loc_type] = set()
#
# for loc_name, data in castle_locations.items():
#     for loc_type in loc_type_groups.keys():
#         if (data.loc_type & loc_type) == loc_type:
#             location_type_groups[loc_type].add(loc_name)
# for loc_name, data in temple_locations.items():
#     for loc_type in loc_type_groups.keys():
#         if (data.loc_type & loc_type) == loc_type:
#             location_type_groups[loc_type].add(loc_name)
# for loc_type, loc_list in location_type_groups.items():
#     location_groups[loc_type_groups[loc_type]] = loc_list

for _player_class, shop_type_locs in shop_class_location_names.items():
    group_name = _player_class.name + " Shop Locations"
    location_groups[group_name] = set()
    for shop_tier_names in shop_type_locs.values():
        for shop_tier in shop_tier_names:
            location_groups[group_name].update(shop_tier)

for group_name, region_list in castle_region_groups.items():
    location_groups[group_name] = set()
    for region in region_list:
        if region not in castle_regions:
            continue
        region_locs = castle_regions[region]
        if region_locs is None:
            continue
        location_groups[group_name].update([loc for loc in region_locs if loc in all_locations])
location_groups["Prison Floor 3 Locations"].update(p3_portal_boss_rune_room_regions[castle_region_names.p3_portal_from_p1])
for group_name, region_list in temple_region_groups.items():
    location_groups[group_name] = set()
    for region in region_list:
        if region not in temple_regions:
            continue
        region_locs = temple_regions[region]
        if region_locs is None:
            continue
        location_groups[group_name].update([loc for loc in region_locs if loc in all_locations])
