# Pickup Names
# Hub
hub_front_of_pof = "Dunes Front of Pyramid of Fear"
hub_behind_temple_entrance = "Dunes Behind Temple Entrance"

hub_behind_shops = "Dunes Behind Shops"
hub_on_rock = "Dunes on Rock"
hub_west_pyramid = "Dunes West Past Rocks By Pyramid"
hub_rocks_south = "Dunes South Behind Rock"
hub_field_south = "Dunes Field South"
hub_field_nw = "Dunes Field NW"
hub_field_north = "Dunes Field North"

hub_pof_reward = "Dunes Pyramid of Fear Reward"

# Cave Level 3
cave3_squire = "Cave Level 3 Squire"
cave3_guard = "Cave Level 3 Guard"
cave3_n = "Cave Level 3 N"
cave3_nw = "Cave Level 3 NW"
cave3_ne = "Cave Level 3 NE"
cave3_se = "Cave Level 3 SE"
cave3_m = "Cave Level 3 Center"
cave3_half_bridge = "Cave Level 3 Half Bridge"
cave3_trapped_guard = "Cave Level 3 Trapped Guard Room"
cave3_outside_guard = "Cave Level 3 Outside Trapped Guard Room"
cave3_secret_n = "Cave Level 3 North Secret Room"
cave3_secret_nw = "Cave Level 3 NW Secret Room"
cave3_secret_s = "Cave Level 3 South Secret Room"

cave3_fall_nw = "Cave Level 3 Fall NW"
cave3_fall_ne = "Cave Level 3 Fall NE"
cave3_fall_sw = "Cave Level 3 Fall SW"
cave3_fall_se = "Cave Level 3 Fall SE"

cave3_fields_r = "Cave Level 3 Fields East"
cave3_captain = "Cave Level 3 Captain"
cave3_captain_dock = "Cave Level 3 Captain Dock"

cave3_portal_puzzle = "Cave Level 3 Portal Puzzle"  #
cave3_portal_l = "Cave Level 3 Portal Left"
cave3_portal_r = "Cave Level 3 Portal Right"

cave3_secret_1 = "Cave Level 3 Secret 1"
cave3_secret_2 = "Cave Level 3 Secret 2"
cave3_secret_3 = "Cave Level 3 Secret 3"
cave3_secret_4 = "Cave Level 3 Secret 4"
cave3_secret_5 = "Cave Level 3 Secret 5"
cave3_secret_6 = "Cave Level 3 Secret 6"
cave3_secret_7 = "Cave Level 3 Secret 7"
cave3_secret_8 = "Cave Level 3 Secret 8"
cave3_secret_9 = "Cave Level 3 Secret 9"
cave3_secret_10 = "Cave Level 3 Secret 10"
cave3_secret_11 = "Cave Level 3 Secret 11"
cave3_secret_12 = "Cave Level 3 Secret 12"

visit_temple_entrance = "Visit Temple Entrance"
pof_switch_hub = "PoF Switch Hub"

# Cave Level 2
cave2_sw_room_1 = "Cave Level 2 Southwest Dupe 1"
cave2_sw_room_2 = "Cave Level 2 Southwest Dupe 2"
cave2_sw_room_3 = "Cave Level 2 Southwest Dupe 3"
cave2_sw_room_4 = "Cave Level 2 Southwest Dupe 4"
cave2_below_pumps_1 = "Cave Level 2 Below Pumps Room Dupe 1"
cave2_below_pumps_2 = "Cave Level 2 Below Pumps Room Dupe 2"
cave2_below_pumps_3 = "Cave Level 2 Below Pumps Room Dupe 3"
cave2_double_bridge_l_1 = "Cave Level 2 Left of Double Bridge Left"
cave2_double_bridge_l_2 = "Cave Level 2 Left of Double Bridge Right"
cave2_double_bridge_m = "Cave Level 2 Double Bridge"
cave2_double_bridge_r = "Cave Level 2 Right of Double Bridge"
cave2_double_bridge_secret = "Cave Level 2 Double Bridge Secret"
cave2_e_1 = "Cave Level 2 East Dupe 1"
cave2_e_2 = "Cave Level 2 East Dupe 2"
cave2_e_3 = "Cave Level 2 East Dupe 3"
cave2_e_4 = "Cave Level 2 East Dupe 4"
cave2_nw_1 = "Cave Level 2 NW Dupe 1"
cave2_nw_2 = "Cave Level 2 NW Dupe 2"
cave2_nw_3 = "Cave Level 2 NW Dupe 3"
cave2_nw_4 = "Cave Level 2 NW Dupe 4"
cave2_nw_5 = "Cave Level 2 NW Dupe 5"
cave2_sw = "Cave Level 2 South-West"
cave2_w_miniboss_1 = "Cave Level 2 West Miniboss Room Dupe 1"
cave2_w_miniboss_2 = "Cave Level 2 West Miniboss Room Dupe 2"
cave2_w_miniboss_3 = "Cave Level 2 West Miniboss Room Dupe 3"
cave2_w_miniboss_4 = "Cave Level 2 West Miniboss Room Dupe 4"
cave2_red_bridge_1 = "Cave Level 2 Red Bridge Dupe 1"
cave2_red_bridge_2 = "Cave Level 2 Red Bridge Dupe 2"
cave2_red_bridge_3 = "Cave Level 2 Red Bridge Dupe 3"
cave2_red_bridge_4 = "Cave Level 2 Red Bridge Dupe 4"
cave2_red_bridge_se_1 = "Cave Level 2 SE of Red Bridge Dupe 1"
cave2_red_bridge_se_2 = "Cave Level 2 SE of Red Bridge Dupe 2"
cave2_green_bridge = "Cave Level 2 Green Bridge"
cave2_guard = "Cave Level 2 Guard Room"
cave2_guard_n = "Cave Level 2 Above Guard Room"
cave2_guard_s = "Cave Level 2 Below Guard Room"
cave2_pumps_n = "Cave Level 2 Above Pumps Room"
cave2_secret_ne = "Cave Level 2 NE Secret Room"
cave2_secret_m = "Cave Level 2 Middle Secret Room"
cave2_secret_w = "Cave Level 2 West Secret Room"

cave2_pumps_wall_l = "Cave Level 2 Pumps Inside Left Wall"
cave2_pumps_wall_r = "Cave Level 2 Pumps Inside Right Wall"
cave2_water_n_l = "Cave Level 2 North Water Left"
cave2_water_n_r_1 = "Cave Level 2 North Water Right Dupe 1"
cave2_water_n_r_2 = "Cave Level 2 North Water Right Dupe 2"
cave2_water_s = "Cave Level 2 South Water"

victory = "Victory"
