# Pickup Names
# Hub
hub_front_of_pof = "Dunes Front of Pyramid of Fear"
hub_behind_temple_entrance = "Dunes Behind Temple Entrance"

hub_behind_shops = "Dunes Behind Shops"
hub_on_rock = "Dunes on Rock"
hub_west_pyramid = "Dunes West Past Rocks By Pyramid"
hub_rocks_south = "Dunes South Behind Rock"
hub_field_south = "Dunes Field South"
hub_field_nw = "Dunes Field NW"
hub_field_north = "Dunes Field North"

hub_pof_reward = "Dunes Pyramid of Fear Reward"

# Cave Level 3
cave3_squire = "Cave Level 3 Squire"
cave3_guard = "Cave Level 3 Guard"
cave3_n = "Cave Level 3 N"
cave3_nw = "Cave Level 3 NW"
cave3_ne = "Cave Level 3 NE"
cave3_se = "Cave Level 3 SE"
cave3_m = "Cave Level 3 Center"
cave3_half_bridge = "Cave Level 3 Half Bridge"
cave3_trapped_guard = "Cave Level 3 Trapped Guard Room"
cave3_outside_guard = "Cave Level 3 Outside Trapped Guard Room"
cave3_secret_n = "Cave Level 3 North Secret Room"
cave3_secret_nw = "Cave Level 3 NW Secret Room"
cave3_secret_s = "Cave Level 3 South Secret Room"

cave3_fall_nw = "Cave Level 3 Fall NW"
cave3_fall_ne = "Cave Level 3 Fall NE"
cave3_fall_sw = "Cave Level 3 Fall SW"
cave3_fall_se = "Cave Level 3 Fall SE"

cave3_fields_r = "Cave Level 3 Fields East"
cave3_captain = "Cave Level 3 Captain"
cave3_captain_dock = "Cave Level 3 Captain Dock"

cave3_portal_puzzle = "Cave Level 3 Portal Puzzle"  #
cave3_portal_l = "Cave Level 3 Portal Left"
cave3_portal_r = "Cave Level 3 Portal Right"

cave3_secret_1 = "Cave Level 3 Secret 1"
cave3_secret_2 = "Cave Level 3 Secret 2"
cave3_secret_3 = "Cave Level 3 Secret 3"
cave3_secret_4 = "Cave Level 3 Secret 4"
cave3_secret_5 = "Cave Level 3 Secret 5"
cave3_secret_6 = "Cave Level 3 Secret 6"
cave3_secret_7 = "Cave Level 3 Secret 7"
cave3_secret_8 = "Cave Level 3 Secret 8"
cave3_secret_9 = "Cave Level 3 Secret 9"
cave3_secret_10 = "Cave Level 3 Secret 10"
cave3_secret_11 = "Cave Level 3 Secret 11"
cave3_secret_12 = "Cave Level 3 Secret 12"

# Cave Level 2
cave2_sw_room_1 = "Cave Level 2 Southwest Dupe 1"
cave2_sw_room_2 = "Cave Level 2 Southwest Dupe 2"
cave2_sw_room_3 = "Cave Level 2 Southwest Dupe 3"
cave2_sw_room_4 = "Cave Level 2 Southwest Dupe 4"
cave2_below_pumps_1 = "Cave Level 2 Below Pumps Room Dupe 1"
cave2_below_pumps_2 = "Cave Level 2 Below Pumps Room Dupe 2"
cave2_below_pumps_3 = "Cave Level 2 Below Pumps Room Dupe 3"
cave2_double_bridge_l_1 = "Cave Level 2 Left of Double Bridge Left"
cave2_double_bridge_l_2 = "Cave Level 2 Left of Double Bridge Right"
cave2_double_bridge_m = "Cave Level 2 Double Bridge"
cave2_double_bridge_r = "Cave Level 2 Right of Double Bridge"
cave2_double_bridge_secret = "Cave Level 2 Double Bridge Secret"
cave2_e_1 = "Cave Level 2 East Dupe 1"
cave2_e_2 = "Cave Level 2 East Dupe 2"
cave2_e_3 = "Cave Level 2 East Dupe 3"
cave2_e_4 = "Cave Level 2 East Dupe 4"
cave2_nw_1 = "Cave Level 2 NW Dupe 1"
cave2_nw_2 = "Cave Level 2 NW Dupe 2"
cave2_nw_3 = "Cave Level 2 NW Dupe 3"
cave2_nw_4 = "Cave Level 2 NW Dupe 4"
cave2_nw_5 = "Cave Level 2 NW Dupe 5"
cave2_sw = "Cave Level 2 South-West"
cave2_w_miniboss_1 = "Cave Level 2 West Miniboss Room Dupe 1"
cave2_w_miniboss_2 = "Cave Level 2 West Miniboss Room Dupe 2"
cave2_w_miniboss_3 = "Cave Level 2 West Miniboss Room Dupe 3"
cave2_w_miniboss_4 = "Cave Level 2 West Miniboss Room Dupe 4"
cave2_red_bridge_1 = "Cave Level 2 Red Bridge Dupe 1"
cave2_red_bridge_2 = "Cave Level 2 Red Bridge Dupe 2"
cave2_red_bridge_3 = "Cave Level 2 Red Bridge Dupe 3"
cave2_red_bridge_4 = "Cave Level 2 Red Bridge Dupe 4"
cave2_red_bridge_se_1 = "Cave Level 2 SE of Red Bridge Dupe 1"
cave2_red_bridge_se_2 = "Cave Level 2 SE of Red Bridge Dupe 2"
cave2_green_bridge = "Cave Level 2 Green Bridge"
cave2_guard = "Cave Level 2 Guard Room"
cave2_guard_n = "Cave Level 2 Above Guard Room"
cave2_guard_s = "Cave Level 2 Below Guard Room"
cave2_pumps_n = "Cave Level 2 Above Pumps Room"
cave2_secret_ne = "Cave Level 2 NE Secret Room"
cave2_secret_m = "Cave Level 2 Middle Secret Room"
cave2_secret_w = "Cave Level 2 West Secret Room"

cave2_pumps_wall_l = "Cave Level 2 Pumps Inside Left Wall"
cave2_pumps_wall_r = "Cave Level 2 Pumps Inside Right Wall"
cave2_water_n_l = "Cave Level 2 North Water Left"
cave2_water_n_r_1 = "Cave Level 2 North Water Right Dupe 1"
cave2_water_n_r_2 = "Cave Level 2 North Water Right Dupe 2"
cave2_water_s = "Cave Level 2 South Water"

# Cave Level 1
cave1_n_1 = "Cave Level 1 North Ants Room Dupe 1"
cave1_n_2 = "Cave Level 1 North Ants Room Dupe 2"
cave1_n_3 = "Cave Level 1 North Ants Room Dupe 3"
cave1_n_room_1 = "Cave Level 1 North Big Room Dupe 1"
cave1_n_room_2 = "Cave Level 1 North Big Room Dupe 2"
cave1_n_room_3 = "Cave Level 1 North Big Room Dupe 3"
cave1_n_room_4 = "Cave Level 1 North Big Room Dupe 4"
cave1_w_1 = "Cave Level 1 West Dupe 1"
cave1_w_2 = "Cave Level 1 West Dupe 2"
cave1_w_by_water_1 = "Cave Level 1 West On Bank 1"
cave1_w_by_water_2 = "Cave Level 1 West On Bank 2"
cave1_s_1 = "Cave Level 1 South Miniboss Dupe 1"
cave1_s_2 = "Cave Level 1 South Miniboss Dupe 2"
cave1_s_3 = "Cave Level 1 South Vines"
cave1_s_4 = "Cave Level 1 South Entrance Dupe 1"
cave1_s_5 = "Cave Level 1 South Entrance Dupe 2"
cave1_m = "Cave Level 1 Middle Above Bridge"
cave1_secret_nw = "Cave Level 1 NW Secret Room"
cave1_secret_w = "Cave Level 1 West Secret Room"
cave1_secret_m = "Cave Level 1 Middle Secret Room"
cave1_double_room_l = "Cave Level 1 Left of Double Room"
cave1_double_room_r = "Cave Level 1 Right of Double Room"

cave1_ne_1 = "Cave Level 1 NE By Save Dupe 1"
cave1_ne_2 = "Cave Level 1 NE By Save Dupe 2"
cave1_ne_3 = "Cave Level 1 NE By Save Dupe 3"
cave1_ne_4 = "Cave Level 1 NE By Save Dupe 4"
cave1_ne_5 = "Cave Level 1 NE By Save Dupe 5"
cave1_ne_room_1 = "Cave Level 1 NE Cache Room Dupe 1"
cave1_ne_room_2 = "Cave Level 1 NE Cache Room Dupe 2"
cave1_ne_room_3 = "Cave Level 1 NE Cache Room Dupe 3"
cave1_ne_room_4 = "Cave Level 1 NE Cache Room Dupe 4"
cave1_ne_room_5 = "Cave Level 1 NE Cache Room Dupe 5"
cave1_ne_grubs = "Cave Level 1 NE Grub Central"
cave1_secret_tunnel_1 = "Cave Level 1 Secret Tunnel Dupe 1"
cave1_secret_tunnel_2 = "Cave Level 1 Secret Tunnel Dupe 2"
cave1_secret_tunnel_3 = "Cave Level 1 Secret Tunnel Dupe 3"
cave1_n_bridges_1 = "Cave Level 1 North of Bridge Intersection Dupe 1"
cave1_n_bridges_2 = "Cave Level 1 North of Bridge Intersection Dupe 2"
cave1_n_bridges_3 = "Cave Level 1 North of Bridge Intersection Dupe 3"
cave1_n_bridges_4 = "Cave Level 1 North of Bridge Intersection Dupe 4"
cave1_n_bridges_5 = "Cave Level 1 North of Bridge Intersection Dupe 5"
cave1_secret_ne = "Cave Level 1 NE Secret Room"
cave1_secret_n_room = "Cave Level 1 Secret Room in Cache Room"

cave1_e_1 = "Cave Level 1 East by Temple Dupe 1"
cave1_e_2 = "Cave Level 1 East by Temple Dupe 2"
cave1_e_3 = "Cave Level 1 East by Temple Dupe 3"
cave1_secret_e = "Cave Level 1 East Secret Room"
cave1_red_bridge_e = "Cave Level 1 East of Red Bridge"
cave1_se_1 = "Cave Level 1 SE Dupe 1"
cave1_se_2 = "Cave Level 1 SE Dupe 2"

cave1_water_s_1 = "Cave Level 1 South Underwater Dupe 1"
cave1_water_s_2 = "Cave Level 1 South Underwater Dupe 2"
cave1_water_s_3 = "Cave Level 1 South Underwater Dupe 3"
cave1_water_s_4 = "Cave Level 1 South Underwater Dupe 4"
cave1_water_s_5 = "Cave Level 1 South Underwater Dupe 5"
cave1_water_s_shore = "Cave Level 1 South Water Shore"

cave1_green_bridge_1 = "Cave Level 1 Green Bridge Dupe 1"
cave1_green_bridge_2 = "Cave Level 1 Green Bridge Dupe 2"
cave1_krilith_ledge_n = "Cave Level 1 Krilith Ledge North"
cave1_krilith_ledge_e = "Cave Level 1 Krilith Ledge East"
cave1_krilith_door = "Cave Level 1 Krilith Entrance"

cave1_temple_hall_1 = "Cave Level 1 Temple Hall Dupe 1"
cave1_temple_hall_2 = "Cave Level 1 Temple Hall Dupe 2"
cave1_temple_hall_3 = "Cave Level 1 Temple Hall Dupe 3"
cave1_temple_end_1 = "Cave Level 1 Temple End of Hall Dupe 1"
cave1_temple_end_2 = "Cave Level 1 Temple End of Hall Dupe 2"
cave1_temple_end_3 = "Cave Level 1 Temple End of Hall Dupe 3"
cave1_temple_end_4 = "Cave Level 1 Temple End of Hall Dupe 4"

# Boss 1
boss1_guard_l = "Sand Sharks Room Left of Guard"
boss1_guard_r_1 = "Sand Sharks Room Right of Guard Dupe 1"
boss1_guard_r_2 = "Sand Sharks Room Right of Guard Dupe 2"

boss1_bridge = "Sand Sharks Room Bridge"
boss1_bridge_n = "Sand Sharks Room Above Bridge"
boss1_drop = "Sand Sharks Reward"
boss1_drop_2 = "Sand Sharks Reward 2"
boss1_secret = "Sand Sharks Room Secret Room"

# Passage

# Temple Entrance
temple_entrance_l = "Temple Entrance Break Block Dupe 1"
temple_entrance_r = "Temple Entrance Break Block Dupe 2"

# Temple Floor 1
t1_above_s_bridge = "Temple Floor 1 Above South Bridge"
t1_s_bridge_1 = "Temple Floor 1 South Bridge Dupe 1"
t1_s_bridge_2 = "Temple Floor 1 South Bridge Dupe 2"
t1_s_bridge_3 = "Temple Floor 1 South Bridge Dupe 3"
t1_s_bridge_4 = "Temple Floor 1 South Bridge Dupe 4"
t1_s_bridge_5 = "Temple Floor 1 South Bridge Dupe 5"
t1_s_bridge_6 = "Temple Floor 1 South Bridge Dupe 6"
t1_sw_sun_room_1 = "Temple Floor 1 SW Sunbeam Dupe 1"
t1_sw_sun_room_2 = "Temple Floor 1 SW Sunbeam Dupe 2"
t1_sw_corner_room = "Temple Floor 1 SW Corner Room"
t1_sw_hidden_room_1 = "Temple Floor 1 SW Hidden Room Dupe 1"
t1_sw_hidden_room_2 = "Temple Floor 1 SW Hidden Room Dupe 2"
t1_sw_hidden_room_3 = "Temple Floor 1 SW Hidden Room Dupe 3"
t1_sw_hidden_room_4 = "Temple Floor 1 SW Hidden Room Dupe 4"

t1_sw_cache_1 = "Temple Floor 1 SW Cache Left of Spikes"
t1_sw_cache_2 = "Temple Floor 1 SW Cache Dupe Mana Drain Panel"
t1_sw_cache_3 = "Temple Floor 1 SW Cache Center"
t1_sw_cache_4 = "Temple Floor 1 SW Cache Right Dupe 1"
t1_sw_cache_5 = "Temple Floor 1 SW Cache Right Dupe 2"

t1_double_gate_1 = "Temple Floor 1 Double Gate Room Spikes"
t1_double_gate_2 = "Temple Floor 1 Double Gate Room Dupe 1"
t1_double_gate_3 = "Temple Floor 1 Double Gate Room Dupe 2"
t1_double_gate_hidden = "Temple Floor 1 Double Gate Room Behind Scenery"
t1_behind_bars_entrance = "Temple Floor 1 Behind Bars by Entrance"
t1_e_of_double_gate_room_1 = "Temple Floor 1 East of Double Gate Room Dupe 1"
t1_e_of_double_gate_room_2 = "Temple Floor 1 East of Double Gate Room Dupe 2"
t1_e_of_double_gate_room_3 = "Temple Floor 1 East of Double Gate Room Dupe 3"
t1_e_of_double_gate_room_4 = "Temple Floor 1 East of Double Gate Room Dupe 4"
t1_mana_drain_fire_trap = "Temple Floor 1 Mana Drain Fireball Trap"
t1_mana_drain_fire_trap_reward_1 = "Temple Floor 1 Mana Drain Fireball Trap Reward Dupe 1"
t1_mana_drain_fire_trap_reward_2 = "Temple Floor 1 Mana Drain Fireball Trap Reward Dupe 2"
t1_mana_drain_fire_trap_passage = "Temple Floor 1 Mana Drain Fireball Trap Passage"

t1_double_gate_behind_block = "Temple Floor 1 Double Gate Room Behind Block"
t1_s_of_sun_turret = "Temple Floor 1 South of Sun Turret Room"
t1_sun_turret_1 = "Temple Floor 1 Sun Turret Room NW"
t1_sun_turret_2 = "Temple Floor 1 Sun Turret Room North"
t1_sun_turret_3 = "Temple Floor 1 Sun Turret Room North Dupe"
t1_fire_trap_by_sun_turret_1 = "Temple Floor 1 Fire Trap by Sun Turret Middle"
t1_fire_trap_by_sun_turret_2 = "Temple Floor 1 Fire Trap by Sun Turret Right"
t1_fire_trap_by_sun_turret_3 = "Temple Floor 1 Fire Trap by Sun Turret Left"
t1_fire_trap_by_sun_turret_4 = "Temple Floor 1 Fire Trap by Sun Turret Bottom"

t1_ice_turret_1 = "Temple Floor 1 Ice Turret Room Left"
t1_ice_turret_2 = "Temple Floor 1 Ice Turret Room Right"
t1_telariana_1 = "Temple Floor 1 Telariana Left Dupe 1"
t1_telariana_2 = "Temple Floor 1 Telariana Left Dupe 2"
t1_telariana_3 = "Temple Floor 1 Telariana Left Dupe 3"
t1_telariana_4 = "Temple Floor 1 Telariana Right"
t1_telariana_5 = "Temple Floor 1 Telariana Middle"
t1_boulder_hallway_by_ice_turret_1 = "Temple Floor 1 Ice Turret Boulder Hallway Top Dupe 1"
t1_boulder_hallway_by_ice_turret_2 = "Temple Floor 1 Ice Turret Boulder Hallway Top Dupe 2"
t1_boulder_hallway_by_ice_turret_3 = "Temple Floor 1 Ice Turret Boulder Hallway Top Dupe 3"
t1_boulder_hallway_by_ice_turret_4 = "Temple Floor 1 Ice Turret Boulder Hallway"
t1_ice_turret_boulder_break_block = "Temple Floor 1 Ice Turret Boulder Breakable Block"
t1_n_sunbeam = "Temple Floor 1 North Sunbeam"
t1_n_sunbeam_treasure_1 = "Temple Floor 1 North Sunbeam Treasure Middle"
t1_n_sunbeam_treasure_2 = "Temple Floor 1 North Sunbeam Treasure Right"
t1_n_sunbeam_treasure_3 = "Temple Floor 1 North Sunbeam Treasure Left"

t1_n_cache_by_ice_turret_1 = "Temple Floor 1 North Cache by Ice Turret Left"
t1_n_cache_by_ice_turret_2 = "Temple Floor 1 North Cache by Ice Turret Middle Dupe 1"
t1_n_cache_by_ice_turret_3 = "Temple Floor 1 North Cache by Ice Turret Middle Dupe 2"
t1_n_cache_by_ice_turret_4 = "Temple Floor 1 North Cache by Ice Turret Right"
t1_n_cache_by_ice_turret_5 = "Temple Floor 1 North Cache by Ice Turret Right Dupe"

t1_s_cache_by_ice_turret_1 = "Temple Floor 1 South Cache by Ice Turret Left"
t1_s_cache_by_ice_turret_2 = "Temple Floor 1 South Cache by Ice Turret Right"
t1_s_cache_by_ice_turret_3 = "Temple Floor 1 South Cache by Ice Turret Right Dupe"

t1_ledge_after_block_trap_1 = "Temple Floor 1 Ledge North of 5 Block Traps Top"
t1_ledge_after_block_trap_2 = "Temple Floor 1 Ledge North of 5 Block Traps Bottom"
t1_ice_block_chamber_1 = "Temple Floor 1 Ice Block Chamber Top-Left"
t1_ice_block_chamber_2 = "Temple Floor 1 Ice Block Chamber Top-Right"
t1_ice_block_chamber_3 = "Temple Floor 1 Ice Block Chamber Bottom"
t1_node_2_1 = "Temple Floor 1 Node 2 Left"
t1_node_2_2 = "Temple Floor 1 Node 2 Right"
t1_node_2_passage_1 = "Temple Floor 1 Node 2 Passage Left"
t1_node_2_passage_2 = "Temple Floor 1 Node 2 Passage Middle"
t1_node_2_passage_3 = "Temple Floor 1 Node 2 Passage Right"
t1_e_gold_beetles = "Temple Floor 1 East Gold Beetles"

t1_sun_block_hall_1 = "Temple Floor 1 Sun Block Hall Alcove Top"
t1_sun_block_hall_2 = "Temple Floor 1 Sun Block Hall Alcove Bottom"
t1_sun_block_hall_3 = "Temple Floor 1 Sun Block Hall Alcove Right"
t1_sun_block_hall_4 = "Temple Floor 1 Sun Block Hall Alcove Far Right"

t1_telariana_ice = "Temple Floor 1 Telariana On Ice"
t1_ice_block_chamber_ice = "Temple Floor 1 Ice Block Chamber On Ice"

# Boss 2 Defeated Locations
boss2_nw = "Krilith Reward NW"
boss2_se = "Krilith Reward SE"

# Random locations
rloc_squire = "C3 Squire"
rloc_pan = "Frying Pan"
rloc_c2_portal = "C2 Portal"
rloc_c2_keystone = "C2 Keystone"
rloc_c1_portal = "C1 Portal"
rloc_c1_keystone = "C1 Keystone"
rloc_passage_entrance = "Passage Entrance"
rloc_passage_middle = "Passage Middle"
rloc_passage_end = "Passage End"

rloc_t1_portal = "T1 Portal"
rloc_t1_keystone = "T1 Keystone"
rloc_t1_silver_key_s = "T1 South Silver Key"
rloc_t1_silver_key_n = "T1 North Silver Key"
rloc_t1_silver_key_ice_turret = "T1 Ice Turret Silver Key"
rloc_t1_silver_key_funky = "T1 Funky Silver Key"
rloc_t1_gold_key = "T1 Gold Key"
rloc_t1_ore_funky = "T1 Funky Ore"
rloc_t1_ore_e = "T1 East Ore"
rloc_t1_mirror = "T1 Mirror"
rloc_t1_secret = "T1 Secret"
rloc_t1_sw_hidden_room = "T1 SW Hidden Room"
rloc_t1_exit = "T1 Exit"

rloc_t2_portal = "T2 Portal"
rloc_t3_portal = "T3 Portal"

# Event locations
ev_hub_pof_switch = "Dunes PoF Switch"
ev_cave1_pof_switch = "Cave Level 1 PoF Switch"
ev_cave2_pof_switch = "Cave Level 2 PoF Switch"
ev_cave3_pof_switch = "Cave Level 3 PoF Switch"
ev_temple1_pof_switch = "Temple Level 1 PoF Switch"
ev_temple2_pof_switch = "Temple Level 2 PoF Switch"
ev_temple_entrance_rock = "Temple Entrance Rock"
ev_krilith_defeated = "Krilith Defeated"
ev_pof_end = "Pyramid of Fear End"
ev_victory = "Victory"
