# Option names, to prevent typos
goal = "goal"
planks_required_count = "planks_required_count"
extra_plank_percent = "extra_plank_percent"
difficulty = "difficulty"
exit_randomization = "exit_randomization"
er_act_range = "er_act_range"
random_start_exit = "random_start_exit"
random_start_exit_act = "random_start_exit_act"
gate_shuffle = "gate_shuffle"
shop_shuffle = "shop_shuffle"
shop_upgrade_category_shuffle = "shop_upgrade_category_shuffle"
shop_upgrade_level_shuffle = "shop_upgrade_level_shuffle"
shop_cost_min = "shop_cost_min"
shop_cost_max = "shop_cost_max"
enemy_shuffle = "enemy_shuffle"
enemy_shuffle_act_range = "enemy_shuffle_act_range"
bonus_behavior = "bonus_behavior"
randomize_bonus_keys = "randomize_bonus_keys"
remove_lives = "remove_lives"
randomize_recovery_items = "randomize_recovery_items"
randomize_secrets = "randomize_secrets"
randomize_puzzles = "randomize_puzzles"
randomize_enemy_loot = "randomize_enemy_loot"
buttonsanity = "buttonsanity"
open_castle = "open_castle"
act_specific_keys = "act_specific_keys"
extra_keys_percent = "extra_keys_percent"
big_bronze_key_percent = "big_bronze_key_percent"
shortcut_teleporter = "shortcut_teleporter"
portal_accessibility = "portal_accessibility"
no_sunbeam_damage = "no_sunbeam_damage"
treasure_shuffle = "treasure_shuffle"
consumables_vendor_locations = "consumables_vendor_locations"
pan_fragments = "pan_fragments"
lever_fragments = "lever_fragments"
pickaxe_fragments = "pickaxe_fragments"
trap_item_percent = "trap_item_percent"
starting_life_count = "starting_life_count"
game_modifiers = "game_modifiers"
death_link = "death_link"

mod_no_extra_lives = "no_extra_lives"
mod_1_hp = "1_hp"
mod_shared_hp_pool = "shared_hp_pool"
mod_no_hp_pickups = "no_hp_pickups"
mod_no_mana_regen = "no_mana_regen"
mod_reverse_hp_regen = "reverse_hp_regen"
mod_infinite_lives = "infinite_lives"
mod_hp_regen = "hp_regen"
mod_double_damage = "double_damage"
mod_double_lives = "double_lives"
mod_5x_mana_regen = "5x_mana_regen"

game_modifier_names = [mod_no_extra_lives, mod_1_hp, mod_shared_hp_pool, mod_no_hp_pickups, mod_no_mana_regen,
                       mod_reverse_hp_regen,
                       mod_infinite_lives, mod_hp_regen, mod_double_damage, mod_double_lives, mod_5x_mana_regen]
