# Region Names
menu = "Menu"

hub_main = "Temple Outside"
hub_rocks = "Temple Outside Break Rocks"
hub_pyramid_of_fear = "Temple Outside Pyramid of Fear Reward"

pof_1_main = "Pyramid of Fear Level 1 Entrance"
pof_1_se_room = "Pyramid of Fear Level 1 SE Room"
pof_1_gate_1 = "Pyramid of Fear Level 1 NW Chamber"
pof_1_n_room = "Pyramid of Fear Level 1 North Room"
pof_1_gate_2 = "Pyramid of Fear Level 1 Exit Room"
pof_2_main = "Pyramid of Fear Level 2 Main Area"
pof_2_n = "Pyramid of Fear Level 2 North Area"
pof_3_main = "Pyramid of Fear Level 3"

library = "Library"

cave_3_main = "Cave Level 3"
cave_3_fall = "Cave Level 3 Fall from Surface"
cave_3_portal = "Cave Level 3 Portal"
cave_3_fields = "Cave Level 3 Activate Pumps"
cave_3_secret = "Cave Level 3 Secret"

cave_2_main = "Cave Level 2"
cave_2_pumps = "Cave Level 2 Activate Pumps"

cave_1_main = "Cave Level 1"
cave_1_blue_bridge = "Cave Level 1 Activate Blue Bridge"
cave_1_red_bridge = "Cave Level 1 Activate Red Bridge"
cave_1_green_bridge = "Cave Level 1 Activate Green Bridge"
cave_1_pumps = "Cave Level 1 Activate Pumps"
cave_1_temple = "Cave Level 1 Temple"

boss_1_main = "Sand Sharks"
boss_1_defeated = "Sand Sharks Defeated"

passage_entrance = "Passage Entrance"
passage_mid = "Passage Middle"
passage_end = "Passage End"

temple_entrance = "Temple Entrance"
temple_entrance_back = "Temple Entrance Back"

t1_main = "Temple Floor 1"
t1_sw_cache = "Temple Floor 1 SW Cache"
t1_node_1 = "Temple Floor 1 Node 1 Active"
t1_node_2 = "Temple Floor 1 Node 2 Active"
t1_sun_turret = "Temple Floor 1 Sun Turret"
t1_ice_turret = "Temple Floor 1 Ice Turret"
t1_n_of_ice_turret = "Temple Floor 1 North of Ice Turret"
t1_s_of_ice_turret = "Temple Floor 1 South of Ice Turret"
t1_east = "Temple Floor 1 East Temple"
t1_sun_block_hall = "Temple Floor 1 Hall Behind Sun Blocks"
t1_telariana_melt_ice = "Temple Floor 1 Telariana Ice Block"
t1_ice_chamber_melt_ice = "Temple Floor 1 Ice Block Chamber Ice Block"

boss2_main = "Krilith"
boss2_defeated = "Krilith Defeated"

t2_main = "Temple Floor 2"
t2_melt_ice = "Temple Floor 2 Ice Blocks"
t2_n_gate = "Temple Floor 2 North Silver Gate"
t2_s_gate = "Temple Floor 2 South Silver Gate"
t2_n_node = "Temple Floor 2 North Node Active"
t2_s_node = "Temple Floor 2 South Node Active"
t2_ornate = "Temple Floor 2 Gold Gate"
t2_ornate_t3 = "Temple Floor 2 North Cache Room"
t2_light_bridges = "Temple Floor 2 Light Bridges"

t3_main = "Temple Floor 3"
t3_n_node_blocks = "Temple Floor 3 North Node Blockade"
t3_s_node_blocks_1 = "Temple Floor 3 South Node First Blockade"
t3_s_node_blocks_2 = "Temple Floor 3 South Node Second Blockade"
t3_s_node = "Temple Floor 3 South Node Active"
t3_n_node = "Temple Floor 3 North Node Active"
t3_boss_fall_1 = "Temple Floor 3 Fall From Right Boss Platform"
t3_boss_fall_2 = "Temple Floor 3 Fall From Top Boss Platform"
t3_boss_fall_3 = "Temple Floor 3 Fall From Left Boss Platform"

b3_main = "Sha'Rand"
b3_platform_1 = "Sha'Rand Right Platform"
b3_platform_2 = "Sha'Rand Top Platform"
b3_platform_3 = "Sha'Rand Left Platform"
b3_defeated = "Sha'Rand Defeated"
