# Temple Region Names
menu = "Menu"

hub_main = "Temple Outside"
hub_rocks = "Temple Outside Break Rocks"
hub_pyramid_of_fear = "Temple Outside PoF Reward"

pof_1_main = "PoF L1 Entrance"
pof_1_se_room = "PoF L1 SE Room"
pof_1_se_room_top = "PoF L1 SE Room Treasure"
pof_1_sw_gate = "PoF L1 Before SW Gate"
pof_1_nw = "PoF L1 NW Chamber"
pof_1_n_room = "PoF L1 North Room"
pof_1_exit_hall = "PoF L1 Exit Hall"
pof_1_gate_2 = "PoF L1 Exit Room"
pof_2_main = "PoF L2 Main Area"
pof_2_n = "PoF L2 North Room"
pof_2_puzzle = "PoF L2 Puzzle Room"
pof_2_exit = "PoF L2 Exit"
pof_3_start = "PoF L3 Start"
pof_3_main = "PoF L3"
pof_puzzle = "PoF Puzzle"

library = "Library"
library_lobby = "Library Lobby"

cave_3_main = "Cave L3"
c3_e = "Cave L3 East"
cave_3_fall = "Cave L3 Fall from Surface"
cave_3_portal = "Cave L3 Portal"
cave_3_fields = "Cave L3 Activate Pumps"
c3_e_water = "Cave L3 East Underwater"
cave_3_secret = "Cave L3 Secret"
c3_puzzle = "Cave L3 Puzzle"

cave_2_main = "Cave L2"
c2_red_bridge = "Cave L2 Activate Red Bridge"
c2_green_bridge = "Cave L2 Activate Green Bridges"
c2_sw = "Cave L2 Southwest"
c2_double_bridge = "Cave L2 Double Bridge"
cave_2_pumps = "Cave L2 Activate Pumps"
c2_puzzle = "Cave L2 Puzzle"

cave_1_main = "Cave L1"
cave_1_blue_bridge = "Cave L1 Activate Blue Bridge"
cave_1_red_bridge = "Cave L1 Activate Red Bridge"
cave_1_green_bridge = "Cave L1 Activate Green Bridge"
c1_storage_island = "Cave L1 Storage Room Island"
c1_secret_hall = "Cave L1 Secret Tunnel"
cave_1_pumps = "Cave L1 Activate Pumps"
cave_1_temple = "Cave L1 Temple"
c1_n_puzzle = "Cave L1 North Puzzle"
c1_e_puzzle = "Cave L1 East Puzzle"

boss_1_entrance = "Dune Sharks Arena Entrance"
b1_back = "Dune Sharks Arena Back"
boss_1_arena = "Dune Sharks Arena"
boss_1_defeated = "Dune Sharks Defeated"

passage_entrance = "Passage Entrance"
passage_mid = "Passage Middle"
passage_end = "Passage End"
passage_puzzle = "Passage Puzzle"

temple_entrance = "Temple Entrance"
temple_entrance_back = "Temple Entrance Back"

t1_main = "Temple F1"
t1_sw_sdoor = "Temple F1 SW Silver Door"
t1_w = "Temple F1 West Node Room"
t1_node_1 = "Temple F1 West Node Active"
t1_node_2 = "Temple F1 East Node Active"
t1_sun_turret = "Temple F1 Fire Turret"
t1_ice_turret = "Temple F1 Ice Turret"
t1_n_of_ice_turret = "Temple F1 North of Ice Turret"
t1_s_of_ice_turret = "Temple F1 South of Ice Turret"
t1_east = "Temple F1 East Temple"
t1_sun_block_hall = "Temple F1 Hall Behind Sun Blocks"
t1_telarian = "Temple F1 Telarian Room"
t1_jail_e = "Temple F1 East Enemy Jail"
t1_telarian_melt_ice = "Temple F1 Telarian Ice Block"
t1_ice_chamber_melt_ice = "Temple F1 Ice Block Chamber Ice Block"
t1_w_puzzle = "Temple F1 West Puzzle"
t1_e_puzzle = "Temple F1 East Puzzle"

boss2_main = "Krilith"
boss2_defeated = "Krilith Defeated"

t2_main = "Temple F2"
t2_melt_ice = "Temple F2 Ice Blocks"
t2_w_ice_gate = "Temple F2 West Ice Gate"
t2_e_ice_gate = "Temple F2 East Ice Gate"
t2_n_gate = "Temple F2 North Silver Gate"
t2_s_gate = "Temple F2 South Silver Gate"
t2_n_node = "Temple F2 North Node Active"
t2_s_node = "Temple F2 South Node Active"
t2_jail_sw = "Temple F2 SW Jail"
t2_sdoor_gate = "Temple F2 South Shortcut Gate"
t2_pof = "Temple F2 Pyramid of Fear Switch"
t2_pof_spikes = "Temple F2 Pyramid of Fear Switch Spikes"
t2_jail_s = "Temple F2 South Jail"
t2_nw_button_gate = "Temple F2 NW Gate"
t2_boulder_room = "Temple F2 Boulder Room"
t2_n_hidden_hall = "Temple F2 Boulder Room Secret Passage"
t2_jones_hall = "Temple F2 Indiana Jones Hallway"
t2_ornate = "Temple F2 Gold Gate"
t2_ornate_t3 = "Temple F2 North Cache Room"
t2_ornate_gate = "Temple F2 North Cache Gate"
t2_light_bridge_w = "Temple F2 West Light Bridge"
t2_light_bridges_s = "Temple F2 South Light Bridges"
t2_light_bridges_se = "Temple F2 SE Light Bridges"
t2_portal_gate = "Temple F2 Portal Gate"
t2_n_puzzle = "Temple F2 North Puzzle"
t2_nw_puzzle = "Temple F2 NW Puzzle"
t2_e_puzzle = "Temple F2 East Puzzle"
t2_sw_puzzle = "Temple F2 SW Puzzle"

t3_main = "Temple F3"
t3_blockade_s = "Temple F3 South of Blockade"
t3_s_gate = "Temple F3 South Gate"
t3_n_node_blocks = "Temple F3 North Node Blockade"
t3_s_node_blocks_1 = "Temple F3 South Node First Blockade"
t3_s_node_blocks_2 = "Temple F3 South Node Second Blockade"
t3_s_node = "Temple F3 South Node Active"
t3_n_node = "Temple F3 North Node Active"
t3_gates = "Temple F3 Gates"
t3_boss_fall_1 = "Temple F3 Fall From Right Boss Platform"
t3_boss_fall_2 = "Temple F3 Fall From Top Boss Platform"
t3_boss_fall_3 = "Temple F3 Fall From Left Boss Platform"
t3_puzzle = "Temple F3 Puzzle"

b3_main = "Sha'Rand"
b3_platform_1 = "Sha'Rand Right Platform"
b3_platform_2 = "Sha'Rand Top Platform"
b3_platform_3 = "Sha'Rand Left Platform"
b3_defeated = "Sha'Rand Defeated"

get_planks = "Collect All Planks"
