# Temple of the Sun Pickup Location Names
# Hub
hub_front_of_pof = "Dunes Pyramid of Fear"
hub_behind_temple_entrance = "Dunes Behind Temple Entrance"

hub_behind_shops = "Dunes Behind Shops"
hub_on_rock = "Dunes on Rock"
hub_west_pyramid = "Dunes West Past Rocks By Pyramid"
hub_rocks_south = "Dunes South Behind Rock"
hub_field_south = "Dunes Field South"
hub_field_nw = "Dunes Field NW"
hub_field_north = "Dunes Field North"

hub_pof_reward = "Dunes Pyramid of Fear Reward"

# Cave Level 3
cave3_squire = "Cave Level 3 Squire"
cave3_guard = "Cave Level 3 Guard"
cave3_n = "Cave Level 3 N"
cave3_nw = "Cave Level 3 NW"
cave3_ne = "Cave Level 3 NE"
cave3_se = "Cave Level 3 SE"
cave3_m = "Cave Level 3 Center"
cave3_half_bridge = "Cave Level 3 Half Bridge"
cave3_trapped_guard = "Cave Level 3 Trapped Guard Room"
cave3_outside_guard = "Cave Level 3 Outside Trapped Guard Room"
cave3_secret_n = "Cave Level 3 North Secret Room"
cave3_secret_nw = "Cave Level 3 NW Secret Room"
cave3_secret_s = "Cave Level 3 South Secret Room"

cave3_fall_nw = "Cave Level 3 Fall NW"
cave3_fall_ne = "Cave Level 3 Fall NE"
cave3_fall_sw = "Cave Level 3 Fall SW"
cave3_fall_se = "Cave Level 3 Fall SE"

cave3_fields_r = "Cave Level 3 Fields East"
cave3_captain = "Cave Level 3 Captain"
cave3_captain_dock = "Cave Level 3 Captain Dock"

cave3_portal_puzzle = "Cave Level 3 Portal Puzzle"  #
cave3_portal_l = "Cave Level 3 Portal Left"
cave3_portal_r = "Cave Level 3 Portal Right"

cave3_secret_1 = "Cave Level 3 Secret 1"
cave3_secret_2 = "Cave Level 3 Secret 2"
cave3_secret_3 = "Cave Level 3 Secret 3"
cave3_secret_4 = "Cave Level 3 Secret 4"
cave3_secret_5 = "Cave Level 3 Secret 5"
cave3_secret_6 = "Cave Level 3 Secret 6"
cave3_secret_7 = "Cave Level 3 Secret 7"
cave3_secret_8 = "Cave Level 3 Secret 8"
cave3_secret_9 = "Cave Level 3 Secret 9"
cave3_secret_10 = "Cave Level 3 Secret 10"
cave3_secret_11 = "Cave Level 3 Secret 11"
cave3_secret_12 = "Cave Level 3 Secret 12"

c3_puzzle_1 = "Cave Level 3 Puzzle Reward 1"
c3_puzzle_2 = "Cave Level 3 Puzzle Reward 2"
c3_puzzle_3 = "Cave Level 3 Puzzle Reward 3"
c3_puzzle_4 = "Cave Level 3 Puzzle Reward 4"

# Cave Level 2
cave2_sw_hidden_room_1 = "Cave Level 2 Southwest Hidden Room Dupe 1"
cave2_sw_hidden_room_2 = "Cave Level 2 Southwest Hidden Room Dupe 2"
cave2_sw_hidden_room_3 = "Cave Level 2 Southwest Hidden Room Dupe 3"
cave2_sw_hidden_room_4 = "Cave Level 2 Southwest Hidden Room Dupe 4"
cave2_below_pumps_1 = "Cave Level 2 Below Pumps Room Dupe 1"
cave2_below_pumps_2 = "Cave Level 2 Below Pumps Room Dupe 2"
cave2_below_pumps_3 = "Cave Level 2 Below Pumps Room Dupe 3"
cave2_double_bridge_l_1 = "Cave Level 2 Left of Double Bridge Left"
cave2_double_bridge_l_2 = "Cave Level 2 Left of Double Bridge Right"
cave2_double_bridge_m = "Cave Level 2 Double Bridge"
cave2_double_bridge_r = "Cave Level 2 Right of Double Bridge"
cave2_double_bridge_secret = "Cave Level 2 Double Bridge Secret"
cave2_e_1 = "Cave Level 2 East Dupe 1"
cave2_e_2 = "Cave Level 2 East Dupe 2"
cave2_e_3 = "Cave Level 2 East Dupe 3"
cave2_e_4 = "Cave Level 2 East Dupe 4"
cave2_nw_1 = "Cave Level 2 NW Dupe 1"
cave2_nw_2 = "Cave Level 2 NW Dupe 2"
cave2_nw_3 = "Cave Level 2 NW Dupe 3"
cave2_nw_4 = "Cave Level 2 NW Dupe 4"
cave2_nw_5 = "Cave Level 2 NW Dupe 5"
cave2_sw = "Cave Level 2 Bat Cave"
cave2_w_miniboss_1 = "Cave Level 2 West Miniboss Room Dupe 1"
cave2_w_miniboss_2 = "Cave Level 2 West Miniboss Room Dupe 2"
cave2_w_miniboss_3 = "Cave Level 2 West Miniboss Room Dupe 3"
cave2_w_miniboss_4 = "Cave Level 2 West Miniboss Room Dupe 4"
cave2_red_bridge_1 = "Cave Level 2 Red Bridge Dupe 1"
cave2_red_bridge_2 = "Cave Level 2 Red Bridge Dupe 2"
cave2_red_bridge_3 = "Cave Level 2 Red Bridge Dupe 3"
cave2_red_bridge_4 = "Cave Level 2 Red Bridge Dupe 4"
cave2_red_bridge_se_1 = "Cave Level 2 SE of Red Bridge Dupe 1"
cave2_red_bridge_se_2 = "Cave Level 2 SE of Red Bridge Dupe 2"
cave2_green_bridge = "Cave Level 2 Green Bridge"
cave2_guard = "Cave Level 2 Guard Room"
cave2_guard_n = "Cave Level 2 Above Guard Room"
cave2_guard_s = "Cave Level 2 Below Guard Room"
cave2_pumps_n = "Cave Level 2 Above Pumps Room"
cave2_secret_ne = "Cave Level 2 NE Secret Room"
cave2_secret_m = "Cave Level 2 Middle Secret Room"
cave2_secret_w = "Cave Level 2 West Secret Room"

cave2_pumps_wall_l = "Cave Level 2 Pumps Inside Left Wall"
cave2_pumps_wall_r = "Cave Level 2 Pumps Inside Right Wall"
cave2_water_n_l = "Cave Level 2 North Water Left"
cave2_water_n_r_1 = "Cave Level 2 North Water Right Dupe 1"
cave2_water_n_r_2 = "Cave Level 2 North Water Right Dupe 2"
cave2_water_s = "Cave Level 2 South Water"

c2_puzzle_1 = "Cave Level 2 Puzzle Reward 1"
c2_puzzle_2 = "Cave Level 2 Puzzle Reward 2"
c2_puzzle_3 = "Cave Level 2 Puzzle Reward 3"
c2_puzzle_4 = "Cave Level 2 Puzzle Reward 4"

# Cave Level 1
cave1_n_1 = "Cave Level 1 North Spider Room Left"
cave1_n_2 = "Cave Level 1 North Spider Room Middle"
cave1_n_3 = "Cave Level 1 North Spider Room Right"
cave1_n_room_1 = "Cave Level 1 North Big Room Top"
cave1_n_room_2 = "Cave Level 1 North Big Room Middle-Top"
cave1_n_room_3 = "Cave Level 1 North Big Room Middle-Bottom"
cave1_n_room_4 = "Cave Level 1 North Big Room Bottom"
cave1_w_1 = "Cave Level 1 West Left"
cave1_w_2 = "Cave Level 1 West Right"
cave1_w_by_water_1 = "Cave Level 1 West On North Bank"
cave1_w_by_water_2 = "Cave Level 1 West On East Bank"
cave1_s_1 = "Cave Level 1 South Miniboss Left"
cave1_s_2 = "Cave Level 1 South Miniboss Right"
cave1_s_3 = "Cave Level 1 Vines by Entrance"
cave1_s_4 = "Cave Level 1 South Entrance Left"
cave1_s_5 = "Cave Level 1 South Entrance Right"
cave1_m = "Cave Level 1 Middle Above Bridge"
cave1_secret_nw = "Cave Level 1 NW Secret Room"
cave1_secret_w = "Cave Level 1 West Secret Room"
cave1_secret_m = "Cave Level 1 Middle Secret Room"
cave1_double_room_l = "Cave Level 1 Left of Double Room"
cave1_double_room_r = "Cave Level 1 Right of Double Room"

cave1_ne_1 = "Cave Level 1 NE By Save Dupe 1"
cave1_ne_2 = "Cave Level 1 NE By Save Dupe 2"
cave1_ne_3 = "Cave Level 1 NE By Save Dupe 3"
cave1_ne_4 = "Cave Level 1 NE By Save Dupe 4"
cave1_ne_5 = "Cave Level 1 NE By Save Dupe 5"
cave1_ne_hidden_room_1 = "Cave Level 1 NE Cache Room Dupe 1"
cave1_ne_hidden_room_2 = "Cave Level 1 NE Cache Room Dupe 2"
cave1_ne_hidden_room_3 = "Cave Level 1 NE Cache Room Dupe 3"
cave1_ne_hidden_room_4 = "Cave Level 1 NE Cache Room Dupe 4"
cave1_ne_hidden_room_5 = "Cave Level 1 NE Cache Room Dupe 5"
cave1_ne_grubs = "Cave Level 1 NE Grub Central"
cave1_secret_tunnel_1 = "Cave Level 1 Secret Tunnel Top"
cave1_secret_tunnel_2 = "Cave Level 1 Secret Tunnel Middle"
cave1_secret_tunnel_3 = "Cave Level 1 Secret Tunnel Bottom"
cave1_n_bridges_1 = "Cave Level 1 North of Bridge Intersection Left"
cave1_n_bridges_2 = "Cave Level 1 North of Bridge Intersection Top Left"
cave1_n_bridges_3 = "Cave Level 1 North of Bridge Intersection Top Right"
cave1_n_bridges_4 = "Cave Level 1 North of Bridge Intersection Left Corner"
cave1_n_bridges_5 = "Cave Level 1 North of Bridge Intersection Left Top"
cave1_secret_ne = "Cave Level 1 NE Secret Room"
cave1_secret_n_hidden_room = "Cave Level 1 Secret Room in Cache Room"

cave1_e_1 = "Cave Level 1 East by Temple Dupe 1"
cave1_e_2 = "Cave Level 1 East by Temple Dupe 2"
cave1_e_3 = "Cave Level 1 East by Temple Dupe 3"
cave1_secret_e = "Cave Level 1 East Secret Room"
cave1_red_bridge_e = "Cave Level 1 East of Red Bridge"
cave1_se_1 = "Cave Level 1 SE Dupe 1"
cave1_se_2 = "Cave Level 1 SE Dupe 2"

cave1_water_s_1 = "Cave Level 1 South Underwater Dupe 1"
cave1_water_s_2 = "Cave Level 1 South Underwater Dupe 2"
cave1_water_s_3 = "Cave Level 1 South Underwater Dupe 3"
cave1_water_s_4 = "Cave Level 1 South Underwater Dupe 4"
cave1_water_s_5 = "Cave Level 1 South Underwater Dupe 5"
cave1_water_s_shore = "Cave Level 1 South Water Shore"

cave1_green_bridge_1 = "Cave Level 1 Green Bridge Dupe 1"
cave1_green_bridge_2 = "Cave Level 1 Green Bridge Dupe 2"
cave1_krilith_ledge_n = "Cave Level 1 Krilith Ledge North"
cave1_krilith_ledge_e = "Cave Level 1 Krilith Ledge East"
cave1_krilith_door = "Cave Level 1 Krilith Entrance"

cave1_temple_hall_1 = "Cave Level 1 Temple Hall Dupe 1"
cave1_temple_hall_2 = "Cave Level 1 Temple Hall Dupe 2"
cave1_temple_hall_3 = "Cave Level 1 Temple Hall Dupe 3"
cave1_temple_end_1 = "Cave Level 1 Temple End of Hall Dupe 1"
cave1_temple_end_2 = "Cave Level 1 Temple End of Hall Dupe 2"
cave1_temple_end_3 = "Cave Level 1 Temple End of Hall Dupe 3"
cave1_temple_end_4 = "Cave Level 1 Temple End of Hall Dupe 4"

c1_n_puzzle_1 = "Cave Level 1 North Puzzle Reward 1"
c1_n_puzzle_2 = "Cave Level 1 North Puzzle Reward 2"
c1_n_puzzle_3 = "Cave Level 1 North Puzzle Reward 3"
c1_n_puzzle_4 = "Cave Level 1 North Puzzle Reward 4"
c1_e_puzzle_1 = "Cave Level 1 East Puzzle Reward 1"
c1_e_puzzle_2 = "Cave Level 1 East Puzzle Reward 2"
c1_e_puzzle_3 = "Cave Level 1 East Puzzle Reward 3"
c1_e_puzzle_4 = "Cave Level 1 East Puzzle Reward 4"

# Boss 1
boss1_guard_l = "Sand Sharks Room Left of Guard"
boss1_guard_r_1 = "Sand Sharks Room Right of Guard Dupe 1"
boss1_guard_r_2 = "Sand Sharks Room Right of Guard Dupe 2"

boss1_bridge = "Sand Sharks Room Bridge"
boss1_bridge_n = "Sand Sharks Room Above Bridge"
boss1_drop = "Sand Sharks Reward"
boss1_drop_2 = "Sand Sharks Reward 2"
boss1_secret = "Sand Sharks Room Secret Room"

# Passage
p_ent2_secret = "Passage Entrance Horizontal Room Secret"
p_mid1_1 = "Passage Middle Slime Cavern Left"
p_mid1_2 = "Passage Middle Slime Cavern Right"
p_mid2_1 = "Passage Middle Arrow Cavern Entrance"
p_mid2_2 = "Passage Middle Arrow Cavern End Top"
p_mid2_3 = "Passage Middle Arrow Cavern End Middle"
p_mid2_4 = "Passage Middle Arrow Cavern End Bottom"
p_mid3_secret_1 = "Passage Middle Secret Cavern Left"
p_mid3_secret_2 = "Passage Middle Secret Cavern Middle"
p_mid3_secret_3 = "Passage Middle Secret Cavern Right"
p_mid3_secret_4 = "Passage Middle Secret Cavern Far Right"
p_mid4_1 = "Passage Middle Bridge Cavern North"
p_mid4_2 = "Passage Middle Bridge Cavern Second Bridge"
p_mid4_3 = "Passage Middle Bridge Cavern South Top"
p_mid4_4 = "Passage Middle Bridge Cavern South Bottom"
p_mid5_1 = "Passage Middle Temple Stockpile North"
p_mid5_2 = "Passage Middle Temple Stockpile East"
p_mid5_secret = "Passage Middle Temple Stockpile Secret"
p_end1_secret = "Passage End U Cavern Secret"
p_end3_1 = "Passage End Zig-Zag Cavern Hidden Room Left"
p_end3_2 = "Passage End Zig-Zag Cavern Hidden Room Right"

p_puzzle_1 = "Passage Puzzle Reward 1"
p_puzzle_2 = "Passage Puzzle Reward 2"
p_puzzle_3 = "Passage Puzzle Reward 3"
p_puzzle_4 = "Passage Puzzle Reward 4"

# Temple Entrance
temple_entrance_l = "Temple Entrance Break Block Dupe 1"
temple_entrance_r = "Temple Entrance Break Block Dupe 2"

# Temple Floor 1
t1_above_s_bridge = "Temple Floor 1 Above South Bridge"
t1_s_bridge_1 = "Temple Floor 1 South Bridge Dupe 1"
t1_s_bridge_2 = "Temple Floor 1 South Bridge Dupe 2"
t1_s_bridge_3 = "Temple Floor 1 South Bridge Dupe 3"
t1_s_bridge_4 = "Temple Floor 1 South Bridge Dupe 4"
t1_s_bridge_5 = "Temple Floor 1 South Bridge Dupe 5"
t1_s_bridge_6 = "Temple Floor 1 South Bridge Dupe 6"
t1_sw_sun_room_1 = "Temple Floor 1 SW Sunbeam Dupe 1"
t1_sw_sun_room_2 = "Temple Floor 1 SW Sunbeam Dupe 2"
t1_sw_corner_room = "Temple Floor 1 SW Corner Room"
t1_sw_hidden_room_1 = "Temple Floor 1 SW Hidden Room Dupe 1"
t1_sw_hidden_room_2 = "Temple Floor 1 SW Hidden Room Dupe 2"
t1_sw_hidden_room_3 = "Temple Floor 1 SW Hidden Room Dupe 3"
t1_sw_hidden_room_4 = "Temple Floor 1 SW Hidden Room Dupe 4"

t1_sw_cache_1 = "Temple Floor 1 SW Cache Left of Spikes"
t1_sw_cache_2 = "Temple Floor 1 SW Cache Dupe Mana Drain Panel"
t1_sw_cache_3 = "Temple Floor 1 SW Cache Center"
t1_sw_cache_4 = "Temple Floor 1 SW Cache Right Dupe 1"
t1_sw_cache_5 = "Temple Floor 1 SW Cache Right Dupe 2"

t1_double_gate_1 = "Temple Floor 1 Double Gate Room Spikes"
t1_double_gate_2 = "Temple Floor 1 Double Gate Room Dupe 1"
t1_double_gate_3 = "Temple Floor 1 Double Gate Room Dupe 2"
t1_double_gate_hidden = "Temple Floor 1 Double Gate Room Behind Scenery"
t1_behind_bars_entrance = "Temple Floor 1 Behind Bars by Entrance"
t1_e_of_double_gate_room_1 = "Temple Floor 1 East of Double Gate Room Dupe 1"
t1_e_of_double_gate_room_2 = "Temple Floor 1 East of Double Gate Room Dupe 2"
t1_e_of_double_gate_room_3 = "Temple Floor 1 East of Double Gate Room Dupe 3"
t1_e_of_double_gate_room_4 = "Temple Floor 1 East of Double Gate Room Dupe 4"
t1_mana_drain_fire_trap = "Temple Floor 1 Mana Drain Fireball Trap"
t1_mana_drain_fire_trap_reward_1 = "Temple Floor 1 Mana Drain Fireball Trap Reward Dupe 1"
t1_mana_drain_fire_trap_reward_2 = "Temple Floor 1 Mana Drain Fireball Trap Reward Dupe 2"
t1_mana_drain_fire_trap_passage = "Temple Floor 1 Mana Drain Fireball Trap Passage"

t1_double_gate_behind_block = "Temple Floor 1 Double Gate Room Behind Block"
t1_s_of_sun_turret = "Temple Floor 1 South of Sun Turret Room"
t1_sun_turret_1 = "Temple Floor 1 Sun Turret Room NW"
t1_sun_turret_2 = "Temple Floor 1 Sun Turret Room North"
t1_sun_turret_3 = "Temple Floor 1 Sun Turret Room North Dupe"
t1_fire_trap_by_sun_turret_1 = "Temple Floor 1 Fire Trap by Sun Turret Middle"
t1_fire_trap_by_sun_turret_2 = "Temple Floor 1 Fire Trap by Sun Turret Right"
t1_fire_trap_by_sun_turret_3 = "Temple Floor 1 Fire Trap by Sun Turret Left"
t1_fire_trap_by_sun_turret_4 = "Temple Floor 1 Fire Trap by Sun Turret Bottom"

t1_ice_turret_1 = "Temple Floor 1 Ice Turret Room Left"
t1_ice_turret_2 = "Temple Floor 1 Ice Turret Room Right"
t1_telariana_1 = "Temple Floor 1 Telariana Left Dupe 1"
t1_telariana_2 = "Temple Floor 1 Telariana Left Dupe 2"
t1_telariana_3 = "Temple Floor 1 Telariana Left Dupe 3"
t1_telariana_4 = "Temple Floor 1 Telariana Right"
t1_telariana_5 = "Temple Floor 1 Telariana Middle"
t1_boulder_hallway_by_ice_turret_1 = "Temple Floor 1 Ice Turret Boulder Hallway Top Dupe 1"
t1_boulder_hallway_by_ice_turret_2 = "Temple Floor 1 Ice Turret Boulder Hallway Top Dupe 2"
t1_boulder_hallway_by_ice_turret_3 = "Temple Floor 1 Ice Turret Boulder Hallway Top Dupe 3"
t1_boulder_hallway_by_ice_turret_4 = "Temple Floor 1 Ice Turret Boulder Hallway"
t1_ice_turret_boulder_break_block = "Temple Floor 1 Ice Turret Boulder Breakable Block"
t1_n_sunbeam = "Temple Floor 1 North Sunbeam"
t1_n_sunbeam_treasure_1 = "Temple Floor 1 North Sunbeam Treasure Middle"
t1_n_sunbeam_treasure_2 = "Temple Floor 1 North Sunbeam Treasure Right"
t1_n_sunbeam_treasure_3 = "Temple Floor 1 North Sunbeam Treasure Left"

t1_n_cache_by_ice_turret_1 = "Temple Floor 1 North Cache by Ice Turret Left"
t1_n_cache_by_ice_turret_2 = "Temple Floor 1 North Cache by Ice Turret Middle Dupe 1"
t1_n_cache_by_ice_turret_3 = "Temple Floor 1 North Cache by Ice Turret Middle Dupe 2"
t1_n_cache_by_ice_turret_4 = "Temple Floor 1 North Cache by Ice Turret Right"
t1_n_cache_by_ice_turret_5 = "Temple Floor 1 North Cache by Ice Turret Right Dupe"

t1_s_cache_by_ice_turret_1 = "Temple Floor 1 South Cache by Ice Turret Left"
t1_s_cache_by_ice_turret_2 = "Temple Floor 1 South Cache by Ice Turret Right"
t1_s_cache_by_ice_turret_3 = "Temple Floor 1 South Cache by Ice Turret Right Dupe"

t1_ledge_after_block_trap_1 = "Temple Floor 1 Ledge North of 5 Block Traps Top"
t1_ledge_after_block_trap_2 = "Temple Floor 1 Ledge North of 5 Block Traps Bottom"
t1_ice_block_chamber_1 = "Temple Floor 1 Ice Block Chamber Top-Left"
t1_ice_block_chamber_2 = "Temple Floor 1 Ice Block Chamber Top-Right"
t1_ice_block_chamber_3 = "Temple Floor 1 Ice Block Chamber Bottom"
t1_node_2_1 = "Temple Floor 1 Node 2 Left"
t1_node_2_2 = "Temple Floor 1 Node 2 Right"
t1_node_2_passage_1 = "Temple Floor 1 Node 2 Passage Left"
t1_node_2_passage_2 = "Temple Floor 1 Node 2 Passage Middle"
t1_node_2_passage_3 = "Temple Floor 1 Node 2 Passage Right"
t1_e_gold_beetles = "Temple Floor 1 East Gold Beetles"

t1_sun_block_hall_1 = "Temple Floor 1 Sun Block Hall Alcove Top"
t1_sun_block_hall_2 = "Temple Floor 1 Sun Block Hall Alcove Bottom"
t1_sun_block_hall_3 = "Temple Floor 1 Sun Block Hall Alcove Right"
t1_sun_block_hall_4 = "Temple Floor 1 Sun Block Hall Alcove Far Right"

t1_telariana_ice = "Temple Floor 1 Telariana On Ice"
t1_ice_block_chamber_ice = "Temple Floor 1 Ice Block Chamber On Ice"

t1_w_puzzle_1 = "Temple Floor 1 West Puzzle Reward 1"
t1_w_puzzle_2 = "Temple Floor 1 West Puzzle Reward 2"
t1_w_puzzle_3 = "Temple Floor 1 West Puzzle Reward 3"
t1_w_puzzle_4 = "Temple Floor 1 West Puzzle Reward 4"
t1_e_puzzle_1 = "Temple Floor 1 East Puzzle Reward 1"
t1_e_puzzle_2 = "Temple Floor 1 East Puzzle Reward 2"
t1_e_puzzle_3 = "Temple Floor 1 East Puzzle Reward 3"
t1_e_puzzle_4 = "Temple Floor 1 East Puzzle Reward 4"

# Boss 2 Defeated
boss2_nw = "Krilith Reward NW"
boss2_se = "Krilith Reward SE"

# Temple Floor 2
t2_n_of_portal = "Temple Floor 2 North of Portal"
t2_s_of_portal = "Temple Floor 2 South of Portal"
t2_w_spike_trap_1 = "Temple Floor 2 W Spike Trap Left"
t2_w_spike_trap_2 = "Temple Floor 2 W Spike Trap Right"
t2_nw_puzzle_cache_1 = "Temple Floor 2 NW Puzzle Cache Dupe 1"
t2_nw_puzzle_cache_2 = "Temple Floor 2 NW Puzzle Cache Dupe 2"
t2_nw_puzzle_cache_3 = "Temple Floor 2 NW Puzzle Cache Dupe 3"
t2_nw_puzzle_cache_4 = "Temple Floor 2 NW Puzzle Cache Dupe 4"
t2_nw_puzzle_cache_5 = "Temple Floor 2 NW Puzzle Cache Dupe 5"
t2_nw_of_s_ice_turret = "Temple Floor 2 NW of South Ice Turret"
t2_w_hall_dead_end_1 = "Temple Floor 2 West T Hall Left Dupe 1"
t2_w_hall_dead_end_2 = "Temple Floor 2 West T Hall Left Dupe 2"
t2_w_hall_dead_end_3 = "Temple Floor 2 West T Hall Left Dupe 3"
t2_w_hall_dead_end_4 = "Temple Floor 2 West T Hall Right"
t2_w_hall_dead_end_5 = "Temple Floor 2 West T Hall Left Dupe 4"
t2_n_of_sw_gate_1 = "Temple Floor 2 North of SW Gate Top"
t2_n_of_sw_gate_2 = "Temple Floor 2 North of SW Gate Bottom"
t2_fire_trap_maze_1 = "Temple Floor 2 Fire Trap Maze Balcony Upper"
t2_fire_trap_maze_2 = "Temple Floor 2 Fire Trap Maze Balcony Lower"
t2_fire_trap_maze_3 = "Temple Floor 2 Central Fireball Mana Trap Upper"
t2_fire_trap_maze_4 = "Temple Floor 2 Central Fireball Mana Trap Lower"
t2_fire_trap_maze_5 = "Temple Floor 2 Fire Trap Maze Upper"
t2_fire_trap_maze_6 = "Temple Floor 2 Fire Trap Maze Lower"
t2_teleporter = "Temple Floor 2 Teleporter Room"
t2_e_outside_gold_beetle_cage_1 = "Temple Floor 2 Outside East Gold Beetle Cage Left"
t2_e_outside_gold_beetle_cage_2 = "Temple Floor 2 Outside East Gold Beetle Cage Right"
t2_boulder_chamber_1 = "Temple Floor 2 East Boulder Chamber NW"
t2_boulder_chamber_2 = "Temple Floor 2 East Boulder Chamber Right Boulder"
t2_boulder_chamber_3 = "Temple Floor 2 East Boulder Chamber NE"
t2_boulder_chamber_4 = "Temple Floor 2 East Boulder Chamber Bottom"
t2_s_balcony_1 = "Temple Floor 2 South Balcony Left"
t2_s_balcony_2 = "Temple Floor 2 South Balcony Right"
t2_se_banner_chamber_1 = "Temple Floor 2 SE Banner Chamber Banner Left"
t2_se_banner_chamber_2 = "Temple Floor 2 SE Banner Chamber Banner Right"
t2_se_banner_chamber_3 = "Temple Floor 2 SE Banner Chamber Banner Bottom"
t2_se_banner_chamber_4 = "Temple Floor 2 SE Banner Chamber NW"
t2_se_banner_chamber_5 = "Temple Floor 2 SE Banner Chamber NE"
t2_se_fireball_hall = "Temple Floor 2 SE Fireball Hall"

t2_sw_gate = "Temple Floor 2 SW Gate"
t2_s_node_room_1 = "Temple Floor 2 South Node Room Right"
t2_s_node_room_2 = "Temple Floor 2 South Node Room Bottom-Right"
t2_s_node_room_3 = "Temple Floor 2 South Node Room Bottom"
t2_s_sunbeam_1 = "Temple Floor 2 South Sunbeam Top"
t2_s_sunbeam_2 = "Temple Floor 2 South Sunbeam Bottom"
t2_sw_jail_1 = "Temple Floor 2 Archer Mummy Jail"
t2_sw_jail_2 = "Temple Floor 2 Archer Mummy Jail Dupe"
t2_left_of_pof_switch_1 = "Temple Floor 2 Left of PoF Switch"
t2_left_of_pof_switch_2 = "Temple Floor 2 Left of PoF Switch Dupe"
t2_right_of_pof_switch = "Temple Floor 2 Right of PoF Switch on Spikes"

t2_nw_ice_turret_1 = "Temple Floor 2 NW Ice Turrets Safety Room Bottom-Left Dupe 1"
t2_nw_ice_turret_2 = "Temple Floor 2 NW Ice Turrets Safety Room Bottom-Left Dupe 2"
t2_nw_ice_turret_3 = "Temple Floor 2 NW Ice Turrets Safety Room Bottom-Left Dupe 3"
t2_nw_ice_turret_4 = "Temple Floor 2 NW Ice Turrets Safety Room Top"
t2_nw_under_block = "Temple Floor 2 NW Block Trap"
t2_nw_gate_1 = "Temple Floor 2 NW Gate Left"
t2_nw_gate_2 = "Temple Floor 2 NW Gate Right"
t2_nw_gate_3 = "Temple Floor 2 Right of NW Gate"

t2_boulder_room_1 = "Temple Floor 2 Boulder Room Top"
t2_boulder_room_2 = "Temple Floor 2 Boulder Room Right"
t2_boulder_room_block = "Temple Floor 2 Boulder Room Under Block"
t2_mana_drain_fire_trap_1 = "Temple Floor 2 North Mana Drain Fire Trap Dupe 1"
t2_mana_drain_fire_trap_2 = "Temple Floor 2 North Mana Drain Fire Trap Dupe 2"
t2_jones_hallway = "Temple Floor 2 Indiana Jones Hallway"
t2_gold_beetle_barricade = "Temple Floor 2 West Gold Beetle Barricade"
t2_w_gold_beetle_room_1 = "Temple Floor 2 West Gold Beetle Room Dupe 1"
t2_w_gold_beetle_room_2 = "Temple Floor 2 West Gold Beetle Room Dupe 2"
t2_w_gold_beetle_room_3 = "Temple Floor 2 West Gold Beetle Room Dupe 3"
t2_w_gold_beetle_room_4 = "Temple Floor 2 West Gold Beetle Room Dupe 4"

t2_w_ice_block_gate = "Temple Floor 2 West Ice Block Gate"
t2_e_ice_block_gate = "Temple Floor 2 East Ice Block Gate"

t2_se_light_bridge_1 = "Temple Floor 2 SE Light Bridge Left"
t2_se_light_bridge_2 = "Temple Floor 2 SE Light Bridge Right"
t2_s_light_bridge_1 = "Temple Floor 2 South Light Bridge Left"
t2_s_light_bridge_2 = "Temple Floor 2 South Light Bridge Right"
t2_portal_gate = "Temple Floor 2 Portal Gate"

t2_floor3_cache_1 = "Temple Floor 2 Ornate Cache Left Dupe 1"
t2_floor3_cache_2 = "Temple Floor 2 Ornate Cache Left Dupe 2"
t2_floor3_cache_3 = "Temple Floor 2 Ornate Cache Right"
t2_floor3_cache_4 = "Temple Floor 2 Ornate Cache Upper Middle"
t2_floor3_cache_5 = "Temple Floor 2 Ornate Cache Lower Middle"
t2_floor3_cache_6 = "Temple Floor 2 Ornate Cache Lower"
t2_floor3_cache_gate = "Temple Floor 2 Ornate Cache Gate"

t2_n_puzzle_1 = "Temple Floor 2 North Puzzle Reward 1"
t2_n_puzzle_2 = "Temple Floor 2 North Puzzle Reward 2"
t2_n_puzzle_3 = "Temple Floor 2 North Puzzle Reward 3"
t2_n_puzzle_4 = "Temple Floor 2 North Puzzle Reward 4"
t2_nw_puzzle_1 = "Temple Floor 2 Northwest Puzzle Reward 1"
t2_nw_puzzle_2 = "Temple Floor 2 Northwest Puzzle Reward 2"
t2_nw_puzzle_3 = "Temple Floor 2 Northwest Puzzle Reward 3"
t2_nw_puzzle_4 = "Temple Floor 2 Northwest Puzzle Reward 4"
t2_e_puzzle_1 = "Temple Floor 2 East Puzzle Reward 1"
t2_e_puzzle_2 = "Temple Floor 2 East Puzzle Reward 2"
t2_e_puzzle_3 = "Temple Floor 2 East Puzzle Reward 3"
t2_e_puzzle_4 = "Temple Floor 2 East Puzzle Reward 4"
t2_sw_puzzle_1 = "Temple Floor 2 Southwest Puzzle Reward 1"
t2_sw_puzzle_2 = "Temple Floor 2 Southwest Puzzle Reward 2"
t2_sw_puzzle_3 = "Temple Floor 2 Southwest Puzzle Reward 3"
t2_sw_puzzle_4 = "Temple Floor 2 Southwest Puzzle Reward 4"

# Temple Floor 3
t3_s_balcony_turret_1 = "Temple Floor 3 South Balcony Turret Side Top"
t3_s_balcony_turret_2 = "Temple Floor 3 South Balcony Turret Side Bottom"
t3_n_turret_1 = "Temple Floor 3 North Turret"
t3_n_turret_2 = "Temple Floor 3 North Boulder"
t3_boulder_block = "Temple Floor 3 Boulder Block"
t3_e_turret_spikes = "Temple Floor 3 East Turret by Spikes"

t3_s_gate = "Temple Floor 3 South Gate"
t3_n_node_blocks_1 = "Temple Floor 3 Long Blockade Far Left"
t3_n_node_blocks_2 = "Temple Floor 3 Long Blockade Left"
t3_n_node_blocks_3 = "Temple Floor 3 Long Blockade Middle"
t3_n_node_blocks_4 = "Temple Floor 3 Long Blockade Right"
t3_n_node_blocks_5 = "Temple Floor 3 Long Blockade Far Right"

t3_s_node_cache_1 = "Temple Floor 3 South Node Cache Left"
t3_s_node_cache_2 = "Temple Floor 3 South Node Cache Top"
t3_s_node_cache_3 = "Temple Floor 3 South Node Cache Bottom"

t3_m_balcony_corridor = "Temple Floor 3 Middle Balcony Corridor"

t3_n_node_1 = "Temple Floor 3 North Node Left"
t3_n_node_2 = "Temple Floor 3 North Node Middle"
t3_n_node_3 = "Temple Floor 3 North Node Right"

t3_boss_fall_1_1 = "Temple Floor 3 Fall From Right Boss Platform Left"
t3_boss_fall_1_2 = "Temple Floor 3 Fall From Right Boss Platform Top-Right"
t3_boss_fall_1_3 = "Temple Floor 3 Fall From Right Boss Platform Bottom"

t3_boss_fall_2_1 = "Temple Floor 3 Fall From Top Boss Platform Top-Left"
t3_boss_fall_2_2 = "Temple Floor 3 Fall From Top Boss Platform Right"
t3_boss_fall_2_3 = "Temple Floor 3 Fall From Top Boss Platform Bottom-Left"

t3_boss_fall_3_1 = "Temple Floor 3 Fall From Left Boss Platform Top"
t3_boss_fall_3_2 = "Temple Floor 3 Fall From Left Boss Platform Left"
t3_boss_fall_3_3 = "Temple Floor 3 Fall From Left Boss Platform Right"
t3_boss_fall_3_4 = "Temple Floor 3 Fall From Left Boss Platform Bottom"

t3_puzzle_1 = "Temple Floor 3 Puzzle Reward 1"
t3_puzzle_2 = "Temple Floor 3 Puzzle Reward 2"
t3_puzzle_3 = "Temple Floor 3 Puzzle Reward 3"
t3_puzzle_4 = "Temple Floor 3 Puzzle Reward 4"

# PoF
pof_1_ent_1 = "Pyramid of Fear Level 1 Entrance Dupe 1"
pof_1_ent_2 = "Pyramid of Fear Level 1 Entrance Dupe 2"
pof_1_ent_3 = "Pyramid of Fear Level 1 Entrance Dupe 3"
pof_1_ent_4 = "Pyramid of Fear Level 1 Entrance Dupe 4"
pof_1_ent_5 = "Pyramid of Fear Level 1 Entrance Dupe 5"
pof_1_sw_left_1 = "Pyramid of Fear Level 1 SW Left Room Dupe 1"
pof_1_sw_left_2 = "Pyramid of Fear Level 1 SW Left Room Dupe 2"
pof_1_sw_left_3 = "Pyramid of Fear Level 1 SW Left Room Dupe 3"
pof_1_sw_left_4 = "Pyramid of Fear Level 1 SW Left Room Dupe 4"
pof_1_sw_left_5 = "Pyramid of Fear Level 1 SW Left Room Dupe 5"
pof_1_sw_left_6 = "Pyramid of Fear Level 1 SW Left Room Dupe 6"
pof_1_sw_left_7 = "Pyramid of Fear Level 1 SW Left Room Dupe 7"
pof_1_sw_left_8 = "Pyramid of Fear Level 1 SW Left Room Dupe 8"
pof_1_sw_left_9 = "Pyramid of Fear Level 1 SW Left Room Dupe 9"
pof_1_sw_left_10 = "Pyramid of Fear Level 1 SW Left Room Dupe 10"
pof_1_sw_left_11 = "Pyramid of Fear Level 1 SW Left Room Dupe 11"
pof_1_s_1 = "Pyramid of Fear Level 1 South Room Dupe 1"
pof_1_s_2 = "Pyramid of Fear Level 1 South Room Dupe 2"
pof_1_s_3 = "Pyramid of Fear Level 1 South Room Dupe 3"
pof_1_s_4 = "Pyramid of Fear Level 1 South Room Dupe 4"
pof_1_s_5 = "Pyramid of Fear Level 1 South Room Dupe 5"
pof_1_s_6 = "Pyramid of Fear Level 1 South Room Dupe 6"
pof_1_s_7 = "Pyramid of Fear Level 1 South Room Dupe 7"
pof_1_s_8 = "Pyramid of Fear Level 1 South Room Dupe 8"
pof_1_s_9 = "Pyramid of Fear Level 1 South Room Dupe 9"
pof_1_s_10 = "Pyramid of Fear Level 1 South Room Dupe 10"
pof_1_s_11 = "Pyramid of Fear Level 1 South Room Dupe 11"
pof_1_s_12 = "Pyramid of Fear Level 1 South Room Dupe 12"
pof_1_s_13 = "Pyramid of Fear Level 1 South Room Dupe 13"

pof_1_confuse_corner_1 = "Pyramid of Fear Level 1 Confuse Corner Dupe 1"
pof_1_confuse_corner_2 = "Pyramid of Fear Level 1 Confuse Corner Dupe 2"
pof_1_confuse_corner_3 = "Pyramid of Fear Level 1 Confuse Corner Dupe 3"
pof_1_confuse_corner_4 = "Pyramid of Fear Level 1 Confuse Corner Dupe 4"
pof_1_n_1 = "Pyramid of Fear Level 1 North Room Dupe 1"
pof_1_n_2 = "Pyramid of Fear Level 1 North Room Dupe 2"
pof_1_n_3 = "Pyramid of Fear Level 1 North Room Dupe 3"
pof_1_n_4 = "Pyramid of Fear Level 1 North Room Dupe 4"
pof_1_n_5 = "Pyramid of Fear Level 1 North Room Dupe 5"
pof_1_n_6 = "Pyramid of Fear Level 1 North Room Dupe 6"
pof_1_n_7 = "Pyramid of Fear Level 1 North Room Dupe 7"
pof_1_n_8 = "Pyramid of Fear Level 1 North Room Dupe 8"
pof_1_n_9 = "Pyramid of Fear Level 1 North Room Dupe 9"
pof_1_c_hall_1 = "Pyramid of Fear Level 1 C Hall Dupe 1"
pof_1_c_hall_2 = "Pyramid of Fear Level 1 C Hall Dupe 2"
pof_1_c_hall_3 = "Pyramid of Fear Level 1 C Hall Dupe 3"
pof_1_c_hall_4 = "Pyramid of Fear Level 1 C Hall Dupe 4"
pof_1_c_hall_5 = "Pyramid of Fear Level 1 C Hall Dupe 5"
pof_1_c_hall_6 = "Pyramid of Fear Level 1 C Hall Dupe 6"

pof_1_end_1 = "Pyramid of Fear Level 1 End Dupe 1"
pof_1_end_2 = "Pyramid of Fear Level 1 End Dupe 2"
pof_1_end_3 = "Pyramid of Fear Level 1 End Dupe 3"
pof_1_end_4 = "Pyramid of Fear Level 1 End Dupe 4"
pof_1_end_5 = "Pyramid of Fear Level 1 End Dupe 5"

pof_2_ent_1 = "Pyramid of Fear Level 2 Entrance Dupe 1"
pof_2_ent_2 = "Pyramid of Fear Level 2 Entrance Dupe 2"
pof_2_ent_3 = "Pyramid of Fear Level 2 Entrance Dupe 3"
pof_2_ent_4 = "Pyramid of Fear Level 2 Entrance Dupe 4"
pof_2_ent_5 = "Pyramid of Fear Level 2 Entrance Dupe 5"
pof_2_ent_6 = "Pyramid of Fear Level 2 Entrance Dupe 6"
pof_2_confuse_hall_1 = "Pyramid of Fear Level 2 Confuse Hall Dupe 1"
pof_2_confuse_hall_2 = "Pyramid of Fear Level 2 Confuse Hall Dupe 2"
pof_2_confuse_hall_3 = "Pyramid of Fear Level 2 Confuse Hall Dupe 3"
pof_2_confuse_hall_4 = "Pyramid of Fear Level 2 Confuse Hall Dupe 4"
pof_2_sw_1 = "Pyramid of Fear Level 2 SW Dupe 1"
pof_2_sw_2 = "Pyramid of Fear Level 2 SW Dupe 2"
pof_2_sw_3 = "Pyramid of Fear Level 2 SW Dupe 3"
pof_2_sw_4 = "Pyramid of Fear Level 2 SW Dupe 4"
pof_2_ne_1 = "Pyramid of Fear Level 2 NE Room Dupe 1"
pof_2_ne_2 = "Pyramid of Fear Level 2 NE Room Dupe 2"
pof_2_ne_3 = "Pyramid of Fear Level 2 NE Room Dupe 3"
pof_2_ne_4 = "Pyramid of Fear Level 2 NE Room Dupe 4"

pof_3_safety_room_1 = "Pyramid of Fear Level 3 Safety Room Top"
pof_3_safety_room_2 = "Pyramid of Fear Level 3 Safety Room Middle"
pof_3_safety_room_3 = "Pyramid of Fear Level 3 Safety Room Bottom"
pof_3_end_1 = "Pyramid of Fear Level 3 Exit Top"
pof_3_end_2 = "Pyramid of Fear Level 3 Exit Far Left"
pof_3_end_3 = "Pyramid of Fear Level 3 Exit Left"
pof_3_end_4 = "Pyramid of Fear Level 3 Exit Right"
pof_3_end_5 = "Pyramid of Fear Level 3 Exit Bottom"

pof_puzzle_1 = "Pyramid of Fear Puzzle Reward 1"
pof_puzzle_2 = "Pyramid of Fear Puzzle Reward 2"
pof_puzzle_3 = "Pyramid of Fear Puzzle Reward 3"
pof_puzzle_4 = "Pyramid of Fear Puzzle Reward 4"

# Random locations
rloc_t3_entrance = "T3 Entrance"
rloc_squire = "C3 Squire"
rloc_c3_secret_n = "C3 Secret 1"
rloc_c3_secret_nw = "C3 Secret 2"
rloc_c3_secret_s = "C3 Secret 3"
rloc_c3_puzzle = "C3 Puzzle 1"
rloc_pan = "Frying Pan"

rloc_c2_portal = "C2 Portal"
rloc_c2_keystone = "C2 Keystone"
rloc_c2_secret_1 = "C2 Secret 1"
rloc_c2_secret_2 = "C2 Secret 2"
rloc_c2_secret_3 = "C2 Secret 3"
rloc_c2_hidden_room = "C2 Hidden Room"
rloc_c2_puzzle = "C2 Puzzle 1"

rloc_c1_portal = "C1 Portal"
rloc_c1_keystone = "C1 Keystone"
rloc_c1_secret_1 = "C1 Secret 1"
rloc_c1_secret_2 = "C1 Secret 2"
rloc_c1_secret_3 = "C1 Secret 3"
rloc_c1_secret_4 = "C1 Secret 4"
rloc_c1_secret_5 = "C1 Secret 5"
rloc_c1_secret_6 = "C1 Secret 6"
rloc_c1_hidden_room = "C1 Hidden Room"
rloc_c1_exit = "C1 Exit"
rloc_c1_puzzle_n = "C1 Puzzle 1"
rloc_c1_puzzle_e = "C1 Puzzle 2"

rloc_b1_secret = "B1 Secret 1"

rloc_passage_entrance = "Passage Entrance"
rloc_passage_middle = "Passage Middle"
rloc_passage_end = "Passage End"
rloc_p_secret_1 = "P Secret 1"
rloc_p_secret_2 = "P Secret 2"
rloc_p_secret_3 = "P Secret 3"
rloc_p_secret_4 = "P Secret 4"
rloc_p_secret_5 = "P Secret 5"
rloc_p_secret_6 = "P Secret 6"
rloc_p_secret_7 = "P Secret 7"
rloc_p_alley = "P Hidden Room"
rloc_p_puzzle = "P Puzzle 1"

rloc_t1_portal = "T1 Portal"
rloc_t1_keystone = "T1 Keystone"
rloc_t1_silver_key_s = "T1 South Silver Key"
rloc_t1_silver_key_n = "T1 North Silver Key"
rloc_t1_silver_key_ice_turret = "T1 Ice Turret Silver Key"
rloc_t1_silver_key_funky = "T1 Funky Silver Key"
rloc_t1_gold_key = "T1 Gold Key"
rloc_t1_ore_funky = "T1 Funky Ore"
rloc_t1_ore_e = "T1 East Ore"
rloc_t1_mirror = "T1 Mirror"
rloc_t1_puzzle = "T1 Puzzle 1"
rloc_t1_puzzle_spawn = "T1 Puzzle Spawn"
rloc_t1_puzzle_w = "T1 Puzzle 1"
rloc_t1_puzzle_e = "T1 Puzzle 2"
rloc_t1_sw_hidden_room = "T1 Hidden Room"
rloc_t1_sw_hidden_room_random_node = "T1 Hidden Room Random Node"

rloc_t2_portal = "T2 Portal"
rloc_t2_keystone = "T2 Keystone"
rloc_t2_puzzle_spawn_1 = "T2 Puzzle Spawn EW"
rloc_t2_puzzle_spawn_2 = "T2 Puzzle Spawn NS"
rloc_t2_puzzle_n = "T2 Puzzle 1"
rloc_t2_puzzle_nw = "T2 Puzzle 2"
rloc_t2_puzzle_e = "T2 Puzzle 3"
rloc_t2_puzzle_sw = "T2 Puzzle 4"
rloc_t2_jones_reward = "T2 Jones Reward"
rloc_t2_gold_key = "T2 Gold Key"
rloc_t2_silver_key_1 = "T2 Silver Key 1"
rloc_t2_silver_key_2 = "T2 Silver Key 2"
rloc_t2_pickaxe = "Pickaxe"
rloc_t2_w_hidden_room = "T2 Hidden Room"

rloc_t3_s_beam_1 = "T3 S Beam 1"
rloc_t3_s_beam_2 = "T3 S Beam 2"
rloc_t3_s_beam_3 = "T3 S Beam 3"
rloc_t3_s_beam_4 = "T3 S Beam 4"
rloc_t3_s_beam_5 = "T3 S Beam 5"
rloc_t3_puzzle = "T3 Puzzle 1"

rloc_pof_puzzle = "POF Puzzle 1"

# Event locations
ev_hub_pof_switch = "Dunes PoF Switch"
ev_cave1_pof_switch = "Cave Level 1 PoF Switch"
ev_cave2_pof_switch = "Cave Level 2 PoF Switch"
ev_cave3_pof_switch = "Cave Level 3 PoF Switch"
ev_temple1_pof_switch = "Temple Level 1 PoF Switch"
ev_temple2_pof_switch = "Temple Level 2 PoF Switch"
ev_temple_entrance_rock = "Temple Entrance Rock"
ev_krilith_defeated = "Krilith Defeated"
ev_t1_n_node = "Temple Level 1 North Node"
ev_t1_s_node = "Temple Level 1 South Node"
ev_t2_n_node = "Temple Level 2 North Node"
ev_t2_s_node = "Temple Level 2 South Node"
ev_t3_n_node = "Temple Level 3 North Node"
ev_t3_s_node = "Temple Level 3 South Node"
ev_t2_n_bridge_switch = "Temple Level 2 North Bridge Switch"
ev_t2_w_bridge_switch = "Temple Level 2 West Bridge Switch"
ev_t2_sw_bridge_switch = "Temple Level 2 SW Bridge Switch"
ev_t2_se_bridge_switch = "Temple Level 2 SE Bridge Switch"
ev_t2_ne_bridge_switch = "Temple Level 2 NE Bridge Switch"
ev_pof_end = "Pyramid of Fear End"

# Shared Event Locations
ev_victory = "Victory"
