# Temple Region Names
menu = "Menu"

hub_main = "Temple Outside"
hub_rocks = "Temple Outside Break Rocks"
hub_pyramid_of_fear = "Temple Outside Pyramid of Fear Reward"

pof_1_main = "Pyramid of Fear Level 1 Entrance"
pof_1_se_room = "Pyramid of Fear Level 1 SE Room"
pof_1_se_room_top = "Pyramid of Fear Level 1 SE Room Treasure"
pof_1_sw_gate = "Pyramid of Fear Level 1 Before SW Gate"
pof_1_nw = "Pyramid of Fear Level 1 NW Chamber"
pof_1_n_room = "Pyramid of Fear Level 1 North Room"
pof_1_exit_hall = "Pyramid of Fear Level 1 Exit Hall"
pof_1_gate_2 = "Pyramid of Fear Level 1 Exit Room"
pof_2_main = "Pyramid of Fear Level 2 Main Area"
pof_2_n = "Pyramid of Fear Level 2 North Room"
pof_2_puzzle = "Pyramid of Fear Level 2 Puzzle Room"
pof_2_exit = "Pyramid of Fear Level 2 Exit"
pof_3_start = "Pyramid of Fear Level 3 Start"
pof_3_main = "Pyramid of Fear Level 3"
pof_puzzle = "Pyramid of Fear Puzzle"

library = "Library"
library_lobby = "Library Lobby"

cave_3_main = "Cave Level 3"
c3_e = "Cave Level 3 East"
cave_3_fall = "Cave Level 3 Fall from Surface"
cave_3_portal = "Cave Level 3 Portal"
cave_3_fields = "Cave Level 3 Activate Pumps"
c3_e_water = "Cave Level 3 East Underwater"
cave_3_secret = "Cave Level 3 Secret"
c3_puzzle = "Cave Level 3 Puzzle"

cave_2_main = "Cave Level 2"
c2_red_bridge = "Cave Level 2 Activate Red Bridge"
c2_green_bridge = "Cave Level 2 Activate Green Bridges"
c2_sw = "Cave Level 2 Southwest"
c2_double_bridge = "Cave Level 2 Double Bridge"
cave_2_pumps = "Cave Level 2 Activate Pumps"
c2_puzzle = "Cave Level 2 Puzzle"

cave_1_main = "Cave Level 1"
cave_1_blue_bridge = "Cave Level 1 Activate Blue Bridge"
cave_1_red_bridge = "Cave Level 1 Activate Red Bridge"
cave_1_green_bridge = "Cave Level 1 Activate Green Bridge"
c1_secret_hall = "Cave Level 1 Secret Tunnel"
cave_1_pumps = "Cave Level 1 Activate Pumps"
cave_1_temple = "Cave Level 1 Temple"
c1_n_puzzle = "Cave Level 1 North Puzzle"
c1_e_puzzle = "Cave Level 1 East Puzzle"

boss_1_entrance = "Dune Sharks Arena Entrance"
b1_back = "Dune Sharks Arena Back"
boss_1_arena = "Dune Sharks Arena"
boss_1_defeated = "Dune Sharks Defeated"

passage_entrance = "Passage Entrance"
passage_mid = "Passage Middle"
passage_end = "Passage End"
passage_puzzle = "Passage Puzzle"

temple_entrance = "Temple Entrance"
temple_entrance_back = "Temple Entrance Back"

t1_main = "Temple Floor 1"
t1_sw_sdoor = "Temple Floor 1 SW Silver Door"
t1_w = "Temple Floor 1 West Node Room"
t1_node_1 = "Temple Floor 1 West Node Active"
t1_node_2 = "Temple Floor 1 East Node Active"
t1_sun_turret = "Temple Floor 1 Fire Turret"
t1_ice_turret = "Temple Floor 1 Ice Turret"
t1_n_of_ice_turret = "Temple Floor 1 North of Ice Turret"
t1_s_of_ice_turret = "Temple Floor 1 South of Ice Turret"
t1_east = "Temple Floor 1 East Temple"
t1_sun_block_hall = "Temple Floor 1 Hall Behind Sun Blocks"
t1_telarian = "Temple Floor 1 Telarian Room"
t1_jail_e = "Temple Floor 1 East Enemy Jail"
t1_telarian_melt_ice = "Temple Floor 1 Telarian Ice Block"
t1_ice_chamber_melt_ice = "Temple Floor 1 Ice Block Chamber Ice Block"
t1_w_puzzle = "Temple Floor 1 West Puzzle"
t1_e_puzzle = "Temple Floor 1 East Puzzle"

boss2_main = "Krilith"
boss2_defeated = "Krilith Defeated"

t2_main = "Temple Floor 2"
t2_melt_ice = "Temple Floor 2 Ice Blocks"
t2_w_ice_gate = "Temple Floor 2 West Ice Gate"
t2_e_ice_gate = "Temple Floor 2 East Ice Gate"
t2_n_gate = "Temple Floor 2 North Silver Gate"
t2_s_gate = "Temple Floor 2 South Silver Gate"
t2_n_node = "Temple Floor 2 North Node Active"
t2_s_node = "Temple Floor 2 South Node Active"
t2_jail_sw = "Temple Floor 2 SW Jail"
t2_sdoor_gate = "Temple Floor 2 South Shortcut Gate"
t2_pof = "Temple Floor 2 Pyramid of Fear Switch"
t2_pof_spikes = "Temple Floor 2 Pyramid of Fear Switch Spikes"
t2_jail_s = "Temple Floor 2 South Jail"
t2_nw_button_gate = "Temple Floor 2 NW Gate"
t2_boulder_room = "Temple Floor 2 Boulder Room"
t2_n_hidden_hall = "Temple Floor 2 Boulder Room Secret Passage"
t2_jones_hall = "Temple Floor 2 Indiana Jones Hallway"
t2_ornate = "Temple Floor 2 Gold Gate"
t2_ornate_t3 = "Temple Floor 2 North Cache Room"
t2_ornate_gate = "Temple Floor 2 North Cache Gate"
t2_light_bridges = "Temple Floor 2 Light Bridges"
t2_portal_gate = "Temple Floor 2 Portal Gate"
t2_n_puzzle = "Temple Floor 2 North Puzzle"
t2_nw_puzzle = "Temple Floor 2 NW Puzzle"
t2_e_puzzle = "Temple Floor 2 East Puzzle"
t2_sw_puzzle = "Temple Floor 2 SW Puzzle"

t3_main = "Temple Floor 3"
t3_blockade_s = "Temple Floor 3 South of Blockade"
t3_s_gate = "Temple Floor 3 South Gate"
t3_n_node_blocks = "Temple Floor 3 North Node Blockade"
t3_s_node_blocks_1 = "Temple Floor 3 South Node First Blockade"
t3_s_node_blocks_2 = "Temple Floor 3 South Node Second Blockade"
t3_s_node = "Temple Floor 3 South Node Active"
t3_n_node = "Temple Floor 3 North Node Active"
t3_gates = "Temple Floor 3 Gates"
t3_boss_fall_1 = "Temple Floor 3 Fall From Right Boss Platform"
t3_boss_fall_2 = "Temple Floor 3 Fall From Top Boss Platform"
t3_boss_fall_3 = "Temple Floor 3 Fall From Left Boss Platform"
t3_puzzle = "Temple Floor 3 Puzzle"

b3_main = "Sha'Rand"
b3_platform_1 = "Sha'Rand Right Platform"
b3_platform_2 = "Sha'Rand Top Platform"
b3_platform_3 = "Sha'Rand Left Platform"
b3_defeated = "Sha'Rand Defeated"

get_planks = "Collect All Planks"
