# Temple Region Names
menu = "Menu"

hub_main = "Temple Outside"
hub_rocks = "Temple Outside Break Rocks"
hub_pyramid_of_fear = "Temple Outside PoF Reward"

pof_1_main = "PoF L1: Entrance"
pof_1_se_room = "PoF L1: SE Room"
pof_1_se_room_top = "PoF L1: SE Room Treasure"
pof_1_sw_gate = "PoF L1: Before SW Gate"
pof_1_nw = "PoF L1: NW Chamber"
pof_1_n_room = "PoF L1: North Room"
pof_1_exit_hall = "PoF L1: Exit Hall"
pof_1_gate_2 = "PoF L1: Exit Room"
pof_2_main = "PoF L2: Main Area"
pof_2_n = "PoF L2: North Room"
pof_2_puzzle = "PoF L2: Puzzle Room"
pof_2_exit = "PoF L2: Exit"
pof_3_start = "PoF L3: Start"
pof_3_main = "PoF L3"
pof_puzzle = "PoF Puzzle"

library = "Library"
library_lobby = "Library Lobby"

cave_3_main = "CL3: West"
c3_e = "CL3: East"
cave_3_fall = "CL3: Fall from Surface"
cave_3_portal = "CL3: Portal"
cave_3_fields = "CL3: Activate Pumps"
c3_e_water = "CL3: East Underwater"
cave_3_secret = "CL3: Secret"
c3_puzzle = "CL3: Puzzle"

cave_2_main = "CL2: East"
c2_red_bridge = "CL2: Activate Red Bridge"
c2_green_bridge = "CL2: East Green Bridge"
c2_sw = "CL2: Southwest"
c2_double_bridge = "CL2: Double Bridge"
cave_2_pumps = "CL2: Activate Pumps"
c2_puzzle = "CL2: Puzzle"

cave_1_main = "CL1: West"
cave_1_blue_bridge = "CL1: Activate Blue Bridge"
cave_1_red_bridge = "CL1: Activate Red Bridge"
cave_1_green_bridge = "CL1: Activate Green Bridge"
c1_storage_island = "CL1: Storage Room Island"
c1_secret_hall = "CL1: Secret Tunnel"
cave_1_pumps = "CL1: Activate Pumps"
cave_1_temple = "CL1: Temple"
c1_n_puzzle = "CL1: West Puzzle"
c1_e_puzzle = "CL1: East Puzzle"

boss_1_entrance = "Dune Sharks Entrance"
b1_back = "Dune Sharks Back"
boss_1_arena = "Dune Sharks Arena"
boss_1_defeated = "Dune Sharks Defeated"

passage_entrance = "SP: Entrance"
passage_mid = "SP: Middle"
passage_end = "SP: End"
passage_puzzle = "SP: Puzzle"

temple_entrance = "Temple Entrance"
temple_entrance_back = "Temple Entrance Back"

t1_main = "TF1: South"
t1_sw_sdoor = "TF1: SW Silver Door"
t1_w = "TF1: West Node Room"
t1_runway_halls = "TF1: Fireball Runway Passages"
t1_node_1 = "TF1: West Node Active"
t1_node_2 = "TF1: East Node Active"
t1_sun_turret = "TF1: Fire Turret"
t1_ice_turret = "TF1: Ice Turret"
t1_n_of_ice_turret = "TF1: North of Ice Turret"
t1_s_of_ice_turret = "TF1: South of Ice Turret"
t1_east = "TF1: East Temple"
t1_sun_block_hall = "TF1: Hall Behind Sun Blocks"
t1_telarian = "TF1: Telarian Room"
t1_jail_e = "TF1: East Enemy Jail"
t1_ne_hall = "TF1: NE Node Passage"
t1_telarian_melt_ice = "TF1: Telarian Ice Block"
t1_ice_chamber_melt_ice = "TF1: Ice Block Chamber Ice Block"
t1_w_puzzle = "TF1: West Puzzle"
t1_e_puzzle = "TF1: East Puzzle"

boss2_main = "Krilith Arena"
boss2_defeated = "Krilith Defeated"

t2_main = "TF2: Center"
t2_melt_ice = "TF2: Ice Blocks"
t2_w_ice_gate = "TF2: West Ice Gate"
t2_e_ice_gate = "TF2: East Ice Gate"
t2_n_gate = "TF2: North Silver Gate"
t2_s_gate = "TF2: South Silver Gate"
t2_n_node = "TF2: North Node Active"
t2_s_node = "TF2: South Node Active"
t2_jail_sw = "TF2: SW Jail"
t2_sdoor_gate = "TF2: South Shortcut Gate"
t2_pof = "TF2: Pyramid of Fear Switch"
t2_pof_spikes = "TF2: Pyramid of Fear Switch Spikes"
t2_jail_s = "TF2: South Jail"
t2_nw_button_gate = "TF2: NW Gate"
t2_boulder_room = "TF2: Boulder Room"
t2_n_hidden_hall = "TF2: Boulder Room Secret Passage"
t2_jones_hall = "TF2: Indiana Jones Hallway"
t2_ornate = "TF2: Gold Gate"
t2_ornate_t3 = "TF2: North Cache Room"
t2_ornate_gate = "TF2: North Cache Gate"
t2_light_bridge_w = "TF2: West Light Bridge"
t2_light_bridges_s = "TF2: South Light Bridges"
t2_light_bridges_se = "TF2: SE Light Bridges"
t2_portal_gate = "TF2: Portal Gate"
t2_n_puzzle = "TF2: North Puzzle"
t2_nw_puzzle = "TF2: NW Puzzle"
t2_e_puzzle = "TF2: East Puzzle"
t2_sw_puzzle = "TF2: SW Puzzle"

t3_main = "TF3: Main Area"
t3_blockade_s = "TF3: South of Blockade"
t3_s_gate = "TF3: South Gate"
t3_n_node_blocks = "TF3: North Node Blockade"
t3_s_node_blocks_1 = "TF3: South Node First Blockade"
t3_s_node_blocks_2 = "TF3: South Node Second Blockade"
t3_s_node = "TF3: South Node Active"
t3_n_node = "TF3: North Node Active"
t3_gates = "TF3: Gates"
t3_puzzle_room = "TF3: Puzzle Room"
t3_boss_fall_1 = "TF3: Fall From Right Boss Platform"
t3_boss_fall_2 = "TF3: Fall From Top Boss Platform"
t3_boss_fall_3 = "TF3: Fall From Left Boss Platform"
t3_puzzle = "TF3: Puzzle"

b3_main = "Sha'Rand"
b3_platform_1 = "Sha'Rand Right Platform"
b3_platform_2 = "Sha'Rand Top Platform"
b3_platform_3 = "Sha'Rand Left Platform"
b3_defeated = "Sha'Rand Defeated"

get_planks = "Collect All Planks"
