# Temple of the Sun Pickup Location Names
# Hub
hub_front_of_pof = "Outside: Pyramid of Fear"
hub_behind_temple_entrance = "Outside: Behind Temple Entrance"

hub_behind_shops = "Outside: Behind Shops"
hub_on_rock = "Outside: Shops Rock"
hub_west_pyramid = "Outside: West Past Rocks By Pyramid"
hub_rocks_south = "Outside: South Behind Rock"
hub_field_south = "Outside: Field South"
hub_field_nw = "Outside: Field NW"
hub_field_north = "Outside: Field North"

hub_pof_reward = "Outside: Pyramid of Fear Reward"

# Cave Level 3
cave3_squire = "CL3: Squire"
cave3_guard = "CL3: West Guard"
cave3_n = "CL3: North Save"
cave3_nw = "CL3: By Miniboss"
cave3_ne = "CL3: NE"
cave3_se = "CL3: Return Portal"
cave3_m = "CL3: Center"
cave3_half_bridge = "CL3: Half Bridge"
cave3_trapped_guard = "CL3: Trapped Guard"
cave3_outside_guard = "CL3: Below Trapped Guard"
cave3_secret_n = "CL3: North Secret"
cave3_secret_nw = "CL3: NW Secret"
cave3_secret_s = "CL3: South Secret"

cave3_fall_nw = "CL3: Outside Fall #1"
cave3_fall_ne = "CL3: Outside Fall #2"
cave3_fall_sw = "CL3: Outside Fall #3"
cave3_fall_se = "CL3: Outside Fall #4"

cave3_fields_r = "CL3: Fields East"
cave3_captain = "CL3: Sun Dock #2"
cave3_captain_dock = "CL3: Sun Dock #1"

cave3_portal_puzzle = "CL3: Portal Puzzle"
cave3_portal_l = "CL3: PoF Switch #1"
cave3_portal_r = "CL3: PoF Switch #2"

cave3_secret_1 = "CL3: Temple Fall #1"
cave3_secret_2 = "CL3: Temple Fall #2"
cave3_secret_3 = "CL3: Temple Fall #3"
cave3_secret_4 = "CL3: Temple Fall #4"
cave3_secret_5 = "CL3: Temple Fall #5"
cave3_secret_6 = "CL3: Temple Fall #6"
cave3_secret_7 = "CL3: Temple Fall #7"
cave3_secret_8 = "CL3: Temple Fall #8"
cave3_secret_9 = "CL3: Temple Fall #9"
cave3_secret_10 = "CL3: Temple Fall #10"
cave3_secret_11 = "CL3: Temple Fall #11"
cave3_secret_12 = "CL3: Temple Fall #12"

c3_puzzle_1 = "CL3: Puzzle Reward #1"
c3_puzzle_2 = "CL3: Puzzle Reward #2"
c3_puzzle_3 = "CL3: Puzzle Reward #3"
c3_puzzle_4 = "CL3: Puzzle Reward #4"

# Cave Level 2
cave2_sw_hidden_room_1 = "CL2: SW Hidden Room #1"
cave2_sw_hidden_room_2 = "CL2: SW Hidden Room #2"
cave2_sw_hidden_room_3 = "CL2: SW Hidden Room #3"
cave2_sw_hidden_room_4 = "CL2: SW Hidden Room #4"
cave2_below_pumps_1 = "CL2: West Save #1"
cave2_below_pumps_2 = "CL2: West Save #2"
cave2_below_pumps_3 = "CL2: West Save #3"
cave2_double_bridge_l_1 = "CL2: Left of Double Bridge #1"
cave2_double_bridge_l_2 = "CL2: Left of Double Bridge #2"
cave2_double_bridge_m = "CL2: Double Bridge"
cave2_double_bridge_r = "CL2: Right of Double Bridge"
cave2_double_bridge_secret = "CL2: Double Bridge Switch Room"
cave2_e_1 = "CL2: East Top #1"
cave2_e_2 = "CL2: East Top #2"
cave2_e_3 = "CL2: East Bottom #1"
cave2_e_4 = "CL2: East Bottom #2"
cave2_nw_1 = "CL2: NW Left #1"
cave2_nw_2 = "CL2: NW Right"
cave2_nw_3 = "CL2: NW Left #2"
cave2_nw_4 = "CL2: NW Top #1"
cave2_nw_5 = "CL2: NW Top #2"
cave2_sw = "CL2: East of Puzzle"
cave2_w_miniboss_1 = "CL2: West Miniboss #1"
cave2_w_miniboss_2 = "CL2: West Miniboss #2"
cave2_w_miniboss_3 = "CL2: West Miniboss #3"
cave2_w_miniboss_4 = "CL2: West Miniboss #4"
cave2_red_bridge_1 = "CL2: Red Bridge #2"
cave2_red_bridge_2 = "CL2: Red Bridge #4"
cave2_red_bridge_3 = "CL2: Red Bridge #3"
cave2_red_bridge_4 = "CL2: Red Bridge #1"
cave2_red_bridge_se_1 = "CL2: East Miniboss #1"
cave2_red_bridge_se_2 = "CL2: East Miniboss #2"
cave2_green_bridge = "CL2: Green Bridge"
cave2_guard = "CL2: Cowardly Guard"
cave2_guard_n = "CL2: Above Cowardly Guard"
cave2_guard_s = "CL2: Below Cowardly Guard"
cave2_pumps_n = "CL2: Above Pumps Lever Socket"
cave2_secret_ne = "CL2: NE Secret"
cave2_secret_m = "CL2: Middle Secret"
cave2_secret_w = "CL2: West Secret"

cave2_pumps_wall_l = "CL2: Pumps Left Wall"
cave2_pumps_wall_r = "CL2: Pumps Right Wall"
cave2_water_n_l = "CL2: North Underwater #1"
cave2_water_n_r_1 = "CL2: North Underwater #2"
cave2_water_n_r_2 = "CL2: North Underwater #3"
cave2_water_s = "CL2: South Underwater"

c2_puzzle_1 = "CL2: Puzzle Reward #1"
c2_puzzle_2 = "CL2: Puzzle Reward #2"
c2_puzzle_3 = "CL2: Puzzle Reward #3"
c2_puzzle_4 = "CL2: Puzzle Reward #4"

# Cave Level 1
cave1_n_1 = "CL1: Right of West Puzzle #1"
cave1_n_2 = "CL1: Right of West Puzzle #2"
cave1_n_3 = "CL1: Right of West Puzzle #3"
cave1_n_room_1 = "CL1: South of West Puzzle #1"
cave1_n_room_2 = "CL1: South of West Puzzle #2"
cave1_n_room_3 = "CL1: South of West Puzzle #3"
cave1_n_room_4 = "CL1: South of West Puzzle #4"
cave1_w_1 = "CL1: West Arrow Traps Right #1"
cave1_w_2 = "CL1: West Arrow Traps Right #2"
cave1_w_by_water_1 = "CL1: SW Lake Top Shore #2"
cave1_w_by_water_2 = "CL1: SW Lake Top Shore #1"
cave1_s_1 = "CL1: South Miniboss Left #1"
cave1_s_2 = "CL1: South Miniboss Left #2"
cave1_s_3 = "CL1: South Miniboss Behind Vines"
cave1_s_4 = "CL1: South Miniboss Right #1"
cave1_s_5 = "CL1: South Miniboss Right #2"
cave1_m = "CL1: Middle Arrow Trap Dead End"
cave1_secret_nw = "CL1: NW Secret"
cave1_secret_w = "CL1: West Secret"
cave1_secret_m = "CL1: Middle Secret"
cave1_double_room_l = "CL1: SW Lake Right Shore"
cave1_double_room_r = "CL1: Left of Storeroom"

cave1_ne_1 = "CL1: NE Save Top #1"
cave1_ne_2 = "CL1: NE Save Top #2"
cave1_ne_3 = "CL1: NE Save Bottom #1"
cave1_ne_4 = "CL1: NE Save Bottom #2"
cave1_ne_5 = "CL1: NE Save Bottom #3"
cave1_ne_hidden_room_1 = "CL1: NE Cache #1"
cave1_ne_hidden_room_2 = "CL1: NE Cache #2"
cave1_ne_hidden_room_3 = "CL1: NE Cache #3"
cave1_ne_hidden_room_4 = "CL1: NE Cache #4"
cave1_ne_hidden_room_5 = "CL1: NE Cache #5"
cave1_ne_grubs = "CL1: NE Miniboss"
cave1_secret_tunnel_1 = "CL1: Secret Tunnel #1"
cave1_secret_tunnel_2 = "CL1: Secret Tunnel #2"
cave1_secret_tunnel_3 = "CL1: Secret Tunnel #3"
cave1_n_bridges_1 = "CL1: North Bridge Island #5"
cave1_n_bridges_2 = "CL1: North Bridge Island #3"
cave1_n_bridges_3 = "CL1: North Bridge Island #4"
cave1_n_bridges_4 = "CL1: North Bridge Island #1"
cave1_n_bridges_5 = "CL1: North Bridge Island #2"
cave1_secret_ne = "CL1: NE Secret"
cave1_secret_n_hidden_room = "CL1: Secret in NE Cache"

cave1_e_1 = "CL1: East by Temple #1"
cave1_e_2 = "CL1: East by Temple #2"
cave1_e_3 = "CL1: East by Temple #3"
cave1_secret_e = "CL1: East Secret"
cave1_red_bridge_e = "CL1: East of Red Bridge"
cave1_se_1 = "CL1: SE #1"
cave1_se_2 = "CL1: SE #2"

cave1_water_s_1 = "CL1: South Underwater by Storeroom Left"
cave1_water_s_2 = "CL1: South Underwater by Storeroom Bottom"
cave1_water_s_3 = "CL1: South Underwater Right Top"
cave1_water_s_4 = "CL1: South Underwater Right Bottom"
cave1_water_s_5 = "CL1: South Underwater Green Switch"
cave1_water_s_shore = "CL1: South Water Shore"

cave1_green_bridge_1 = "CL1: Green Bridge #1"
cave1_green_bridge_2 = "CL1: Green Bridge #2"
cave1_krilith_ledge_n = "CL1: Storage Ledge North"
cave1_krilith_ledge_e = "CL1: Storage Ledge East"
cave1_krilith_door = "CL1: Storage Entrance"

cave1_temple_hall_1 = "CL1: Temple Bottom #1"
cave1_temple_hall_2 = "CL1: Temple Bottom #2"
cave1_temple_hall_3 = "CL1: Temple Bottom #3"
cave1_temple_end_1 = "CL1: Temple Top #1"
cave1_temple_end_2 = "CL1: Temple Top #2"
cave1_temple_end_3 = "CL1: Temple Top #3"
cave1_temple_end_4 = "CL1: Temple Top #4"

c1_n_puzzle_1 = "CL1: North Puzzle Reward #1"
c1_n_puzzle_2 = "CL1: North Puzzle Reward #2"
c1_n_puzzle_3 = "CL1: North Puzzle Reward #3"
c1_n_puzzle_4 = "CL1: North Puzzle Reward #4"
c1_e_puzzle_1 = "CL1: East Puzzle Reward #1"
c1_e_puzzle_2 = "CL1: East Puzzle Reward #2"
c1_e_puzzle_3 = "CL1: East Puzzle Reward #3"
c1_e_puzzle_4 = "CL1: East Puzzle Reward #4"

# Boss 1
boss1_guard_l = "Dune Sharks: Guard Left"
boss1_guard_r_1 = "Dune Sharks: Guard Right #1"
boss1_guard_r_2 = "Dune Sharks: Guard Right #2"

boss1_bridge = "Dune Sharks: Bridge"
boss1_bridge_n = "Dune Sharks: Bridge Left"
boss1_secret = "Dune Sharks: Secret"

# Passage
p_ent2_secret = "SP: Entrance Secret"
p_mid1_1 = "SP: Slime Cavern #1"
p_mid1_2 = "SP: Slime Cavern #2"
p_mid2_1 = "SP: Arrow Cavern Entrance"
p_mid2_2 = "SP: Arrow Cavern End #1"
p_mid2_3 = "SP: Arrow Cavern End #2"
p_mid2_4 = "SP: Arrow Cavern End #3"
p_mid3_secret_1 = "SP: Middle Secret Left"
p_mid3_secret_2 = "SP: Middle Secret Middle"
p_mid3_secret_3 = "SP: Middle Secret Right"
p_mid3_secret_4 = "SP: Middle Secret Far Right"
p_mid4_1 = "SP: Bridge Cavern North"
p_mid4_2 = "SP: Bridge Cavern Bridge"
p_mid4_3 = "SP: Bridge Cavern South #1"
p_mid4_4 = "SP: Bridge Cavern South #2"
p_mid5_1 = "SP: Temple Stockpile North"
p_mid5_2 = "SP: Temple Stockpile East"
p_mid5_secret = "SP: Temple Stockpile Secret"
p_end1_secret = "SP: End Secret"
p_end3_1 = "SP: End Hidden #1"
p_end3_2 = "SP: End Hidden #2"

p_puzzle_1 = "SP: Puzzle Reward #1"
p_puzzle_2 = "SP: Puzzle Reward #2"
p_puzzle_3 = "SP: Puzzle Reward #3"
p_puzzle_4 = "SP: Puzzle Reward #4"

# Temple Entrance
temple_entrance_l = "Temple Entrance: Lazy Guard #1"
temple_entrance_r = "Temple Entrance: Lazy Guard #2"

# Temple Floor 1
t1_above_s_bridge = "TF1: Above South Bridge"
t1_s_bridge_1 = "TF1: South Bridge Left #1"
t1_s_bridge_2 = "TF1: South Bridge Left #2"
t1_s_bridge_3 = "TF1: South Bridge Left #3"
t1_s_bridge_4 = "TF1: South Bridge Middle #1"
t1_s_bridge_5 = "TF1: South Bridge Middle #2"
t1_s_bridge_6 = "TF1: South Bridge Middle #3"
t1_sw_sun_room_1 = "TF1: SW Sunbeam #1"
t1_sw_sun_room_2 = "TF1: SW Sunbeam #2"
t1_sw_corner_room = "TF1: SW Corner"
t1_sw_hidden_room_1 = "TF1: SW Cache #1"
t1_sw_hidden_room_2 = "TF1: SW Cache #2"
t1_sw_hidden_room_3 = "TF1: SW Cache #3"
t1_sw_hidden_room_4 = "TF1: SW Cache #4"

t1_sw_sdoor_1 = "TF1: SW Gate Left of Spikes"
t1_sw_sdoor_2 = "TF1: SW Gate Mana Drain Panel"
t1_sw_sdoor_3 = "TF1: SW Gate Center"
t1_sw_sdoor_4 = "TF1: SW Gate Right Bottom"
t1_sw_sdoor_5 = "TF1: SW Gate Right Top"

t1_double_gate_1 = "TF1: West Node Room Spikes"
t1_double_gate_2 = "TF1: West Node Room #1"
t1_double_gate_3 = "TF1: West Node Room #2"
t1_double_gate_hidden = "TF1: West Node Room Behind Scenery"
t1_behind_bars_entrance = "TF1: West Node Room Behind Bars"
t1_e_of_double_gate_room_1 = "TF1: Fireball Runway Room Right"
t1_e_of_double_gate_room_2 = "TF1: Fireball Runway Room Bottom #1"
t1_e_of_double_gate_room_3 = "TF1: Fireball Runway Room Bottom #2"
t1_e_of_double_gate_room_4 = "TF1: Fireball Runway Room Bottom #3"
t1_mana_drain_fire_trap = "TF1: Fireball Runway"
t1_mana_drain_fire_trap_reward_1 = "TF1: Fireball Runway End #1"
t1_mana_drain_fire_trap_reward_2 = "TF1: Fireball Runway End #2"
t1_mana_drain_fire_trap_passage = "TF1: Fireball Runway Passage"

t1_double_gate_behind_block = "TF1: West Node Room Behind Block"
t1_s_of_sun_turret = "TF1: NW Tower South"
t1_sun_turret_1 = "TF1: NW Tower NW"
t1_sun_turret_2 = "TF1: NW Tower North"
t1_sun_turret_3 = "TF1: NW Tower Far North"
t1_fire_trap_by_sun_turret_1 = "TF1: West Fireball Trap Top #1"
t1_fire_trap_by_sun_turret_2 = "TF1: West Fireball Trap Top #2"
t1_fire_trap_by_sun_turret_3 = "TF1: West Fireball Trap Top #3"
t1_fire_trap_by_sun_turret_4 = "TF1: West Fireball Trap Bottom"

t1_ice_turret_1 = "TF1: East Tower Room Left"
t1_ice_turret_2 = "TF1: East Tower Right"
t1_telarian_1 = "TF1: Telarian Left #1"
t1_telarian_2 = "TF1: Telarian Left #2"
t1_telarian_3 = "TF1: Telarian Left #3"
t1_telarian_4 = "TF1: Telarian Right #1"
t1_telarian_5 = "TF1: Telarian Right #2"
t1_boulder_hallway_by_ice_turret_1 = "TF1: East Boulder Hallway Top #1"
t1_boulder_hallway_by_ice_turret_2 = "TF1: East Boulder Hallway Top #2"
t1_boulder_hallway_by_ice_turret_3 = "TF1: East Boulder Hallway Top #3"
t1_boulder_hallway_by_ice_turret_4 = "TF1: East Boulder Hallway"
t1_ice_turret_boulder_break_block = "TF1: East Boulder Breakable Block"
t1_n_sunbeam = "TF1: North Sunbeam"
t1_n_sunbeam_treasure_1 = "TF1: North Sunbeam Treasure Middle"
t1_n_sunbeam_treasure_2 = "TF1: North Sunbeam Treasure Right"
t1_n_sunbeam_treasure_3 = "TF1: North Sunbeam Treasure Left"

t1_n_cache_by_ice_turret_1 = "TF1: East Tower NW Gate Left"
t1_n_cache_by_ice_turret_2 = "TF1: East Tower NW Gate Middle #1"
t1_n_cache_by_ice_turret_3 = "TF1: East Tower NW Gate Middle #2"
t1_n_cache_by_ice_turret_4 = "TF1: East Tower NW Gate Right Bottom"
t1_n_cache_by_ice_turret_5 = "TF1: East Tower NW Gate Right Top"

t1_s_cache_by_ice_turret_1 = "TF1: East Tower SE Gate Left"
t1_s_cache_by_ice_turret_2 = "TF1: East Tower SE Gate Right #1"
t1_s_cache_by_ice_turret_3 = "TF1: East Tower SE Gate Right #2"

t1_ledge_after_block_trap_1 = "TF1: East Block Traps #1"
t1_ledge_after_block_trap_2 = "TF1: East Block Traps #2"
t1_ice_block_chamber_1 = "TF1: Miniboss Room Top-Left"
t1_ice_block_chamber_2 = "TF1: Miniboss Room Top-Right"
t1_ice_block_chamber_3 = "TF1: Miniboss Room Bottom"
t1_node_2_1 = "TF1: Node 2 #1"
t1_node_2_2 = "TF1: Node 2 #2"
t1_node_2_passage_1 = "TF1: Node 2 Passage #1"
t1_node_2_passage_2 = "TF1: Node 2 Passage #2"
t1_node_2_passage_3 = "TF1: Node 2 Passage #3"
t1_e_gold_beetles = "TF1: East Enemy Jail"

t1_sun_block_hall_1 = "TF1: Sun Block Hall Alcove"
t1_sun_block_hall_2 = "TF1: Sun Block Hall Middle"
t1_sun_block_hall_3 = "TF1: Sun Block Hall Right #1"
t1_sun_block_hall_4 = "TF1: Sun Block Hall Right #2"

t1_telarian_ice = "TF1: Telarian Ice Block"
t1_ice_block_chamber_ice = "TF1: Miniboss Room Ice Block"

t1_w_puzzle_1 = "TF1: West Puzzle Reward #1"
t1_w_puzzle_2 = "TF1: West Puzzle Reward #2"
t1_w_puzzle_3 = "TF1: West Puzzle Reward #3"
t1_w_puzzle_4 = "TF1: West Puzzle Reward #4"
t1_e_puzzle_1 = "TF1: East Puzzle Reward #1"
t1_e_puzzle_2 = "TF1: East Puzzle Reward #2"
t1_e_puzzle_3 = "TF1: East Puzzle Reward #3"
t1_e_puzzle_4 = "TF1: East Puzzle Reward #4"

# Boss 2 Defeated
boss2_nw = "Krilith: NW Ice Block"
boss2_se = "Krilith: SE Ice Block"

# Temple Floor 2
t2_n_of_portal = "TF2: North of Portal"
t2_s_of_portal = "TF2: South of Portal"
t2_w_spike_trap_1 = "TF2: West Spike Trap #1"
t2_w_spike_trap_2 = "TF2: West Spike Trap #2"
t2_nw_puzzle_cache_1 = "TF2: NW Puzzle Cache #1"
t2_nw_puzzle_cache_2 = "TF2: NW Puzzle Cache #2"
t2_nw_puzzle_cache_3 = "TF2: NW Puzzle Cache #3"
t2_nw_puzzle_cache_4 = "TF2: NW Puzzle Cache #4"
t2_nw_puzzle_cache_5 = "TF2: NW Puzzle Cache #5"
t2_nw_of_s_ice_turret = "TF2: Across from West Rune Panel"
t2_w_hall_dead_end_1 = "TF2: West T Hall Left #1"
t2_w_hall_dead_end_2 = "TF2: West T Hall Left #2"
t2_w_hall_dead_end_3 = "TF2: West T Hall Left #3"
t2_w_hall_dead_end_4 = "TF2: West T Hall Right"
t2_w_hall_dead_end_5 = "TF2: West T Hall Left #4"
t2_n_of_sw_gate_1 = "TF2: West Tower SW #1"
t2_n_of_sw_gate_2 = "TF2: West Tower SW #2"
t2_fire_trap_maze_1 = "TF2: Fire Trap Maze Balcony #1"
t2_fire_trap_maze_2 = "TF2: Fire Trap Maze Balcony #2"
t2_fire_trap_maze_3 = "TF2: Middle Fireball Runway Top"
t2_fire_trap_maze_4 = "TF2: Middle Fireball Runway Bottom"
t2_fire_trap_maze_5 = "TF2: Fire Trap Maze Top"
t2_fire_trap_maze_6 = "TF2: Fire Trap Maze Bottom"
t2_teleporter = "TF2: Return Portal Room"
t2_e_outside_gold_beetle_cage_1 = "TF2: East Enemy Jail #1"
t2_e_outside_gold_beetle_cage_2 = "TF2: East Enemy Jail #2"
t2_boulder_chamber_1 = "TF2: East Miniboss NW"
t2_boulder_chamber_2 = "TF2: East Miniboss Right Boulder"
t2_boulder_chamber_3 = "TF2: East Miniboss NE"
t2_boulder_chamber_4 = "TF2: East Miniboss Bottom"
t2_s_balcony_1 = "TF2: South Balcony Left"
t2_s_balcony_2 = "TF2: South Balcony Right"
t2_se_banner_chamber_1 = "TF2: SE Banner Chamber Banner #1"
t2_se_banner_chamber_2 = "TF2: SE Banner Chamber Banner #2"
t2_se_banner_chamber_3 = "TF2: SE Banner Chamber Banner #3"
t2_se_banner_chamber_4 = "TF2: SE Banner Chamber NW"
t2_se_banner_chamber_5 = "TF2: SE Banner Chamber NE"
t2_se_fireball_hall = "TF2: SE Fireball Hall"

t2_sw_gate = "TF2: SW Shortcut Gate"
t2_s_node_room_1 = "TF2: South Node Right #1"
t2_s_node_room_2 = "TF2: South Node Right #2"
t2_s_node_room_3 = "TF2: South Node Right #3"
t2_s_sunbeam_1 = "TF2: South Sunbeam #1"
t2_s_sunbeam_2 = "TF2: South Sunbeam #2"
t2_sw_jail_1 = "TF2: SW Cell #2"
t2_sw_jail_2 = "TF2: SW Cell #1"
t2_left_of_pof_switch_1 = "TF2: PoF Switch Left #1"
t2_left_of_pof_switch_2 = "TF2: PoF Switch Left #2"
t2_right_of_pof_switch = "TF2: PoF Switch Spikes"

t2_nw_ice_turret_1 = "TF2: NW Towers Top Room #2"
t2_nw_ice_turret_2 = "TF2: NW Towers Top Room #3"
t2_nw_ice_turret_3 = "TF2: NW Towers Top Room #4"
t2_nw_ice_turret_4 = "TF2: NW Towers Top Room #1"
t2_nw_under_block = "TF2: NW Block Trap"
t2_nw_gate_1 = "TF2: NW Pillar Gate #1"
t2_nw_gate_2 = "TF2: NW Pillar Gate #2"
t2_nw_gate_3 = "TF2: NW Pillar Gate"

t2_boulder_room_1 = "TF2: Hidden Boulder Room Top"
t2_boulder_room_2 = "TF2: Hidden Boulder Room Right"
t2_boulder_room_block = "TF2: Hidden Boulder Room Under Block"
t2_mana_drain_fire_trap_1 = "TF2: North Fireball Runway #1"
t2_mana_drain_fire_trap_2 = "TF2: North Fireball Runway #2"
t2_jones_hallway = "TF2: Indiana Jones Hallway"
t2_gold_beetle_barricade = "TF2: West Enemy Jail Barricade"
t2_w_gold_beetle_room_1 = "TF2: West Enemy Jail #1"
t2_w_gold_beetle_room_2 = "TF2: West Enemy Jail #2"
t2_w_gold_beetle_room_3 = "TF2: West Enemy Jail #3"
t2_w_gold_beetle_room_4 = "TF2: West Enemy Jail #4"

t2_w_ice_block_gate = "TF2: West Ice Block Gate"
t2_e_ice_block_gate = "TF2: East Ice Block Gate"

t2_se_light_bridge_1 = "TF2: SE Light Bridge Left"
t2_se_light_bridge_2 = "TF2: SE Light Bridge Right"
t2_s_light_bridge_1 = "TF2: South Light Bridge #1"
t2_s_light_bridge_2 = "TF2: South Light Bridge #2"
t2_portal_gate = "TF2: Portal Gate"

t2_floor3_cache_1 = "TF2: Ornate Room #1"
t2_floor3_cache_2 = "TF2: Ornate Room #2"
t2_floor3_cache_3 = "TF2: Ornate Room #3"
t2_floor3_cache_4 = "TF2: Ornate Room #4"
t2_floor3_cache_5 = "TF2: Ornate Room #5"
t2_floor3_cache_6 = "TF2: Ornate Room #6"
t2_floor3_cache_gate = "TF2: Ornate Room Pillar Gate"

t2_n_puzzle_1 = "TF2: North Puzzle Reward #1"
t2_n_puzzle_2 = "TF2: North Puzzle Reward #2"
t2_n_puzzle_3 = "TF2: North Puzzle Reward #3"
t2_n_puzzle_4 = "TF2: North Puzzle Reward #4"
t2_nw_puzzle_1 = "TF2: NW Puzzle Reward #1"
t2_nw_puzzle_2 = "TF2: NW Puzzle Reward #2"
t2_nw_puzzle_3 = "TF2: NW Puzzle Reward #3"
t2_nw_puzzle_4 = "TF2: NW Puzzle Reward #4"
t2_e_puzzle_1 = "TF2: East Puzzle Reward #1"
t2_e_puzzle_2 = "TF2: East Puzzle Reward #2"
t2_e_puzzle_3 = "TF2: East Puzzle Reward #3"
t2_e_puzzle_4 = "TF2: East Puzzle Reward #4"
t2_sw_puzzle_1 = "TF2: SW Puzzle Reward #1"
t2_sw_puzzle_2 = "TF2: SW Puzzle Reward #2"
t2_sw_puzzle_3 = "TF2: SW Puzzle Reward #3"
t2_sw_puzzle_4 = "TF2: SW Puzzle Reward #4"

# Temple Floor 3
t3_s_balcony_turret_1 = "TF3: South Balcony Tower #1"
t3_s_balcony_turret_2 = "TF3: South Balcony Tower #2"
t3_n_turret_1 = "TF3: North Tower"
t3_n_turret_2 = "TF3: North Boulder"
t3_boulder_block = "TF3: Boulder Block"
t3_e_turret_spikes = "TF3: East Tower"

t3_s_gate = "TF3: South Pillar Gate"
t3_n_node_blocks_1 = "TF3: Sun Block Wall Far Left"
t3_n_node_blocks_2 = "TF3: Sun Block Wall Left"
t3_n_node_blocks_3 = "TF3: Sun Block Wall Middle"
t3_n_node_blocks_4 = "TF3: Sun Block Wall Right"
t3_n_node_blocks_5 = "TF3: Sun Block Wall Far Right"

t3_s_node_cache_1 = "TF3: South Node Cache Left"
t3_s_node_cache_2 = "TF3: South Node Cache Right #1"
t3_s_node_cache_3 = "TF3: South Node Cache Right #2"

t3_m_balcony_corridor = "TF3: NE Balcony Corridor"

t3_n_node_1 = "TF3: North Node #1"
t3_n_node_2 = "TF3: North Node #2"
t3_n_node_3 = "TF3: North Node #3"

t3_boss_fall_1_1 = "TF3: Right Boss Platform Fall #1"
t3_boss_fall_1_2 = "TF3: Right Boss Platform Fall #2"
t3_boss_fall_1_3 = "TF3: Right Boss Platform Fall #3"

t3_boss_fall_2_1 = "TF3: Top Boss Platform Fall #1"
t3_boss_fall_2_2 = "TF3: Top Boss Platform Fall #2"
t3_boss_fall_2_3 = "TF3: Top Boss Platform Fall #3"

t3_boss_fall_3_1 = "TF3: Left Boss Platform Fall #1"
t3_boss_fall_3_2 = "TF3: Left Boss Platform Fall #2"
t3_boss_fall_3_3 = "TF3: Left Boss Platform Fall #3"
t3_boss_fall_3_4 = "TF3: Left Boss Platform Fall #4"

t3_puzzle_1 = "TF3: Puzzle Reward #1"
t3_puzzle_2 = "TF3: Puzzle Reward #2"
t3_puzzle_3 = "TF3: Puzzle Reward #3"
t3_puzzle_4 = "TF3: Puzzle Reward #4"

# PoF
pof_1_ent_1 = "PoF L1: Entrance #1"
pof_1_ent_2 = "PoF L1: Entrance #2"
pof_1_ent_3 = "PoF L1: Entrance #3"
pof_1_ent_4 = "PoF L1: Entrance #4"
pof_1_ent_5 = "PoF L1: Entrance #5"
pof_1_sw_left_2 = "PoF L1: SW #2"
pof_1_sw_left_3 = "PoF L1: SW #3"
pof_1_sw_left_1 = "PoF L1: SW #1"
pof_1_sw_left_4 = "PoF L1: SW #4"
pof_1_sw_left_5 = "PoF L1: SW #5"
pof_1_sw_left_6 = "PoF L1: SW #6"
pof_1_sw_left_7 = "PoF L1: SW #7"
pof_1_sw_left_8 = "PoF L1: SW #8"
pof_1_sw_left_9 = "PoF L1: SW #9"
pof_1_sw_left_10 = "PoF L1: SW #10"
pof_1_sw_left_11 = "PoF L1: SW #11"
pof_1_s_1 = "PoF L1: South Wall #1"
pof_1_s_2 = "PoF L1: South Wall #2"
pof_1_s_3 = "PoF L1: South Wall #3"
pof_1_s_4 = "PoF L1: South Wall #4"
pof_1_s_5 = "PoF L1: South Wall #5"
pof_1_s_6 = "PoF L1: South Wall #6"
pof_1_s_7 = "PoF L1: South Wall #7"
pof_1_s_8 = "PoF L1: South Wall #8"
pof_1_s_9 = "PoF L1: South Wall #9"
pof_1_s_10 = "PoF L1: South Wall #10"
pof_1_s_11 = "PoF L1: South Wall #11"
pof_1_s_12 = "PoF L1: South Wall #12"
pof_1_s_13 = "PoF L1: South Wall #13"

pof_1_confuse_corner_1 = "PoF L1: Confuse Corner #1"
pof_1_confuse_corner_2 = "PoF L1: Confuse Corner #2"
pof_1_confuse_corner_3 = "PoF L1: Confuse Corner #3"
pof_1_confuse_corner_4 = "PoF L1: Confuse Corner #4"
pof_1_n_1 = "PoF L1: North 3x3 #1"
pof_1_n_2 = "PoF L1: North 3x3 #2"
pof_1_n_3 = "PoF L1: North 3x3 #3"
pof_1_n_4 = "PoF L1: North 3x3 #4"
pof_1_n_5 = "PoF L1: North 3x3 #5"
pof_1_n_6 = "PoF L1: North 3x3 #6"
pof_1_n_7 = "PoF L1: North 3x3 #7"
pof_1_n_8 = "PoF L1: North 3x3 #8"
pof_1_n_9 = "PoF L1: North 3x3 #9"
pof_1_c_hall_1 = "PoF L1: C Hall #1"
pof_1_c_hall_2 = "PoF L1: C Hall #2"
pof_1_c_hall_3 = "PoF L1: C Hall #3"
pof_1_c_hall_4 = "PoF L1: C Hall #4"
pof_1_c_hall_5 = "PoF L1: C Hall #5"
pof_1_c_hall_6 = "PoF L1: C Hall #6"

pof_1_end_1 = "PoF L1: End #1"
pof_1_end_2 = "PoF L1: End #2"
pof_1_end_3 = "PoF L1: End #3"
pof_1_end_4 = "PoF L1: End #4"
pof_1_end_5 = "PoF L1: End #5"

pof_2_ent_1 = "PoF L2: Entrance #1"
pof_2_ent_2 = "PoF L2: Entrance #2"
pof_2_ent_3 = "PoF L2: Entrance #3"
pof_2_ent_4 = "PoF L2: Entrance #4"
pof_2_ent_5 = "PoF L2: Entrance #5"
pof_2_ent_6 = "PoF L2: Entrance #6"
pof_2_confuse_hall_1 = "PoF L2: East Hall #1"
pof_2_confuse_hall_2 = "PoF L2: East Hall #2"
pof_2_confuse_hall_3 = "PoF L2: East Hall #3"
pof_2_confuse_hall_4 = "PoF L2: East Hall #4"
pof_2_sw_1 = "PoF L2: SW #1"
pof_2_sw_2 = "PoF L2: SW #2"
pof_2_sw_3 = "PoF L2: SW #3"
pof_2_sw_4 = "PoF L2: SW #4"
pof_2_ne_1 = "PoF L2: NE #1"
pof_2_ne_2 = "PoF L2: NE #2"
pof_2_ne_3 = "PoF L2: NE #3"
pof_2_ne_4 = "PoF L2: NE #4"

pof_3_safety_room_1 = "PoF L3: Start #1"
pof_3_safety_room_2 = "PoF L3: Start #2"
pof_3_safety_room_3 = "PoF L3: Start #3"
pof_3_end_1 = "PoF L3: Exit Top"
pof_3_end_2 = "PoF L3: Exit Left #1"
pof_3_end_3 = "PoF L3: Exit Left #2"
pof_3_end_4 = "PoF L3: Exit Right"
pof_3_end_5 = "PoF L3: Exit Bottom"

pof_puzzle_1 = "PoF L2: Puzzle Reward #1"
pof_puzzle_2 = "PoF L2: Puzzle Reward #2"
pof_puzzle_3 = "PoF L2: Puzzle Reward #3"
pof_puzzle_4 = "PoF L2: Puzzle Reward #4"

# Enemy locations
c3_miniboss_tick_1 = "CL3: Miniboss Loot #1"
c3_miniboss_tick_2 = "CL3: Miniboss Loot #2"
c3_tower_plant = "CL3: Exit Tower Loot"
c3_tower_plant_small_1 = "CL3: Broken Bridge NW Mini Flower Loot"
c3_tower_plant_small_2 = "CL3: Broken Bridge West Mini Flower Loot"
c3_tower_plant_small_3 = "CL3: NE Mini Flowers NW Loot"
c3_tower_plant_small_4 = "CL3: NE Mini Flowers SW Loot"
c3_tower_plant_small_5 = "CL3: NE Mini Flowers NE Loot"
c3_tower_plant_small_6 = "CL3: NE Mini Flowers SE Loot"
c3_tower_plant_small_7 = "CL3: Trapped Guard SW Mini Flower Loot"
c3_tower_plant_small_8 = "CL3: Trapped Guard East Mini Flower Loot"

c2_miniboss_maggot_w_1 = "CL2: West Miniboss Loot #1"
c2_miniboss_maggot_w_2 = "CL2: West Miniboss Loot #2"
c2_miniboss_maggot_s_1 = "CL2: South Miniboss Loot #1"
c2_miniboss_maggot_s_2 = "CL2: South Miniboss Loot #2"
c2_miniboss_tick_1 = "CL2: Middle Miniboss Loot #1"
c2_miniboss_tick_2 = "CL2: Middle Miniboss Loot #2"
c2_tower_plant_1 = "CL2: North Tower Loot"
c2_tower_plant_2 = "CL2: SW Tower Loot"
c2_tower_plant_3 = "CL2: East Tower Loot"
c2_tower_plant_small_1 = "CL2: NW Mini Flowers Leftmost Flower Loot"
c2_tower_plant_small_2 = "CL2: NW Mini Flowers Middle-Right Flower Loot"
c2_tower_plant_small_3 = "CL2: North Bridge NW Mini Flower Loot"
c2_tower_plant_small_4 = "CL2: Pumps Lever Mini Flower Loot"
c2_tower_plant_small_5 = "CL2: North Bridge NE Mini Flower Loot"
c2_tower_plant_small_6 = "CL2: North Bridge North Mini Flower Loot"
c2_tower_plant_small_7 = "CL2: NW Mini Flowers Middle-Left Flower Loot"
c2_tower_plant_small_8 = "CL2: Mini Flower by Green Bridge Switch Loot"
c2_tower_plant_small_9 = "CL2: Mini Flower West of Green Bridge Switch Loot"
c2_tower_plant_small_10 = "CL2: Mini Flower by Puzzle Loot"
c2_tower_plant_small_11 = "CL2: NW Mini Flowers Rightmost Flower Loot"
c2_tower_plant_small_12 = "CL2: Mini Flower North of South Save Loot"
c2_tower_plant_small_13 = "CL2: North Bridge SE Mini Flower Loot"
c2_tower_plant_small_14 = "CL2: North Bridge South Mini Flower Loot"
c2_tower_plant_small_15 = "CL2: North Bridge SW Mini Flower Loot"
c2_tower_plant_small_16 = "CL2: Mini Flower South of South Save Loot"
c2_tower_plant_small_17 = "CL2: Middle Miniboss Arena Left Mini Flower Loot"
c2_tower_plant_small_18 = "CL2: Middle Miniboss Arena Right Mini Flower Loot"
c2_tower_plant_small_19 = "CL2: South Miniboss Area Left Mini Flower Loot"
c2_tower_plant_small_20 = "CL2: SE Mini Flowers NW Flower Loot"
c2_tower_plant_small_21 = "CL2: SE Mini Flowers NE Flower Loot"
c2_tower_plant_small_22 = "CL2: South Miniboss Area Right Mini Flower Loot"
c2_tower_plant_small_23 = "CL2: SE Mini Flowers South Flower Loot"

c1_miniboss_maggot_s_1 = "CL1: South Miniboss Loot #1"
c1_miniboss_maggot_s_2 = "CL1: South Miniboss Loot #2"
c1_miniboss_maggot_ne_1 = "CL1: NE Miniboss Loot #1"
c1_miniboss_maggot_ne_2 = "CL1: NE Miniboss Loot #2"
c1_miniboss_tick_1 = "CL1: NW Miniboss Loot #1"
c1_miniboss_tick_2 = "CL1: NW Miniboss Loot #2"
c1_tower_plant_1 = "CL1: Middle Tower Loot"
c1_tower_plant_2 = "CL1: NE Miniboss Area Tower Loot"
c1_tower_plant_3 = "CL1: SW Tower Loot"
c1_tower_plant_4 = "CL1: NE Tower Loot"
c1_tower_plant_small_1 = "CL1: NE Mini Flowers Middle-Left Flower Loot"
c1_tower_plant_small_2 = "CL1: NE Mini Flowers Leftmost Flower Loot"
c1_tower_plant_small_3 = "CL1: NE Miniboss Area NW Mini Flower Loot"
c1_tower_plant_small_4 = "CL1: NE Miniboss Area NE Mini Flower Loot"
c1_tower_plant_small_5 = "CL1: West Mini Flowers Top Flower Loot"
c1_tower_plant_small_6 = "CL1: West Mini Flowers Right Flower Loot"
c1_tower_plant_small_7 = "CL1: West Mini Flowers Bottom Flower Loot"
c1_tower_plant_small_8 = "CL1: West Mini Flowers Left Flower Loot"
c1_tower_plant_small_9 = "CL1: NE Miniboss Area SW Mini Flower Loot"
c1_tower_plant_small_10 = "CL1: NE Miniboss Area SE Mini Flower Loot"
c1_tower_plant_small_11 = "CL1: South Miniboss Area Top Mini Flower Loot"
c1_tower_plant_small_12 = "CL1: South Miniboss Area Bottom Mini Flower Loot"
c1_tower_plant_small_13 = "CL1: NE Mini Flowers Middle-Right Flower Loot"
c1_tower_plant_small_14 = "CL1: NE Mini Flowers Rightmost Flower Loot"

b1_boss_worm_1_1 = "1st Dune Shark Loot #1"
b1_boss_worm_1_2 = "1st Dune Shark Loot #2"
b1_boss_worm_2_1 = "2nd Dune Shark Loot #1"
b1_boss_worm_2_2 = "2nd Dune Shark Loot #2"
b1_boss_worm_3_1 = "3rd Dune Shark Loot #1"
b1_boss_worm_3_2 = "3rd Dune Shark Loot #2"
b1_boss_worm_4_1 = "4th Dune Shark Loot #1"
b1_boss_worm_4_2 = "4th Dune Shark Loot #2"
b1_boss_worm_5_1 = "5th Dune Shark Loot #1"
b1_boss_worm_5_2 = "5th Dune Shark Loot #2"
b1_boss_worm_6_1 = "6th Dune Shark Loot #1"
b1_boss_worm_6_2 = "6th Dune Shark Loot #2"
b1_boss_worm_7_1 = "7th Dune Shark Loot #1"
b1_boss_worm_7_2 = "7th Dune Shark Loot #2"
b1_boss_worm_key = "Final Dune Shark Loot"

p_tower_plant_small_1 = "SP: Bridge Cavern North Mini Flower Loot"
p_tower_plant_small_2 = "SP: Bridge Cavern Top-Right Mini Flower Loot"
p_tower_plant_small_3 = "SP: Bridge Cavern Middle-Left Mini Flower Loot"
p_tower_plant_small_4 = "SP: Bridge Cavern Bottom-Upper Mini Flower Loot"
p_tower_plant_small_5 = "SP: Bridge Cavern South Mini Flower Loot"
p_tower_plant_small_6 = "SP: Bridge Cavern Middle-Right Mini Flower Loot"

t1_miniboss_mummy_1 = "TF1: Miniboss Loot #1"
t1_miniboss_mummy_2 = "TF1: Miniboss Loot #2"
t1_tower_fire = "TF1: NW Tower Loot"
t1_tower_ice = "TF1: East Tower Loot"

t2_miniboss_mummy_w_1 = "TF2: West Miniboss Loot #1"
t2_miniboss_mummy_w_2 = "TF2: West Miniboss Loot #2"
t2_miniboss_mummy_e_1 = "TF2: East Miniboss Loot #1"
t2_miniboss_mummy_e_2 = "TF2: East Miniboss Loot #2"
t2_tower_fire = "TF2: NE Tower Loot"
t2_tower_ice_1 = "TF2: NW Towers Left Tower Loot"
t2_tower_ice_2 = "TF2: NW Towers Right Tower Loot"
t2_tower_ice_3 = "TF2: West Tower Loot"
t2_tower_mana_1 = "TF2: Far West Tower Loot"
t2_tower_mana_2 = "TF2: Middle Tower Loot"
t2_tower_mana_3 = "TF2: SW Tower Loot"

t3_tower_fire_1 = "TF3: Far East Tower Loot"
t3_tower_fire_2 = "TF3: West Tower Loot"
t3_tower_ice_1 = "TF3: North Tower Loot"
t3_tower_ice_2 = "TF3: Middle Towers Top Tower Loot"
t3_tower_ice_3 = "TF3: Middle Towers Bottom Tower Loot"
t3_tower_mana_1 = "TF3: East Tower Loot"
t3_tower_mana_2 = "TF3: South Tower Loot"

b3_tower_fire_1 = "Sha'Rand: Top Platform Tower Loot"
b3_tower_fire_2 = "Sha'Rand: Right Platform Tower Loot"
b3_tower_fire_3 = "Sha'Rand: Left Platform Tower Loot"

# Random locations
rloc_t3_entrance = "Temple 3 Entrance"
rloc_squire = "Cave 3 Squire"
rloc_c3_secret_n = "Cave 3 Secret 1"
rloc_c3_secret_nw = "Cave 3 Secret 2"
rloc_c3_secret_s = "Cave 3 Secret 3"
rloc_c3_puzzle = "Cave 3 Puzzle 1"
rloc_pan = "Frying Pan"

rloc_c2_portal = "Cave 2 Portal"
rloc_c2_keystone = "Cave 2 Keystone"
rloc_c2_secret_1 = "Cave 2 Secret 1"
rloc_c2_secret_2 = "Cave 2 Secret 2"
rloc_c2_secret_3 = "Cave 2 Secret 3"
rloc_c2_hidden_room = "Cave 2 Hidden Room"
rloc_c2_puzzle = "Cave 2 Puzzle 1"

rloc_c1_portal = "Cave 1 Portal"
rloc_c1_keystone = "Cave 1 Keystone"
rloc_c1_secret_1 = "Cave 1 Secret 1"
rloc_c1_secret_2 = "Cave 1 Secret 2"
rloc_c1_secret_3 = "Cave 1 Secret 3"
rloc_c1_secret_4 = "Cave 1 Secret 4"
rloc_c1_secret_5 = "Cave 1 Secret 5"
rloc_c1_secret_6 = "Cave 1 Secret 6"
rloc_c1_hidden_room = "Cave 1 Hidden Room"
rloc_c1_exit = "Cave 1 Exit"
rloc_c1_puzzle_n = "Cave 1 Puzzle 1"
rloc_c1_puzzle_e = "Cave 1 Puzzle 2"

rloc_b1_secret = "Temple Boss 1 Secret 1"

rloc_passage_entrance = "Passage Entrance"
rloc_passage_middle = "Passage Middle"
rloc_passage_end = "Passage End"
rloc_p_secret_1 = "Passage Secret 1"
rloc_p_secret_2 = "Passage Secret 2"
rloc_p_secret_3 = "Passage Secret 3"
rloc_p_secret_4 = "Passage Secret 4"
rloc_p_secret_5 = "Passage Secret 5"
rloc_p_secret_6 = "Passage Secret 6"
rloc_p_secret_7 = "Passage Secret 7"
rloc_p_alley = "Passage Hidden Room"
rloc_p_puzzle = "Passage Puzzle 1"

rloc_t1_portal = "Temple 1 Portal"
rloc_t1_keystone = "Temple 1 Keystone"
rloc_t1_silver_key_s = "Temple 1 South Silver Key"
rloc_t1_silver_key_n = "Temple 1 North Silver Key"
rloc_t1_silver_key_ice_turret = "Temple 1 Ice Turret Silver Key"
rloc_t1_silver_key_funky = "Temple 1 Funky Silver Key"
rloc_t1_gold_key = "Temple 1 Gold Key"
rloc_t1_ore_funky = "Temple 1 Funky Ore"
rloc_t1_ore_e = "Temple 1 East Ore"
rloc_t1_mirror = "Temple 1 Mirror"
rloc_t1_puzzle = "Temple 1 Puzzle 1"
rloc_t1_puzzle_spawn = "Temple 1 Puzzle Spawn"
rloc_t1_puzzle_w = "Temple 1 Puzzle 1"
rloc_t1_puzzle_e = "Temple 1 Puzzle 2"
rloc_t1_sw_hidden_room = "Temple 1 Hidden Room"
rloc_t1_sw_hidden_room_random_node = "Temple 1 Hidden Room Random Node"

rloc_t2_entrance = "Temple 2 Entrance"
rloc_t2_portal = "Temple 2 Portal"
rloc_t2_keystone = "Temple 2 Keystone"
rloc_t2_puzzle_spawn_1 = "Temple 2 Puzzle Spawn EW"
rloc_t2_puzzle_spawn_2 = "Temple 2 Puzzle Spawn NS"
rloc_t2_puzzle_n = "Temple 2 Puzzle 1"
rloc_t2_puzzle_nw = "Temple 2 Puzzle 2"
rloc_t2_puzzle_e = "Temple 2 Puzzle 3"
rloc_t2_puzzle_sw = "Temple 2 Puzzle 4"
rloc_t2_jones_reward = "Temple 2 Jones Reward"
rloc_t2_gold_key = "Temple 2 Gold Key"
rloc_t2_silver_key_1 = "Temple 2 Silver Key 1"
rloc_t2_silver_key_2 = "Temple 2 Silver Key 2"
rloc_t2_pickaxe = "Pickaxe"
rloc_t2_w_hidden_room = "Temple 2 Hidden Room"

rloc_t3_s_beam_1 = "Temple 3 S Beam 1"
rloc_t3_s_beam_2 = "Temple 3 S Beam 2"
rloc_t3_s_beam_3 = "Temple 3 S Beam 3"
rloc_t3_s_beam_4 = "Temple 3 S Beam 4"
rloc_t3_s_beam_5 = "Temple 3 S Beam 5"
rloc_t3_puzzle = "Temple 3 Puzzle 1"

rloc_pof_puzzle = "PoF Puzzle 1"

shop_combo = "Combo Shop"
shop_misc = "Vitality Shop"
shop_off = "Offense Shop"
shop_def = "Defense Shop"

# Event locations
ev_c1_portal = "CL1: Activate Portal"
ev_c2_portal = "CL2: Activate Portal"
ev_c3_portal = "CL3: Activate Portal"
ev_t1_portal = "TF1: Activate Portal"
ev_t2_portal = "TF2: Activate Portal"
ev_t3_portal = "TF3: Activate Portal"
ev_hub_pof_switch = "Outside: PoF Switch"
ev_cave1_pof_switch = "CL1: PoF Switch"
ev_cave2_pof_switch = "CL2: PoF Switch"
ev_cave3_pof_switch = "CL3: PoF Switch"
ev_temple1_pof_switch = "TF1: PoF Switch"
ev_temple2_pof_switch = "TF2: PoF Switch"
ev_temple_entrance_rock = "Temple Entrance Rock"
ev_t1_n_node = "TF1: North Node"
ev_t1_n_node_n_mirrors = "TF1: North Node North Mirrors"
ev_t1_n_node_s_mirror = "TF1: North Node South Mirror"
ev_t1_s_node = "TF1: South Node"
ev_t2_n_node = "TF2: North Node"
ev_t2_s_node = "TF2: South Node"
ev_t3_n_node = "TF3: North Node"
ev_t3_s_node = "TF3: South Node"
btn_t2_floor_blue = "TF2: Blue Floor Button"
btn_t2_rune_n = "TF2: North Rune Button"
btn_t2_rune_w = "TF2: West Rune Button"
btn_t2_rune_sw = "TF2: SW Rune Button"
btn_t2_rune_se = "TF2: SE Rune Button"
btn_t2_rune_e = "TF2: NE Rune Button"
ev_pof_1_se_room_panel = "PoF Level 1 SE Teleport Room Panel"
ev_pof_1_unlock_exit = "PoF Level 1 Unlock Exit"
ev_pof_2_unlock_exit = "PoF Level 2 Unlock Exit"
ev_pof_end = "PoF L2: End"

ev_beat_boss_1 = "Defeat Dune Sharks"
ev_beat_boss_2 = "Defeat Krilith"
ev_beat_boss_3 = "Defeat Sha'Rand"

# Shared Event Locations
ev_victory = "Victory"
