# Temple of the Sun Pickup Location Names
# Hub
hub_front_of_pof = "Dunes Pyramid of Fear"
hub_behind_temple_entrance = "Dunes Behind Temple Entrance"

hub_behind_shops = "Dunes Behind Shops"
hub_on_rock = "Dunes on Rock"
hub_west_pyramid = "Dunes West Past Rocks By Pyramid"
hub_rocks_south = "Dunes South Behind Rock"
hub_field_south = "Dunes Field South"
hub_field_nw = "Dunes Field NW"
hub_field_north = "Dunes Field North"

hub_pof_reward = "Dunes Pyramid of Fear Reward"

# Cave Level 3
cave3_squire = "Cave Level 3 Squire"
cave3_guard = "Cave Level 3 Guard"
cave3_n = "Cave Level 3 N"
cave3_nw = "Cave Level 3 NW"
cave3_ne = "Cave Level 3 NE"
cave3_se = "Cave Level 3 SE"
cave3_m = "Cave Level 3 Center"
cave3_half_bridge = "Cave Level 3 Half Bridge"
cave3_trapped_guard = "Cave Level 3 Trapped Guard Room"
cave3_outside_guard = "Cave Level 3 Outside Trapped Guard Room"
cave3_secret_n = "Cave Level 3 North Secret Room"
cave3_secret_nw = "Cave Level 3 NW Secret Room"
cave3_secret_s = "Cave Level 3 South Secret Room"

cave3_fall_nw = "Cave Level 3 Dunes Fall Top Left"
cave3_fall_ne = "Cave Level 3 Dunes Fall Top Right"
cave3_fall_sw = "Cave Level 3 Dunes Fall Bottom Left"
cave3_fall_se = "Cave Level 3 Dunes Fall Bottom Right"

cave3_fields_r = "Cave Level 3 Fields East"
cave3_captain = "Cave Level 3 Sun Dock Bottom"
cave3_captain_dock = "Cave Level 3 Sun Dock Top"

cave3_portal_puzzle = "Cave Level 3 Portal Puzzle"  #
cave3_portal_l = "Cave Level 3 Portal Left"
cave3_portal_r = "Cave Level 3 Portal Right"

cave3_secret_1 = "Cave Level 3 Secret 1"
cave3_secret_2 = "Cave Level 3 Secret 2"
cave3_secret_3 = "Cave Level 3 Secret 3"
cave3_secret_4 = "Cave Level 3 Secret 4"
cave3_secret_5 = "Cave Level 3 Secret 5"
cave3_secret_6 = "Cave Level 3 Secret 6"
cave3_secret_7 = "Cave Level 3 Secret 7"
cave3_secret_8 = "Cave Level 3 Secret 8"
cave3_secret_9 = "Cave Level 3 Secret 9"
cave3_secret_10 = "Cave Level 3 Secret 10"
cave3_secret_11 = "Cave Level 3 Secret 11"
cave3_secret_12 = "Cave Level 3 Secret 12"

c3_puzzle_1 = "Cave Level 3 Puzzle Reward 1"
c3_puzzle_2 = "Cave Level 3 Puzzle Reward 2"
c3_puzzle_3 = "Cave Level 3 Puzzle Reward 3"
c3_puzzle_4 = "Cave Level 3 Puzzle Reward 4"

# Cave Level 2
cave2_sw_hidden_room_1 = "Cave Level 2 Southwest Hidden Room Dupe 1"
cave2_sw_hidden_room_2 = "Cave Level 2 Southwest Hidden Room Dupe 2"
cave2_sw_hidden_room_3 = "Cave Level 2 Southwest Hidden Room Dupe 3"
cave2_sw_hidden_room_4 = "Cave Level 2 Southwest Hidden Room Dupe 4"
cave2_below_pumps_1 = "Cave Level 2 North of West Save Top Dupe 1"
cave2_below_pumps_2 = "Cave Level 2 North of West Save Top Dupe 2"
cave2_below_pumps_3 = "Cave Level 2 West Save"
cave2_double_bridge_l_1 = "Cave Level 2 Left of Double Bridge Dupe 1"
cave2_double_bridge_l_2 = "Cave Level 2 Left of Double Bridge Dupe 2"
cave2_double_bridge_m = "Cave Level 2 Double Bridge"
cave2_double_bridge_r = "Cave Level 2 Right of Double Bridge"
cave2_double_bridge_secret = "Cave Level 2 Double Bridge Secret"
cave2_e_1 = "Cave Level 2 East Top Dupe 1"
cave2_e_2 = "Cave Level 2 East Top Dupe 2"
cave2_e_3 = "Cave Level 2 East Bottom Dupe 1"
cave2_e_4 = "Cave Level 2 East Bottom Dupe 2"
cave2_nw_1 = "Cave Level 2 North of West Miniboss Room Left Bottom"
cave2_nw_2 = "Cave Level 2 North of West Miniboss Room Right Bottom"
cave2_nw_3 = "Cave Level 2 North of West Miniboss Room Left Top"
cave2_nw_4 = "Cave Level 2 North of West Miniboss Room Right Top Dupe 1"
cave2_nw_5 = "Cave Level 2 North of West Miniboss Room Right Top Dupe 2"
cave2_sw = "Cave Level 2 East of Puzzle Room"
cave2_w_miniboss_1 = "Cave Level 2 West Miniboss Room Dupe 1"
cave2_w_miniboss_2 = "Cave Level 2 West Miniboss Room Dupe 2"
cave2_w_miniboss_3 = "Cave Level 2 West Miniboss Room Dupe 3"
cave2_w_miniboss_4 = "Cave Level 2 West Miniboss Room Dupe 4"
cave2_red_bridge_1 = "Cave Level 2 Red Bridge Top"
cave2_red_bridge_2 = "Cave Level 2 Red Bridge Bottom"
cave2_red_bridge_3 = "Cave Level 2 Red Bridge Lower Left"
cave2_red_bridge_4 = "Cave Level 2 Red Bridge Upper Left"
cave2_red_bridge_se_1 = "Cave Level 2 SE of Red Bridge Dupe 1"
cave2_red_bridge_se_2 = "Cave Level 2 SE of Red Bridge Dupe 2"
cave2_green_bridge = "Cave Level 2 Green Bridge"
cave2_guard = "Cave Level 2 Guard Room"
cave2_guard_n = "Cave Level 2 Above Guard Room"
cave2_guard_s = "Cave Level 2 Below Guard Room"
cave2_pumps_n = "Cave Level 2 Above Pumps Room"
cave2_secret_ne = "Cave Level 2 NE Secret Room"
cave2_secret_m = "Cave Level 2 Middle Secret Room"
cave2_secret_w = "Cave Level 2 West Secret Room"

cave2_pumps_wall_l = "Cave Level 2 Pumps Inside Left Wall"
cave2_pumps_wall_r = "Cave Level 2 Pumps Inside Right Wall"
cave2_water_n_l = "Cave Level 2 North Underwater Left"
cave2_water_n_r_1 = "Cave Level 2 North Underwater Right Dupe 1"
cave2_water_n_r_2 = "Cave Level 2 North Underwater Right Dupe 2"
cave2_water_s = "Cave Level 2 South Underwater"

c2_puzzle_1 = "Cave Level 2 Puzzle Reward 1"
c2_puzzle_2 = "Cave Level 2 Puzzle Reward 2"
c2_puzzle_3 = "Cave Level 2 Puzzle Reward 3"
c2_puzzle_4 = "Cave Level 2 Puzzle Reward 4"

# Cave Level 1
cave1_n_1 = "Cave Level 1 West NE Dead End Left Dupe 1"
cave1_n_2 = "Cave Level 1 West NE Dead End Left Dupe 2"
cave1_n_3 = "Cave Level 1 West NE Dead End Right"
cave1_n_room_1 = "Cave Level 1 West North Big Room Right Dupe 1"
cave1_n_room_2 = "Cave Level 1 West North Big Room Right Dupe 2"
cave1_n_room_3 = "Cave Level 1 West North Big Room Right Dupe 3"
cave1_n_room_4 = "Cave Level 1 West North Big Room Right Dupe 4"
cave1_w_1 = "Cave Level 1 Far West Dupe 1"
cave1_w_2 = "Cave Level 1 Far West Dupe 2"
cave1_w_by_water_1 = "Cave Level 1 West On North Bank Right"
cave1_w_by_water_2 = "Cave Level 1 West On North Bank Left"
cave1_s_1 = "Cave Level 1 South Miniboss Left Dupe 1"
cave1_s_2 = "Cave Level 1 South Miniboss Left Dupe 2"
cave1_s_3 = "Cave Level 1 South Miniboss Behind Vines"
cave1_s_4 = "Cave Level 1 South Miniboss Right Dupe 1"
cave1_s_5 = "Cave Level 1 South Miniboss Right Dupe 2"
cave1_m = "Cave Level 1 Middle Arrow Trap Dead End"
cave1_secret_nw = "Cave Level 1 NW Secret Room"
cave1_secret_w = "Cave Level 1 West Secret Room"
cave1_secret_m = "Cave Level 1 Middle Secret Room"
cave1_double_room_l = "Cave Level 1 Left of Double Room"
cave1_double_room_r = "Cave Level 1 Right of Double Room"

cave1_ne_1 = "Cave Level 1 NE By Save Top Dupe 1"
cave1_ne_2 = "Cave Level 1 NE By Save Top Dupe 2"
cave1_ne_3 = "Cave Level 1 NE By Save Bottom Dupe 1"
cave1_ne_4 = "Cave Level 1 NE By Save Bottom Dupe 2"
cave1_ne_5 = "Cave Level 1 NE By Save Bottom Dupe 3"
cave1_ne_hidden_room_1 = "Cave Level 1 NE Cache Dupe 1"
cave1_ne_hidden_room_2 = "Cave Level 1 NE Cache Dupe 2"
cave1_ne_hidden_room_3 = "Cave Level 1 NE Cache Dupe 3"
cave1_ne_hidden_room_4 = "Cave Level 1 NE Cache Dupe 4"
cave1_ne_hidden_room_5 = "Cave Level 1 NE Cache Dupe 5"
cave1_ne_grubs = "Cave Level 1 NE Miniboss Room"
cave1_secret_tunnel_1 = "Cave Level 1 Secret Tunnel Top"
cave1_secret_tunnel_2 = "Cave Level 1 Secret Tunnel Middle"
cave1_secret_tunnel_3 = "Cave Level 1 Secret Tunnel Bottom"
cave1_n_bridges_1 = "Cave Level 1 North Bridge Island Left Bottom"
cave1_n_bridges_2 = "Cave Level 1 North Bridge Island Top Dupe 1"
cave1_n_bridges_3 = "Cave Level 1 North Bridge Island Top Dupe 2"
cave1_n_bridges_4 = "Cave Level 1 North Bridge Island Far Left"
cave1_n_bridges_5 = "Cave Level 1 North Bridge Island Left Top"
cave1_secret_ne = "Cave Level 1 NE Secret Room"
cave1_secret_n_hidden_room = "Cave Level 1 Secret Room in NE Cache"

cave1_e_1 = "Cave Level 1 East by Temple Left"
cave1_e_2 = "Cave Level 1 East by Temple Bottom"
cave1_e_3 = "Cave Level 1 East by Temple Right"
cave1_secret_e = "Cave Level 1 East Secret Room"
cave1_red_bridge_e = "Cave Level 1 East of Red Bridge"
cave1_se_1 = "Cave Level 1 SE Dupe 1"
cave1_se_2 = "Cave Level 1 SE Dupe 2"

cave1_water_s_1 = "Cave Level 1 South Underwater by Storeroom Left"
cave1_water_s_2 = "Cave Level 1 South Underwater by Storeroom Bottom"
cave1_water_s_3 = "Cave Level 1 South Underwater Right Top"
cave1_water_s_4 = "Cave Level 1 South Underwater Right Bottom"
cave1_water_s_5 = "Cave Level 1 South Underwater Green Switch"
cave1_water_s_shore = "Cave Level 1 South Water Shore"

cave1_green_bridge_1 = "Cave Level 1 Green Bridge Dupe 1"
cave1_green_bridge_2 = "Cave Level 1 Green Bridge Dupe 2"
cave1_krilith_ledge_n = "Cave Level 1 Storeroom Ledge North"
cave1_krilith_ledge_e = "Cave Level 1 Storeroom Ledge East"
cave1_krilith_door = "Cave Level 1 Storeroom Entrance"

cave1_temple_hall_1 = "Cave Level 1 Temple Bottom Dupe 1"
cave1_temple_hall_2 = "Cave Level 1 Temple Bottom Dupe 2"
cave1_temple_hall_3 = "Cave Level 1 Temple Bottom Dupe 3"
cave1_temple_end_1 = "Cave Level 1 Temple Top Dupe 1"
cave1_temple_end_2 = "Cave Level 1 Temple Top Dupe 2"
cave1_temple_end_3 = "Cave Level 1 Temple Top Dupe 3"
cave1_temple_end_4 = "Cave Level 1 Temple Top Dupe 4"

c1_n_puzzle_1 = "Cave Level 1 North Puzzle Reward 1"
c1_n_puzzle_2 = "Cave Level 1 North Puzzle Reward 2"
c1_n_puzzle_3 = "Cave Level 1 North Puzzle Reward 3"
c1_n_puzzle_4 = "Cave Level 1 North Puzzle Reward 4"
c1_e_puzzle_1 = "Cave Level 1 East Puzzle Reward 1"
c1_e_puzzle_2 = "Cave Level 1 East Puzzle Reward 2"
c1_e_puzzle_3 = "Cave Level 1 East Puzzle Reward 3"
c1_e_puzzle_4 = "Cave Level 1 East Puzzle Reward 4"

# Boss 1
boss1_guard_l = "Dune Sharks Room Left of Guard"
boss1_guard_r_1 = "Dune Sharks Room Right of Guard Dupe 1"
boss1_guard_r_2 = "Dune Sharks Room Right of Guard Dupe 2"

boss1_bridge = "Dune Sharks Bridge"
boss1_bridge_n = "Dune Sharks Above Bridge"
boss1_secret = "Dune Sharks Secret"

# Passage
p_ent2_secret = "Passage Entrance Secret"
p_mid1_1 = "Passage Middle Slime Cavern Dupe 1"
p_mid1_2 = "Passage Middle Slime Cavern Dupe 2"
p_mid2_1 = "Passage Middle Arrow Cavern Entrance"
p_mid2_2 = "Passage Middle Arrow Cavern End Dupe 1"
p_mid2_3 = "Passage Middle Arrow Cavern End Dupe 2"
p_mid2_4 = "Passage Middle Arrow Cavern End Dupe 3"
p_mid3_secret_1 = "Passage Middle Secret Cavern Left"
p_mid3_secret_2 = "Passage Middle Secret Cavern Middle"
p_mid3_secret_3 = "Passage Middle Secret Cavern Right"
p_mid3_secret_4 = "Passage Middle Secret Cavern Far Right"
p_mid4_1 = "Passage Middle Bridge Cavern North"
p_mid4_2 = "Passage Middle Bridge Cavern Bridge"
p_mid4_3 = "Passage Middle Bridge Cavern South Dupe 1"
p_mid4_4 = "Passage Middle Bridge Cavern South Dupe 2"
p_mid5_1 = "Passage Middle Temple Stockpile North"
p_mid5_2 = "Passage Middle Temple Stockpile East"
p_mid5_secret = "Passage Middle Temple Stockpile Secret"
p_end1_secret = "Passage End Secret"
p_end3_1 = "Passage End Hidden Room Dupe 1"
p_end3_2 = "Passage End Hidden Room Dupe 2"

p_puzzle_1 = "Passage Puzzle Reward 1"
p_puzzle_2 = "Passage Puzzle Reward 2"
p_puzzle_3 = "Passage Puzzle Reward 3"
p_puzzle_4 = "Passage Puzzle Reward 4"

# Temple Entrance
temple_entrance_l = "Temple Entrance Break Block Dupe 1"
temple_entrance_r = "Temple Entrance Break Block Dupe 2"

# Temple Floor 1
t1_above_s_bridge = "Temple Floor 1 Above South Bridge"
t1_s_bridge_1 = "Temple Floor 1 South Bridge Left Dupe 1"
t1_s_bridge_2 = "Temple Floor 1 South Bridge Left Dupe 2"
t1_s_bridge_3 = "Temple Floor 1 South Bridge Left Dupe 3"
t1_s_bridge_4 = "Temple Floor 1 South Bridge Middle Dupe 1"
t1_s_bridge_5 = "Temple Floor 1 South Bridge Middle Dupe 2"
t1_s_bridge_6 = "Temple Floor 1 South Bridge Middle Dupe 3"
t1_sw_sun_room_1 = "Temple Floor 1 SW Sunbeam Room Dupe 1"
t1_sw_sun_room_2 = "Temple Floor 1 SW Sunbeam Room Dupe 2"
t1_sw_corner_room = "Temple Floor 1 SW Corner Room"
t1_sw_hidden_room_1 = "Temple Floor 1 SW Cache Dupe 1"
t1_sw_hidden_room_2 = "Temple Floor 1 SW Cache Dupe 2"
t1_sw_hidden_room_3 = "Temple Floor 1 SW Cache Dupe 3"
t1_sw_hidden_room_4 = "Temple Floor 1 SW Cache Dupe 4"

t1_sw_sdoor_1 = "Temple Floor 1 SW Gate Room Left of Spikes"
t1_sw_sdoor_2 = "Temple Floor 1 SW Gate Room Mana Drain Panel"
t1_sw_sdoor_3 = "Temple Floor 1 SW Gate Room Center"
t1_sw_sdoor_4 = "Temple Floor 1 SW Gate Room Right Bottom"
t1_sw_sdoor_5 = "Temple Floor 1 SW Gate Room Right Top"

t1_double_gate_1 = "Temple Floor 1 Double Gate Room Spikes"
t1_double_gate_2 = "Temple Floor 1 Double Gate Room Dupe 1"
t1_double_gate_3 = "Temple Floor 1 Double Gate Room Dupe 2"
t1_double_gate_hidden = "Temple Floor 1 Double Gate Room Behind Scenery"
t1_behind_bars_entrance = "Temple Floor 1 Behind Bars by Entrance"
t1_e_of_double_gate_room_1 = "Temple Floor 1 Fireball Runway Room Dupe 1"
t1_e_of_double_gate_room_2 = "Temple Floor 1 Fireball Runway Room Bottom Left"
t1_e_of_double_gate_room_3 = "Temple Floor 1 Fireball Runway Room Bottom Right Dupe 1"
t1_e_of_double_gate_room_4 = "Temple Floor 1 Fireball Runway Room Bottom Right Dupe 2"
t1_mana_drain_fire_trap = "Temple Floor 1 Fireball Runway"
t1_mana_drain_fire_trap_reward_1 = "Temple Floor 1 Fireball Runway End Dupe 1"
t1_mana_drain_fire_trap_reward_2 = "Temple Floor 1 Fireball Runway End Dupe 2"
t1_mana_drain_fire_trap_passage = "Temple Floor 1 Fireball Runway Passage"

t1_double_gate_behind_block = "Temple Floor 1 Double Gate Room Behind Block"
t1_s_of_sun_turret = "Temple Floor 1 South of NW Tower Room"
t1_sun_turret_1 = "Temple Floor 1 NW Tower Room NW"
t1_sun_turret_2 = "Temple Floor 1 NW Tower Room North"
t1_sun_turret_3 = "Temple Floor 1 NW Tower Room Far North"
t1_fire_trap_by_sun_turret_1 = "Temple Floor 1 NW Fire Trap Top Far Left"
t1_fire_trap_by_sun_turret_2 = "Temple Floor 1 NW Fire Trap Top Left Dupe 1"
t1_fire_trap_by_sun_turret_3 = "Temple Floor 1 NW Fire Trap Top Left Dupe 2"
t1_fire_trap_by_sun_turret_4 = "Temple Floor 1 NW Fire Trap Bottom"

t1_ice_turret_1 = "Temple Floor 1 East Tower Room Left"
t1_ice_turret_2 = "Temple Floor 1 East Tower Room Right"
t1_telarian_1 = "Temple Floor 1 Telarian Left Dupe 1"
t1_telarian_2 = "Temple Floor 1 Telarian Left Dupe 2"
t1_telarian_3 = "Temple Floor 1 Telarian Left Dupe 3"
t1_telarian_4 = "Temple Floor 1 Telarian Right"
t1_telarian_5 = "Temple Floor 1 Telarian Middle"
t1_boulder_hallway_by_ice_turret_1 = "Temple Floor 1 East Tower Boulder Hallway Top Dupe 1"
t1_boulder_hallway_by_ice_turret_2 = "Temple Floor 1 East Tower Boulder Hallway Top Dupe 2"
t1_boulder_hallway_by_ice_turret_3 = "Temple Floor 1 East Tower Boulder Hallway Top Dupe 3"
t1_boulder_hallway_by_ice_turret_4 = "Temple Floor 1 East Tower Boulder Hallway"
t1_ice_turret_boulder_break_block = "Temple Floor 1 East Tower Boulder Breakable Block"
t1_n_sunbeam = "Temple Floor 1 North Sunbeam"
t1_n_sunbeam_treasure_1 = "Temple Floor 1 North Sunbeam Treasure Middle"
t1_n_sunbeam_treasure_2 = "Temple Floor 1 North Sunbeam Treasure Right"
t1_n_sunbeam_treasure_3 = "Temple Floor 1 North Sunbeam Treasure Left"

t1_n_cache_by_ice_turret_1 = "Temple Floor 1 East Tower NW Gate Room Left"
t1_n_cache_by_ice_turret_2 = "Temple Floor 1 East Tower NW Gate Room Middle Dupe 1"
t1_n_cache_by_ice_turret_3 = "Temple Floor 1 East Tower NW Gate Room Middle Dupe 2"
t1_n_cache_by_ice_turret_4 = "Temple Floor 1 East Tower NW Gate Room Right Bottom"
t1_n_cache_by_ice_turret_5 = "Temple Floor 1 East Tower NW Gate Room Right Top"

t1_s_cache_by_ice_turret_1 = "Temple Floor 1 East Tower SE Gate Room Left"
t1_s_cache_by_ice_turret_2 = "Temple Floor 1 East Tower SE Gate Room Right"
t1_s_cache_by_ice_turret_3 = "Temple Floor 1 East Tower SE Gate Room Right Dupe"

t1_ledge_after_block_trap_1 = "Temple Floor 1 Ledge North of 5 Block Traps Top"
t1_ledge_after_block_trap_2 = "Temple Floor 1 Ledge North of 5 Block Traps Bottom"
t1_ice_block_chamber_1 = "Temple Floor 1 Miniboss Room Top-Left"
t1_ice_block_chamber_2 = "Temple Floor 1 Miniboss Room Top-Right"
t1_ice_block_chamber_3 = "Temple Floor 1 Miniboss Room Bottom"
t1_node_2_1 = "Temple Floor 1 Node 2 Dupe 1"
t1_node_2_2 = "Temple Floor 1 Node 2 Dupe 2"
t1_node_2_passage_1 = "Temple Floor 1 Node 2 Passage Left"
t1_node_2_passage_2 = "Temple Floor 1 Node 2 Passage Middle"
t1_node_2_passage_3 = "Temple Floor 1 Node 2 Passage Right"
t1_e_gold_beetles = "Temple Floor 1 East Enemy Jail"

t1_sun_block_hall_1 = "Temple Floor 1 Sun Block Hall Alcove Top"
t1_sun_block_hall_2 = "Temple Floor 1 Sun Block Hall Alcove Bottom"
t1_sun_block_hall_3 = "Temple Floor 1 Sun Block Hall Alcove Right"
t1_sun_block_hall_4 = "Temple Floor 1 Sun Block Hall Alcove Far Right"

t1_telarian_ice = "Temple Floor 1 Telarian Ice Block"
t1_ice_block_chamber_ice = "Temple Floor 1 Miniboss Room Ice Block"

t1_w_puzzle_1 = "Temple Floor 1 West Puzzle Reward 1"
t1_w_puzzle_2 = "Temple Floor 1 West Puzzle Reward 2"
t1_w_puzzle_3 = "Temple Floor 1 West Puzzle Reward 3"
t1_w_puzzle_4 = "Temple Floor 1 West Puzzle Reward 4"
t1_e_puzzle_1 = "Temple Floor 1 East Puzzle Reward 1"
t1_e_puzzle_2 = "Temple Floor 1 East Puzzle Reward 2"
t1_e_puzzle_3 = "Temple Floor 1 East Puzzle Reward 3"
t1_e_puzzle_4 = "Temple Floor 1 East Puzzle Reward 4"

# Boss 2 Defeated
boss2_nw = "Krilith Reward NW"
boss2_se = "Krilith Reward SE"

# Temple Floor 2
t2_n_of_portal = "Temple Floor 2 North of Portal"
t2_s_of_portal = "Temple Floor 2 South of Portal"
t2_w_spike_trap_1 = "Temple Floor 2 W Spike Trap Left"
t2_w_spike_trap_2 = "Temple Floor 2 W Spike Trap Right"
t2_nw_puzzle_cache_1 = "Temple Floor 2 NW Puzzle Cache Dupe 1"
t2_nw_puzzle_cache_2 = "Temple Floor 2 NW Puzzle Cache Dupe 2"
t2_nw_puzzle_cache_3 = "Temple Floor 2 NW Puzzle Cache Dupe 3"
t2_nw_puzzle_cache_4 = "Temple Floor 2 NW Puzzle Cache Dupe 4"
t2_nw_puzzle_cache_5 = "Temple Floor 2 NW Puzzle Cache Dupe 5"
t2_nw_of_s_ice_turret = "Temple Floor 2 Across from West Rune Panel"
t2_w_hall_dead_end_1 = "Temple Floor 2 West T Hall Left Dupe 1"
t2_w_hall_dead_end_2 = "Temple Floor 2 West T Hall Left Dupe 2"
t2_w_hall_dead_end_3 = "Temple Floor 2 West T Hall Left Dupe 3"
t2_w_hall_dead_end_4 = "Temple Floor 2 West T Hall Right"
t2_w_hall_dead_end_5 = "Temple Floor 2 West T Hall Left Dupe 4"
t2_n_of_sw_gate_1 = "Temple Floor 2 NW of SW Gate Top"
t2_n_of_sw_gate_2 = "Temple Floor 2 NW of SW Gate Bottom"
t2_fire_trap_maze_1 = "Temple Floor 2 Fire Trap Maze Balcony Upper"
t2_fire_trap_maze_2 = "Temple Floor 2 Fire Trap Maze Balcony Lower"
t2_fire_trap_maze_3 = "Temple Floor 2 Middle Fireball Runway Upper"
t2_fire_trap_maze_4 = "Temple Floor 2 Middle Fireball Runway Lower"
t2_fire_trap_maze_5 = "Temple Floor 2 Fire Trap Maze Upper"
t2_fire_trap_maze_6 = "Temple Floor 2 Fire Trap Maze Lower"
t2_teleporter = "Temple Floor 2 Teleporter Room"
t2_e_outside_gold_beetle_cage_1 = "Temple Floor 2 Outside East Enemy Jail Dupe 1"
t2_e_outside_gold_beetle_cage_2 = "Temple Floor 2 Outside East Enemy Jail Dupe 2"
t2_boulder_chamber_1 = "Temple Floor 2 East Miniboss Room NW"
t2_boulder_chamber_2 = "Temple Floor 2 East Miniboss Room Right Boulder"
t2_boulder_chamber_3 = "Temple Floor 2 East Miniboss Room NE"
t2_boulder_chamber_4 = "Temple Floor 2 East Miniboss Room Bottom"
t2_s_balcony_1 = "Temple Floor 2 South Balcony Left"
t2_s_balcony_2 = "Temple Floor 2 South Balcony Right"
t2_se_banner_chamber_1 = "Temple Floor 2 SE Banner Chamber Banner Left"
t2_se_banner_chamber_2 = "Temple Floor 2 SE Banner Chamber Banner Right"
t2_se_banner_chamber_3 = "Temple Floor 2 SE Banner Chamber Banner Bottom"
t2_se_banner_chamber_4 = "Temple Floor 2 SE Banner Chamber NW"
t2_se_banner_chamber_5 = "Temple Floor 2 SE Banner Chamber NE"
t2_se_fireball_hall = "Temple Floor 2 SE Fireball Hall"

t2_sw_gate = "Temple Floor 2 in SW Gate"
t2_s_node_room_1 = "Temple Floor 2 South Node Room Right Dupe 1"
t2_s_node_room_2 = "Temple Floor 2 South Node Room Right Dupe 2"
t2_s_node_room_3 = "Temple Floor 2 South Node Room Right Dupe 3"
t2_s_sunbeam_1 = "Temple Floor 2 South Sunbeam Top"
t2_s_sunbeam_2 = "Temple Floor 2 South Sunbeam Bottom"
t2_sw_jail_1 = "Temple Floor 2 SW Cell Middle"
t2_sw_jail_2 = "Temple Floor 2 SW Cell Left"
t2_left_of_pof_switch_1 = "Temple Floor 2 Left of PoF Switch Left"
t2_left_of_pof_switch_2 = "Temple Floor 2 Left of PoF Switch Right"
t2_right_of_pof_switch = "Temple Floor 2 Right of PoF Switch on Spikes"

t2_nw_ice_turret_1 = "Temple Floor 2 NW Towers Safety Room Bottom-Left Dupe 1"
t2_nw_ice_turret_2 = "Temple Floor 2 NW Towers Safety Room Bottom-Left Dupe 2"
t2_nw_ice_turret_3 = "Temple Floor 2 NW Towers Safety Room Bottom-Left Dupe 3"
t2_nw_ice_turret_4 = "Temple Floor 2 NW Towers Safety Room Top"
t2_nw_under_block = "Temple Floor 2 NW Block Trap"
t2_nw_gate_1 = "Temple Floor 2 NW Gate Left"
t2_nw_gate_2 = "Temple Floor 2 NW Gate Right"
t2_nw_gate_3 = "Temple Floor 2 Right of NW Gate"

t2_boulder_room_1 = "Temple Floor 2 Hidden Boulder Room Top"
t2_boulder_room_2 = "Temple Floor 2 Hidden Boulder Room Right"
t2_boulder_room_block = "Temple Floor 2 Hidden Boulder Room Under Block"
t2_mana_drain_fire_trap_1 = "Temple Floor 2 North Fireball Runway Dupe 1"
t2_mana_drain_fire_trap_2 = "Temple Floor 2 North Fireball Runway Dupe 2"
t2_jones_hallway = "Temple Floor 2 Indiana Jones Hallway"
t2_gold_beetle_barricade = "Temple Floor 2 West Enemy Jail Barricade"
t2_w_gold_beetle_room_1 = "Temple Floor 2 West Enemy Jail Dupe 1"
t2_w_gold_beetle_room_2 = "Temple Floor 2 West Enemy Jail Dupe 2"
t2_w_gold_beetle_room_3 = "Temple Floor 2 West Enemy Jail Dupe 3"
t2_w_gold_beetle_room_4 = "Temple Floor 2 West Enemy Jail Dupe 4"

t2_w_ice_block_gate = "Temple Floor 2 West Ice Block Gate"
t2_e_ice_block_gate = "Temple Floor 2 East Ice Block Gate"

t2_se_light_bridge_1 = "Temple Floor 2 SE Light Bridge Left"
t2_se_light_bridge_2 = "Temple Floor 2 SE Light Bridge Right"
t2_s_light_bridge_1 = "Temple Floor 2 South Light Bridge Dupe 1"
t2_s_light_bridge_2 = "Temple Floor 2 South Light Bridge Dupe 2"
t2_portal_gate = "Temple Floor 2 Portal Gate"

t2_floor3_cache_1 = "Temple Floor 2 Ornate Room Left Dupe 1"
t2_floor3_cache_2 = "Temple Floor 2 Ornate Room Left Dupe 2"
t2_floor3_cache_3 = "Temple Floor 2 Ornate Room Top Right"
t2_floor3_cache_4 = "Temple Floor 2 Ornate Room Left Dupe 3"
t2_floor3_cache_5 = "Temple Floor 2 Ornate Room Left Dupe 4"
t2_floor3_cache_6 = "Temple Floor 2 Ornate Room Bottom Right"
t2_floor3_cache_gate = "Temple Floor 2 Ornate Room Gate"

t2_n_puzzle_1 = "Temple Floor 2 North Puzzle Reward 1"
t2_n_puzzle_2 = "Temple Floor 2 North Puzzle Reward 2"
t2_n_puzzle_3 = "Temple Floor 2 North Puzzle Reward 3"
t2_n_puzzle_4 = "Temple Floor 2 North Puzzle Reward 4"
t2_nw_puzzle_1 = "Temple Floor 2 Northwest Puzzle Reward 1"
t2_nw_puzzle_2 = "Temple Floor 2 Northwest Puzzle Reward 2"
t2_nw_puzzle_3 = "Temple Floor 2 Northwest Puzzle Reward 3"
t2_nw_puzzle_4 = "Temple Floor 2 Northwest Puzzle Reward 4"
t2_e_puzzle_1 = "Temple Floor 2 East Puzzle Reward 1"
t2_e_puzzle_2 = "Temple Floor 2 East Puzzle Reward 2"
t2_e_puzzle_3 = "Temple Floor 2 East Puzzle Reward 3"
t2_e_puzzle_4 = "Temple Floor 2 East Puzzle Reward 4"
t2_sw_puzzle_1 = "Temple Floor 2 Southwest Puzzle Reward 1"
t2_sw_puzzle_2 = "Temple Floor 2 Southwest Puzzle Reward 2"
t2_sw_puzzle_3 = "Temple Floor 2 Southwest Puzzle Reward 3"
t2_sw_puzzle_4 = "Temple Floor 2 Southwest Puzzle Reward 4"

# Temple Floor 3
t3_s_balcony_turret_1 = "Temple Floor 3 South Balcony Tower Top"
t3_s_balcony_turret_2 = "Temple Floor 3 South Balcony Tower Right"
t3_n_turret_1 = "Temple Floor 3 North Tower"
t3_n_turret_2 = "Temple Floor 3 North Boulder"
t3_boulder_block = "Temple Floor 3 Boulder Block"
t3_e_turret_spikes = "Temple Floor 3 East Tower by Spikes"

t3_s_gate = "Temple Floor 3 South Gate"
t3_n_node_blocks_1 = "Temple Floor 3 Sun Block Wall Far Left"
t3_n_node_blocks_2 = "Temple Floor 3 Sun Block Wall Left"
t3_n_node_blocks_3 = "Temple Floor 3 Sun Block Wall Middle"
t3_n_node_blocks_4 = "Temple Floor 3 Sun Block Wall Right"
t3_n_node_blocks_5 = "Temple Floor 3 Sun Block Wall Far Right"

t3_s_node_cache_1 = "Temple Floor 3 South Node Cache Left"
t3_s_node_cache_2 = "Temple Floor 3 South Node Cache Right Dupe 1"
t3_s_node_cache_3 = "Temple Floor 3 South Node Cache Right Dupe 2"

t3_m_balcony_corridor = "Temple Floor 3 NE Balcony Corridor"

t3_n_node_1 = "Temple Floor 3 North Node Right Dupe 1"
t3_n_node_2 = "Temple Floor 3 North Node Right Dupe 2"
t3_n_node_3 = "Temple Floor 3 North Node Right Dupe 3"

t3_boss_fall_1_1 = "Temple Floor 3 Fall From Right Boss Platform Left"
t3_boss_fall_1_2 = "Temple Floor 3 Fall From Right Boss Platform Top-Right"
t3_boss_fall_1_3 = "Temple Floor 3 Fall From Right Boss Platform Bottom"

t3_boss_fall_2_1 = "Temple Floor 3 Fall From Top Boss Platform Top-Left"
t3_boss_fall_2_2 = "Temple Floor 3 Fall From Top Boss Platform Right"
t3_boss_fall_2_3 = "Temple Floor 3 Fall From Top Boss Platform Bottom-Left"

t3_boss_fall_3_1 = "Temple Floor 3 Fall From Left Boss Platform Top"
t3_boss_fall_3_2 = "Temple Floor 3 Fall From Left Boss Platform Left"
t3_boss_fall_3_3 = "Temple Floor 3 Fall From Left Boss Platform Right"
t3_boss_fall_3_4 = "Temple Floor 3 Fall From Left Boss Platform Bottom"

t3_puzzle_1 = "Temple Floor 3 Puzzle Reward 1"
t3_puzzle_2 = "Temple Floor 3 Puzzle Reward 2"
t3_puzzle_3 = "Temple Floor 3 Puzzle Reward 3"
t3_puzzle_4 = "Temple Floor 3 Puzzle Reward 4"

# PoF
pof_1_ent_1 = "Pyramid of Fear Level 1 Entrance Dupe 1"
pof_1_ent_2 = "Pyramid of Fear Level 1 Entrance Dupe 2"
pof_1_ent_3 = "Pyramid of Fear Level 1 Entrance Dupe 3"
pof_1_ent_4 = "Pyramid of Fear Level 1 Entrance Dupe 4"
pof_1_ent_5 = "Pyramid of Fear Level 1 Entrance Dupe 5"
pof_1_sw_left_1 = "Pyramid of Fear Level 1 SW Left Room Dupe 1"
pof_1_sw_left_2 = "Pyramid of Fear Level 1 SW Left Room Dupe 2"
pof_1_sw_left_3 = "Pyramid of Fear Level 1 SW Left Room Dupe 3"
pof_1_sw_left_4 = "Pyramid of Fear Level 1 SW Left Room Dupe 4"
pof_1_sw_left_5 = "Pyramid of Fear Level 1 SW Left Room Dupe 5"
pof_1_sw_left_6 = "Pyramid of Fear Level 1 SW Left Room Dupe 6"
pof_1_sw_left_7 = "Pyramid of Fear Level 1 SW Left Room Dupe 7"
pof_1_sw_left_8 = "Pyramid of Fear Level 1 SW Left Room Dupe 8"
pof_1_sw_left_9 = "Pyramid of Fear Level 1 SW Left Room Dupe 9"
pof_1_sw_left_10 = "Pyramid of Fear Level 1 SW Left Room Dupe 10"
pof_1_sw_left_11 = "Pyramid of Fear Level 1 SW Left Room Dupe 11"
pof_1_s_1 = "Pyramid of Fear Level 1 South Room Dupe 1"
pof_1_s_2 = "Pyramid of Fear Level 1 South Room Dupe 2"
pof_1_s_3 = "Pyramid of Fear Level 1 South Room Dupe 3"
pof_1_s_4 = "Pyramid of Fear Level 1 South Room Dupe 4"
pof_1_s_5 = "Pyramid of Fear Level 1 South Room Dupe 5"
pof_1_s_6 = "Pyramid of Fear Level 1 South Room Dupe 6"
pof_1_s_7 = "Pyramid of Fear Level 1 South Room Dupe 7"
pof_1_s_8 = "Pyramid of Fear Level 1 South Room Dupe 8"
pof_1_s_9 = "Pyramid of Fear Level 1 South Room Dupe 9"
pof_1_s_10 = "Pyramid of Fear Level 1 South Room Dupe 10"
pof_1_s_11 = "Pyramid of Fear Level 1 South Room Dupe 11"
pof_1_s_12 = "Pyramid of Fear Level 1 South Room Dupe 12"
pof_1_s_13 = "Pyramid of Fear Level 1 South Room Dupe 13"

pof_1_confuse_corner_1 = "Pyramid of Fear Level 1 Confuse Corner Dupe 1"
pof_1_confuse_corner_2 = "Pyramid of Fear Level 1 Confuse Corner Dupe 2"
pof_1_confuse_corner_3 = "Pyramid of Fear Level 1 Confuse Corner Dupe 3"
pof_1_confuse_corner_4 = "Pyramid of Fear Level 1 Confuse Corner Dupe 4"
pof_1_n_1 = "Pyramid of Fear Level 1 North Room Dupe 1"
pof_1_n_2 = "Pyramid of Fear Level 1 North Room Dupe 2"
pof_1_n_3 = "Pyramid of Fear Level 1 North Room Dupe 3"
pof_1_n_4 = "Pyramid of Fear Level 1 North Room Dupe 4"
pof_1_n_5 = "Pyramid of Fear Level 1 North Room Dupe 5"
pof_1_n_6 = "Pyramid of Fear Level 1 North Room Dupe 6"
pof_1_n_7 = "Pyramid of Fear Level 1 North Room Dupe 7"
pof_1_n_8 = "Pyramid of Fear Level 1 North Room Dupe 8"
pof_1_n_9 = "Pyramid of Fear Level 1 North Room Dupe 9"
pof_1_c_hall_1 = "Pyramid of Fear Level 1 C Hall Dupe 1"
pof_1_c_hall_2 = "Pyramid of Fear Level 1 C Hall Dupe 2"
pof_1_c_hall_3 = "Pyramid of Fear Level 1 C Hall Dupe 3"
pof_1_c_hall_4 = "Pyramid of Fear Level 1 C Hall Dupe 4"
pof_1_c_hall_5 = "Pyramid of Fear Level 1 C Hall Dupe 5"
pof_1_c_hall_6 = "Pyramid of Fear Level 1 C Hall Dupe 6"

pof_1_end_1 = "Pyramid of Fear Level 1 End Dupe 1"
pof_1_end_2 = "Pyramid of Fear Level 1 End Dupe 2"
pof_1_end_3 = "Pyramid of Fear Level 1 End Dupe 3"
pof_1_end_4 = "Pyramid of Fear Level 1 End Dupe 4"
pof_1_end_5 = "Pyramid of Fear Level 1 End Dupe 5"

pof_2_ent_1 = "Pyramid of Fear Level 2 Entrance Dupe 1"
pof_2_ent_2 = "Pyramid of Fear Level 2 Entrance Dupe 2"
pof_2_ent_3 = "Pyramid of Fear Level 2 Entrance Dupe 3"
pof_2_ent_4 = "Pyramid of Fear Level 2 Entrance Dupe 4"
pof_2_ent_5 = "Pyramid of Fear Level 2 Entrance Dupe 5"
pof_2_ent_6 = "Pyramid of Fear Level 2 Entrance Dupe 6"
pof_2_confuse_hall_1 = "Pyramid of Fear Level 2 Confuse Hall Dupe 1"
pof_2_confuse_hall_2 = "Pyramid of Fear Level 2 Confuse Hall Dupe 2"
pof_2_confuse_hall_3 = "Pyramid of Fear Level 2 Confuse Hall Dupe 3"
pof_2_confuse_hall_4 = "Pyramid of Fear Level 2 Confuse Hall Dupe 4"
pof_2_sw_1 = "Pyramid of Fear Level 2 SW Dupe 1"
pof_2_sw_2 = "Pyramid of Fear Level 2 SW Dupe 2"
pof_2_sw_3 = "Pyramid of Fear Level 2 SW Dupe 3"
pof_2_sw_4 = "Pyramid of Fear Level 2 SW Dupe 4"
pof_2_ne_1 = "Pyramid of Fear Level 2 NE Room Dupe 1"
pof_2_ne_2 = "Pyramid of Fear Level 2 NE Room Dupe 2"
pof_2_ne_3 = "Pyramid of Fear Level 2 NE Room Dupe 3"
pof_2_ne_4 = "Pyramid of Fear Level 2 NE Room Dupe 4"

pof_3_safety_room_1 = "Pyramid of Fear Level 3 Start Room Top"
pof_3_safety_room_2 = "Pyramid of Fear Level 3 Start Room Middle"
pof_3_safety_room_3 = "Pyramid of Fear Level 3 Start Room Bottom"
pof_3_end_1 = "Pyramid of Fear Level 3 Exit Top"
pof_3_end_2 = "Pyramid of Fear Level 3 Exit Far Left"
pof_3_end_3 = "Pyramid of Fear Level 3 Exit Left"
pof_3_end_4 = "Pyramid of Fear Level 3 Exit Right"
pof_3_end_5 = "Pyramid of Fear Level 3 Exit Bottom"

pof_puzzle_1 = "Pyramid of Fear Puzzle Reward 1"
pof_puzzle_2 = "Pyramid of Fear Puzzle Reward 2"
pof_puzzle_3 = "Pyramid of Fear Puzzle Reward 3"
pof_puzzle_4 = "Pyramid of Fear Puzzle Reward 4"

# Enemy locations
c3_miniboss_tick_1 = "Cave Level 3 Miniboss Loot Dupe 1"
c3_miniboss_tick_2 = "Cave Level 3 Miniboss Loot Dupe 2"
c3_tower_plant = "Cave Level 3 Tower by Exit Loot"
c3_tower_plant_small_1 = "Cave Level 3 Mini Flower NW of Broken Bridge Loot"
c3_tower_plant_small_2 = "Cave Level 3 Mini Flower West of Broken Bridge Loot"
c3_tower_plant_small_3 = "Cave Level 3 NE Mini Flowers NW Flower Loot"
c3_tower_plant_small_4 = "Cave Level 3 NE Mini Flowers SW Flower Loot"
c3_tower_plant_small_5 = "Cave Level 3 NE Mini Flowers NE Flower Loot"
c3_tower_plant_small_6 = "Cave Level 3 NE Mini Flowers SE Flower Loot"
c3_tower_plant_small_7 = "Cave Level 3 Mini Flower SW of Trapped Guard Loot"
c3_tower_plant_small_8 = "Cave Level 3 Mini Flower East of Trapped Guard Loot"

c2_miniboss_maggot_w_1 = "Cave Level 2 West Miniboss Loot Dupe 1"
c2_miniboss_maggot_w_2 = "Cave Level 2 West Miniboss Loot Dupe 2"
c2_miniboss_maggot_s_1 = "Cave Level 2 South Miniboss Loot Dupe 1"
c2_miniboss_maggot_s_2 = "Cave Level 2 South Miniboss Loot Dupe 2"
c2_miniboss_tick_1 = "Cave Level 2 Middle Miniboss Loot Dupe 1"
c2_miniboss_tick_2 = "Cave Level 2 Middle Miniboss Loot Dupe 2"
c2_tower_plant_1 = "Cave Level 2 North Tower Loot"
c2_tower_plant_2 = "Cave Level 2 SW Tower Loot"
c2_tower_plant_3 = "Cave Level 2 East Tower Loot"
c2_tower_plant_small_1 = "Cave Level 2 NW Mini Flowers Leftmost Flower Loot"
c2_tower_plant_small_2 = "Cave Level 2 NW Mini Flowers Middle-Right Flower Loot"
c2_tower_plant_small_3 = "Cave Level 2 North Bridge NW Mini Flower Loot"
c2_tower_plant_small_4 = "Cave Level 2 Pumps Lever Mini Flower Loot"
c2_tower_plant_small_5 = "Cave Level 2 North Bridge NE Mini Flower Loot"
c2_tower_plant_small_6 = "Cave Level 2 North Bridge North Mini Flower Loot"
c2_tower_plant_small_7 = "Cave Level 2 NW Mini Flowers Middle-Left Flower Loot"
c2_tower_plant_small_8 = "Cave Level 2 Mini Flower by Green Bridge Switch Loot"
c2_tower_plant_small_9 = "Cave Level 2 Mini Flower West of Green Bridge Switch Loot"
c2_tower_plant_small_10 = "Cave Level 2 Mini Flower by Puzzle Loot"
c2_tower_plant_small_11 = "Cave Level 2 NW Mini Flowers Rightmost Flower Loot"
c2_tower_plant_small_12 = "Cave Level 2 Mini Flower North of South Save Loot"
c2_tower_plant_small_13 = "Cave Level 2 North Bridge SE Mini Flower Loot"
c2_tower_plant_small_14 = "Cave Level 2 North Bridge South Mini Flower Loot"
c2_tower_plant_small_15 = "Cave Level 2 North Bridge SW Mini Flower Loot"
c2_tower_plant_small_16 = "Cave Level 2 Mini Flower South of South Save Loot"
c2_tower_plant_small_17 = "Cave Level 2 Middle Miniboss Arena Left Mini Flower Loot"
c2_tower_plant_small_18 = "Cave Level 2 Middle Miniboss Arena Right Mini Flower Loot"
c2_tower_plant_small_19 = "Cave Level 2 South Miniboss Area Left Mini Flower Loot"
c2_tower_plant_small_20 = "Cave Level 2 SE Mini Flowers NW Flower Loot"
c2_tower_plant_small_21 = "Cave Level 2 SE Mini Flowers NE Flower Loot"
c2_tower_plant_small_22 = "Cave Level 2 South Miniboss Area Right Mini Flower Loot"
c2_tower_plant_small_23 = "Cave Level 2 SE Mini Flowers South Flower Loot"

c1_miniboss_maggot_s_1 = "Cave Level 1 South Miniboss Loot Dupe 1"
c1_miniboss_maggot_s_2 = "Cave Level 1 South Miniboss Loot Dupe 2"
c1_miniboss_maggot_ne_1 = "Cave Level 1 NE Miniboss Loot Dupe 1"
c1_miniboss_maggot_ne_2 = "Cave Level 1 NE Miniboss Loot Dupe 2"
c1_miniboss_tick_1 = "Cave Level 1 NW Miniboss Loot Dupe 1"
c1_miniboss_tick_2 = "Cave Level 1 NW Miniboss Loot Dupe 2"
c1_tower_plant_1 = "Cave Level 1 Middle Tower Loot"
c1_tower_plant_2 = "Cave Level 1 NE Miniboss Area Tower Loot"
c1_tower_plant_3 = "Cave Level 1 SW Tower Loot"
c1_tower_plant_4 = "Cave Level 1 NE Tower Loot"
c1_tower_plant_small_1 = "Cave Level 1 NE Mini Flowers Middle-Left Flower Loot"
c1_tower_plant_small_2 = "Cave Level 1 NE Mini Flowers Leftmost Flower Loot"
c1_tower_plant_small_3 = "Cave Level 1 NE Miniboss Area NW Mini Flower Loot"
c1_tower_plant_small_4 = "Cave Level 1 NE Miniboss Area NE Mini Flower Loot"
c1_tower_plant_small_5 = "Cave Level 1 West Mini Flowers Top Flower Loot"
c1_tower_plant_small_6 = "Cave Level 1 West Mini Flowers Right Flower Loot"
c1_tower_plant_small_7 = "Cave Level 1 West Mini Flowers Bottom Flower Loot"
c1_tower_plant_small_8 = "Cave Level 1 West Mini Flowers Left Flower Loot"
c1_tower_plant_small_9 = "Cave Level 1 NE Miniboss Area SW Mini Flower Loot"
c1_tower_plant_small_10 = "Cave Level 1 NE Miniboss Area SE Mini Flower Loot"
c1_tower_plant_small_11 = "Cave Level 1 South Miniboss Area Top Mini Flower Loot"
c1_tower_plant_small_12 = "Cave Level 1 South Miniboss Area Bottom Mini Flower Loot"
c1_tower_plant_small_13 = "Cave Level 1 NE Mini Flowers Middle-Right Flower Loot"
c1_tower_plant_small_14 = "Cave Level 1 NE Mini Flowers Rightmost Flower Loot"

b1_boss_worm_1_1 = "First Dune Shark Loot Dupe 1"
b1_boss_worm_1_2 = "First Dune Shark Loot Dupe 2"
b1_boss_worm_2_1 = "Second Dune Shark Loot Dupe 1"
b1_boss_worm_2_2 = "Second Dune Shark Loot Dupe 2"
b1_boss_worm_3_1 = "Third Dune Shark Loot Dupe 1"
b1_boss_worm_3_2 = "Third Dune Shark Loot Dupe 2"
b1_boss_worm_4_1 = "Fourth Dune Shark Loot Dupe 1"
b1_boss_worm_4_2 = "Fourth Dune Shark Loot Dupe 2"
b1_boss_worm_5_1 = "Fifth Dune Shark Loot Dupe 1"
b1_boss_worm_5_2 = "Fifth Dune Shark Loot Dupe 2"
b1_boss_worm_6_1 = "Sixth Dune Shark Loot Dupe 1"
b1_boss_worm_6_2 = "Sixth Dune Shark Loot Dupe 2"
b1_boss_worm_7_1 = "Seventh Dune Shark Loot Dupe 1"
b1_boss_worm_7_2 = "Seventh Dune Shark Loot Dupe 2"
b1_boss_worm_key = "Final Dune Shark Loot"

p_tower_plant_small_1 = "Passage Middle Top-Left Mini Flower Loot"
p_tower_plant_small_2 = "Passage Middle Top-Right Mini Flower Loot"
p_tower_plant_small_3 = "Passage Middle Middle-Left Mini Flower Loot"
p_tower_plant_small_4 = "Passage Middle Bottom-Upper Mini Flower Loot"
p_tower_plant_small_5 = "Passage Middle Bottom-Lower Mini Flower Loot"
p_tower_plant_small_6 = "Passage Middle Middle-Right Mini Flower Loot"

t1_miniboss_mummy = "Temple Floor 1 Miniboss Loot"
t1_tower_fire = "Temple Floor 1 NW Tower Loot"
t1_tower_ice = "Temple Floor 1 East Tower Loot"

t2_miniboss_mummy_w = "Temple Floor 2 West Miniboss Loot"
t2_miniboss_mummy_e = "Temple Floor 2 East Miniboss Loot"
t2_tower_fire = "Temple Floor 2 NE Tower Loot"
t2_tower_ice_1 = "Temple Floor 2 NW Towers Left Tower Loot"
t2_tower_ice_2 = "Temple Floor 2 NW Towers Right Tower Loot"
t2_tower_ice_3 = "Temple Floor 2 West Tower Loot"
t2_tower_mana_1 = "Temple Floor 2 Far West Tower Loot"
t2_tower_mana_2 = "Temple Floor 2 Middle Tower Loot"
t2_tower_mana_3 = "Temple Floor 2 SW Tower Loot"

t3_tower_fire_1 = "Temple Floor 3 Far East Tower Loot"
t3_tower_fire_2 = "Temple Floor 3 West Tower Loot"
t3_tower_ice_1 = "Temple Floor 3 North Tower Loot"
t3_tower_ice_2 = "Temple Floor 3 Middle Towers Top Tower Loot"
t3_tower_ice_3 = "Temple Floor 3 Middle Towers Bottom Tower Loot"
t3_tower_mana_1 = "Temple Floor 3 East Tower Loot"
t3_tower_mana_2 = "Temple Floor 3 South Tower Loot"

b3_tower_fire_1 = "Boss 3 Top Platform Tower Loot"
b3_tower_fire_2 = "Boss 3 Right Platform Tower Loot"
b3_tower_fire_3 = "Boss 3 Left Platform Tower Loot"

# Random locations
rloc_t3_entrance = "Temple 3 Entrance"
rloc_squire = "Cave 3 Squire"
rloc_c3_secret_n = "Cave 3 Secret 1"
rloc_c3_secret_nw = "Cave 3 Secret 2"
rloc_c3_secret_s = "Cave 3 Secret 3"
rloc_c3_puzzle = "Cave 3 Puzzle 1"
rloc_pan = "Frying Pan"

rloc_c2_portal = "Cave 2 Portal"
rloc_c2_keystone = "Cave 2 Keystone"
rloc_c2_secret_1 = "Cave 2 Secret 1"
rloc_c2_secret_2 = "Cave 2 Secret 2"
rloc_c2_secret_3 = "Cave 2 Secret 3"
rloc_c2_hidden_room = "Cave 2 Hidden Room"
rloc_c2_puzzle = "Cave 2 Puzzle 1"

rloc_c1_portal = "Cave 1 Portal"
rloc_c1_keystone = "Cave 1 Keystone"
rloc_c1_secret_1 = "Cave 1 Secret 1"
rloc_c1_secret_2 = "Cave 1 Secret 2"
rloc_c1_secret_3 = "Cave 1 Secret 3"
rloc_c1_secret_4 = "Cave 1 Secret 4"
rloc_c1_secret_5 = "Cave 1 Secret 5"
rloc_c1_secret_6 = "Cave 1 Secret 6"
rloc_c1_hidden_room = "Cave 1 Hidden Room"
rloc_c1_exit = "Cave 1 Exit"
rloc_c1_puzzle_n = "Cave 1 Puzzle 1"
rloc_c1_puzzle_e = "Cave 1 Puzzle 2"

rloc_b1_secret = "Temple Boss 1 Secret 1"

rloc_passage_entrance = "Passage Entrance"
rloc_passage_middle = "Passage Middle"
rloc_passage_end = "Passage End"
rloc_p_secret_1 = "Passage Secret 1"
rloc_p_secret_2 = "Passage Secret 2"
rloc_p_secret_3 = "Passage Secret 3"
rloc_p_secret_4 = "Passage Secret 4"
rloc_p_secret_5 = "Passage Secret 5"
rloc_p_secret_6 = "Passage Secret 6"
rloc_p_secret_7 = "Passage Secret 7"
rloc_p_alley = "Passage Hidden Room"
rloc_p_puzzle = "Passage Puzzle 1"

rloc_t1_portal = "Temple 1 Portal"
rloc_t1_keystone = "Temple 1 Keystone"
rloc_t1_silver_key_s = "Temple 1 South Silver Key"
rloc_t1_silver_key_n = "Temple 1 North Silver Key"
rloc_t1_silver_key_ice_turret = "Temple 1 Ice Turret Silver Key"
rloc_t1_silver_key_funky = "Temple 1 Funky Silver Key"
rloc_t1_gold_key = "Temple 1 Gold Key"
rloc_t1_ore_funky = "Temple 1 Funky Ore"
rloc_t1_ore_e = "Temple 1 East Ore"
rloc_t1_mirror = "Temple 1 Mirror"
rloc_t1_puzzle = "Temple 1 Puzzle 1"
rloc_t1_puzzle_spawn = "Temple 1 Puzzle Spawn"
rloc_t1_puzzle_w = "Temple 1 Puzzle 1"
rloc_t1_puzzle_e = "Temple 1 Puzzle 2"
rloc_t1_sw_hidden_room = "Temple 1 Hidden Room"
rloc_t1_sw_hidden_room_random_node = "Temple 1 Hidden Room Random Node"

rloc_t2_entrance = "Temple 2 Entrance"
rloc_t2_portal = "Temple 2 Portal"
rloc_t2_keystone = "Temple 2 Keystone"
rloc_t2_puzzle_spawn_1 = "Temple 2 Puzzle Spawn EW"
rloc_t2_puzzle_spawn_2 = "Temple 2 Puzzle Spawn NS"
rloc_t2_puzzle_n = "Temple 2 Puzzle 1"
rloc_t2_puzzle_nw = "Temple 2 Puzzle 2"
rloc_t2_puzzle_e = "Temple 2 Puzzle 3"
rloc_t2_puzzle_sw = "Temple 2 Puzzle 4"
rloc_t2_jones_reward = "Temple 2 Jones Reward"
rloc_t2_gold_key = "Temple 2 Gold Key"
rloc_t2_silver_key_1 = "Temple 2 Silver Key 1"
rloc_t2_silver_key_2 = "Temple 2 Silver Key 2"
rloc_t2_pickaxe = "Pickaxe"
rloc_t2_w_hidden_room = "Temple 2 Hidden Room"

rloc_t3_s_beam_1 = "Temple 3 S Beam 1"
rloc_t3_s_beam_2 = "Temple 3 S Beam 2"
rloc_t3_s_beam_3 = "Temple 3 S Beam 3"
rloc_t3_s_beam_4 = "Temple 3 S Beam 4"
rloc_t3_s_beam_5 = "Temple 3 S Beam 5"
rloc_t3_puzzle = "Temple 3 Puzzle 1"

rloc_pof_puzzle = "PoF Puzzle 1"

shop_combo = "Combo Shop"
shop_misc = "Vitality Shop"
shop_off = "Offense Shop"
shop_def = "Defense Shop"

# Event locations
ev_c1_portal = "Cave Level 1 Activate Portal"
ev_c2_portal = "Cave Level 2 Activate Portal"
ev_c3_portal = "Cave Level 3 Activate Portal"
ev_t1_portal = "Temple Floor 1 Activate Portal"
ev_t2_portal = "Temple Floor 2 Activate Portal"
ev_t3_portal = "Temple Floor 3 Activate Portal"
ev_hub_pof_switch = "Dunes PoF Switch"
ev_cave1_pof_switch = "Cave Level 1 PoF Switch"
ev_cave2_pof_switch = "Cave Level 2 PoF Switch"
ev_cave3_pof_switch = "Cave Level 3 PoF Switch"
ev_temple1_pof_switch = "Temple Floor 1 PoF Switch"
ev_temple2_pof_switch = "Temple Floor 2 PoF Switch"
ev_temple_entrance_rock = "Temple Entrance Rock"
ev_t1_n_node = "Temple Floor 1 North Node"
ev_t1_n_node_n_mirrors = "Temple Floor 1 North Node North Mirrors"
ev_t1_n_node_s_mirror = "Temple Floor 1 North Node South Mirror"
ev_t1_s_node = "Temple Floor 1 South Node"
ev_t2_n_node = "Temple Floor 2 North Node"
ev_t2_s_node = "Temple Floor 2 South Node"
ev_t3_n_node = "Temple Floor 3 North Node"
ev_t3_s_node = "Temple Floor 3 South Node"
btn_t2_floor_blue = "Temple Floor 2 Blue Floor Button"
btn_t2_rune_n = "Temple Floor 2 North Rune Button"
btn_t2_rune_w = "Temple Floor 2 West Rune Button"
btn_t2_rune_sw = "Temple Floor 2 SW Rune Button"
btn_t2_rune_se = "Temple Floor 2 SE Rune Button"
btn_t2_rune_e = "Temple Floor 2 NE Rune Button"
ev_pof_1_se_room_panel = "PoF Level 1 SE Teleport Room Panel"
ev_pof_1_unlock_exit = "PoF Level 1 Unlock Exit"
ev_pof_2_unlock_exit = "PoF Level 2 Unlock Exit"
ev_pof_end = "Pyramid of Fear End"

ev_beat_boss_1 = "Defeat Dune Sharks"
ev_beat_boss_2 = "Defeat Krilith"
ev_beat_boss_3 = "Defeat Sha'Rand"

# Shared Event Locations
ev_victory = "Victory"
